import warnings
warnings.warn("Importing commerce.management.commands.tests.test_create_orders_for_old_enterprise_course_enrollmnet instead of lms.djangoapps.commerce.management.commands.tests.test_create_orders_for_old_enterprise_course_enrollmnet is deprecated", stacklevel=2)

from lms.djangoapps.commerce.management.commands.tests.test_create_orders_for_old_enterprise_course_enrollmnet import *
