# Generated by Django 3.2.22 on 2023-10-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgeclass_badgr_server_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeassertion',
            name='badge_class',
        ),
        migrations.RemoveField(
            model_name='badgeassertion',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='badgeclass',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='CourseCompleteImageConfiguration',
        ),
        migrations.RemoveField(
            model_name='courseeventbadgesconfiguration',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='BadgeAssertion',
        ),
        migrations.DeleteModel(
            name='BadgeClass',
        ),
        migrations.DeleteModel(
            name='CourseEventBadgesConfiguration',
        ),
    ]
