# Generated by Django 2.2.25 on 2024-02-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgeclass_badgr_server_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeassertion',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
