# Generated by Django 2.2.17 on 2021-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_wide_roles', '0002_add_system_wide_student_support_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemwideroleassignment',
            name='applies_to_all_contexts',
            field=models.BooleanField(default=False, help_text='If true, indicates that the user is effectively assigned their role for any and all contexts. Defaults to False.'),
        ),
    ]
