# Generated by Django 2.2.18 on 2021-02-08 12:33

from django.db import migrations

from openedx.core.djangoapps.system_wide_roles.constants import SUPPORT_TOOLS_ADMIN_ROLE


def create_support_tools_admin_role(apps, schema_editor):
    """
    Create the system wide support tools MFE admin role if it does not exist.
    """
    SystemWideRole = apps.get_model('system_wide_roles', 'SystemWideRole')
    SystemWideRole.objects.update_or_create(name=SUPPORT_TOOLS_ADMIN_ROLE)


def delete_support_tools_admin_role(apps, schema_editor):
    """
    Delete the system wide support tools admin role.
    """
    SystemWideRole = apps.get_model('system_wide_roles', 'SystemWideRole')
    SystemWideRole.objects.filter(
        name=SUPPORT_TOOLS_ADMIN_ROLE
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('system_wide_roles', '0003_systemwideroleassignment_applies_to_all_contexts'),
    ]

    operations = [
        migrations.RunPython(
            create_support_tools_admin_role,
            delete_support_tools_admin_role
        )
    ]
