# Generated by Django 3.2.19 on 2023-05-26 12:13

from django.db import migrations, models
import openedx.core.djangoapps.notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_context',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_preference_config',
            field=models.JSONField(default=openedx.core.djangoapps.notifications.models.get_notification_preference_config),
        ),
    ]
