# Generated by Django 4.2.10 on 2024-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20230607_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web',
            field=models.BooleanField(default=True),
        ),
    ]
