# Generated by Django 4.2.13 on 2024-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_email_notification_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_by_id',
            field=models.CharField(db_index=True, default='', max_length=42),
        ),
    ]
