# Generated by Django 4.2.20 on 2025-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_group_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group_by_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
