# Generated by Django 4.2.18 on 2025-03-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_group_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push',
            field=models.BooleanField(default=False),
        ),
    ]
