# Generated by Django 4.2.18 on 2025-02-07 05:00

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_group_by_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBrazeCampaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notification_type', models.CharField(max_length=64)),
                ('braze_campaign_id', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
