# Generated by Django 5.2.7 on 2025-12-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_push'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseNotificationPreference',
        ),
    ]
