# Generated by Django 5.2.9 on 2025-12-12 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_email_sent_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_scheduled',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this notification is waiting in buffer for digest'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'course_id', 'email_sent_on', 'email_scheduled'], name='notif_email_buffer_idx'),
        ),
    ]
