# Generated by Django 3.2.16 on 2022-11-30 15:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyreport',
            name='courses_offered',
            field=models.BigIntegerField(help_text='Total number of active unique courses.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='enrollments',
            field=models.BigIntegerField(help_text='Total number of active enrollments in the platform.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='extra_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='Extra information that will be saved in the report, E.g: site_name, openedx-release.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='generated_certificates',
            field=models.BigIntegerField(help_text='Total number of generated certificates.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='learners',
            field=models.BigIntegerField(help_text='Total number of recently active users with login in some weeks.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='registered_learners',
            field=models.BigIntegerField(help_text='Total number of users ever registered in the platform.'),
        ),
    ]
