# Generated by Django 3.2.16 on 2022-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_report', '0002_auto_20221130_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyreport',
            name='state',
            field=models.CharField(choices=[('processing', 'Processing'), ('generated', 'Generated'), ('error', 'Error')], default='processing', help_text='State of the async generating process.', max_length=24),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='courses_offered',
            field=models.BigIntegerField(default=0, help_text='Total number of active unique courses.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='enrollments',
            field=models.BigIntegerField(default=0, help_text='Total number of active enrollments in the platform.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='generated_certificates',
            field=models.BigIntegerField(default=0, help_text='Total number of generated certificates.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='learners',
            field=models.BigIntegerField(default=0, help_text='Total number of recently active users with login in some weeks.'),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='registered_learners',
            field=models.BigIntegerField(default=0, help_text='Total number of users ever registered in the platform.'),
        ),
    ]
