# Generated by Django 3.2.16 on 2023-02-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_report', '0003_add_state_field_and_add_default_values_to_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True, help_text='Date when the report was sent to external api.')),
                ('status_code', models.IntegerField(help_text='Request status code.')),
                ('request_details', models.CharField(blank=True, help_text='Information about the send request.', max_length=255, null=True)),
                ('report', models.ForeignKey(help_text='The report that was sent.', on_delete=django.db.models.deletion.CASCADE, to='survey_report.surveyreport')),
            ],
        ),
    ]
