# Generated by Django 3.2.16 on 2023-02-10 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey_report', '0004_surveyreportupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyReportAnonymousSiteID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
