# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 20:57
from __future__ import unicode_literals

from django.db import migrations


def copy_column_values(apps, schema_editor):
    """
    Copy the contents of the values field into the site_values field in both
    SiteConfiguration and SiteConfigurationHistory.
    """
    # Update all values in the model.
    SiteConfiguration = apps.get_model('site_configuration', 'SiteConfiguration')
    for site_configuration in SiteConfiguration.objects.all():
        site_configuration.site_values = site_configuration.values
        # It would be incorrect to record these saves in the history table since it is
        # just backfilling data.  Use save_without_historical_record() instead of
        # save().
        site_configuration.save_without_historical_record()

    # Update all values in the history model.
    SiteConfigurationHistory = apps.get_model('site_configuration', 'SiteConfigurationHistory')
    for historical_site_configuration in SiteConfigurationHistory.objects.all():
        historical_site_configuration.site_values = historical_site_configuration.values
        historical_site_configuration.save()


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0004_add_site_values_field'),
    ]

    operations = [
        migrations.RunPython(
            copy_column_values,
            reverse_code=migrations.RunPython.noop,  # Allow reverse migrations, but make it a no-op.
        ),
    ]
