# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0004_copy_values_to_site_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='values',
        ),
        migrations.RemoveField(
            model_name='siteconfigurationhistory',
            name='values',
        ),
    ]
