# Generated by Django 2.2.16 on 2020-11-10 14:16

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge Tahoe customization and upstream updates.
    """

    dependencies = [
        ('site_configuration', '0007_remove_values_field'),
        ('site_configuration', '0004_auto_20161120_2325'),
    ]

    operations = [
    ]
