# Generated by Django 2.2.16 on 2020-11-10 14:18

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields
import openedx.core.djangoapps.site_configuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0008_merge_tahoe_and_upstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='page_elements',
            field=jsonfield.fields.JSONField(blank=True, default=openedx.core.djangoapps.site_configuration.models.get_initial_page_elements, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sass_variables',
            field=jsonfield.fields.JSONField(blank=True, default=openedx.core.djangoapps.site_configuration.models.get_initial_sass_variables, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
    ]
