# Generated by Django 2.2.17 on 2021-06-16 05:40

from django.db import migrations, models
import django.db.models.deletion
import openedx.adg.common.course_meta.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.PositiveSmallIntegerField(default=openedx.adg.common.course_meta.helpers.next_course_short_id, unique=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_meta', to='course_overviews.CourseOverview')),
            ],
        ),
    ]
