# Generated by Django 2.2.17 on 2021-01-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_meta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemeta',
            name='is_prereq',
        ),
    ]
