# Generated by Django 2.2.15 on 2020-11-16 11:34

from django.db import migrations, models
import django.db.models.deletion
import openedx.adg.common.course_meta.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('course_meta', '0002_auto_20201020_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemeta',
            name='course_short_id',
            field=models.IntegerField(default=openedx.adg.common.course_meta.helpers.next_course_short_id, unique=True),
        ),
        migrations.AlterField(
            model_name='coursemeta',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_meta', to='course_overviews.CourseOverview'),
        ),
    ]
