# Generated by Django 2.2.20 on 2021-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_customprogramsconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProgramsConfig',
        ),
    ]
