# Generated by Django 2.2.24 on 2021-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_goals', '0003_historicalcoursegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegoal',
            name='number_of_days_with_visits_per_week_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursegoal',
            name='subscribed_to_goal_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcoursegoal',
            name='number_of_days_with_visits_per_week_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcoursegoal',
            name='subscribed_to_goal_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
