# Generated by Django 2.2.24 on 2021-08-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_goals', '0005_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User activities'},
        ),
        migrations.AddField(
            model_name='coursegoal',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, help_text='Used to validate unsubscribe requests without requiring a login', null=True, unique=True, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcoursegoal',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, db_index=True, help_text='Used to validate unsubscribe requests without requiring a login', null=True, editable=False),
        ),
    ]
