# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 08:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0016_simulatecoursepublishconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatecoursepublishconfig',
            name='arguments',
            field=models.TextField(blank=True, default=u'', help_text=u'Useful for manually running a Jenkins job. Specify like "--delay 10 --receivers A B C         --courses X Y Z".'),
        ),
    ]
