# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0017_auto_20191002_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
