# Generated by Django 1.11.27 on 2020-01-16 17:23


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0018_add_start_end_in_CourseOverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewtab',
            name='course_staff_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoverviewtab',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverviewtab',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverviewtab',
            name='course_overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_set', to='course_overviews.CourseOverview'),
        ),
    ]
