# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0019_copy_start_end_to_start_date_and_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverview',
            name='end',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='start',
        ),
        migrations.RemoveField(
            model_name='historicalcourseoverview',
            name='end',
        ),
        migrations.RemoveField(
            model_name='historicalcourseoverview',
            name='start',
        ),
    ]
