# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-13 19:31
from __future__ import unicode_literals

from django.db import migrations


def copy_column_values(apps, schema_editor):
    """
    Copy start,end into start_date & end_date respectively
    """
    CourseOverview = apps.get_model('course_overviews', 'CourseOverview')
    for course_overview in CourseOverview.objects.all():
        course_overview.start_date = course_overview.start
        course_overview.end_date = course_overview.end
        course_overview.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0020_courseoverviewtab_url_slug'),
    ]

    operations = [
        migrations.RunPython(
            copy_column_values,
            reverse_code=migrations.RunPython.noop,  # Allow reverse migrations, but make it a no-op.
        ),
    ]
