# Generated by Django 2.2.24 on 2021-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='allow_proctoring_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='enable_proctored_exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='proctoring_escalation_email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='proctoring_provider',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='allow_proctoring_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='enable_proctored_exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='proctoring_escalation_email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='proctoring_provider',
            field=models.TextField(null=True),
        ),
    ]
