# Generated by Django 2.2.24 on 2021-06-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='plan_release',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='plan_release',
            field=models.IntegerField(default=0),
        ),
    ]
