# Generated by Django 3.2.12 on 2022-02-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_auto_20210702_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='entrance_exam_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='entrance_exam_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='entrance_exam_minimum_score_pct',
            field=models.FloatField(default=0.65),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='entrance_exam_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='entrance_exam_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='entrance_exam_minimum_score_pct',
            field=models.FloatField(default=0.65),
        ),
    ]
