# Generated by Django 3.2.16 on 2022-10-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcourseoverview',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course overview', 'verbose_name_plural': 'historical course overviews'},
        ),
    ]
