# Generated by Django 3.2.13 on 2022-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_courseliveclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('room_key', models.CharField(max_length=60, null=True)),
                ('room_name', models.CharField(max_length=60, null=True)),
                ('topic_name', models.CharField(max_length=60, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('client_token', models.CharField(max_length=60, null=True)),
                ('meeting_link', models.CharField(max_length=60, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('is_recurrence_meeting', models.BooleanField(max_length=60)),
                ('meeting_notes', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseliveclasses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseliveclasses',
            name='created_by',
        ),
    ]
