# Generated by Django 3.2.19 on 2023-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_auto_20221102_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='force_on_flexible_peer_openassessments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='force_on_flexible_peer_openassessments',
            field=models.BooleanField(default=False),
        ),
    ]
