# Generated by Django 3.2.12 on 2022-07-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0028_liveclasses_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclasses',
            name='client_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='liveclasses',
            name='meeting_link',
            field=models.URLField(null=True),
        ),
    ]
