# Generated by Django 3.2.12 on 2022-05-16 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0047_auto_20220516_0738'),
        ('course_overviews', '0028_auto_20220511_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('room_key', models.CharField(max_length=60, null=True)),
                ('room_name', models.CharField(max_length=60, null=True)),
                ('topic_name', models.CharField(max_length=60, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('client_token', models.CharField(max_length=60, null=True)),
                ('meeting_link', models.CharField(max_length=60, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('is_recurrence_meeting', models.BooleanField(max_length=60)),
                ('meeting_notes', models.CharField(max_length=60, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseLiveClasses',
        ),
    ]
