# Generated by Django 3.2.13 on 2022-05-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0028_auto_20220517_1345'),
        ('student', '0046_auto_20220517_1345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLiveClasses',
        ),
        migrations.AddField(
            model_name='liveclasses',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
