# Generated by Django 4.2.20 on 2025-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='custom_name',
            field=models.CharField(blank=True, db_index=True, help_text='Optional custom name surfaced in Studio (Schedule & Details)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='custom_name',
            field=models.CharField(blank=True, db_index=True, help_text='Optional custom name surfaced in Studio (Schedule & Details)', max_length=255, null=True),
        ),
    ]
