# Generated by Django 4.2.20 on 2025-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0030_courseoverview_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='custom_course_number',
            field=models.CharField(blank=True, db_index=True, help_text='Optional custom course number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='custom_course_number',
            field=models.CharField(blank=True, db_index=True, help_text='Optional custom course number', max_length=255, null=True),
        ),
    ]
