CONVERSATIONALIST = ('conversationalist', 'Conversationalist')
TEAM_PLAYER = ('team', 'Team player')
BADGE_NOT_FOUND_ERROR = 'There exists no badge with id {badge_id}'
BADGE_TYPE_ERROR = 'Cannot assign badge {badge_id} of unknown type {badge_type}'
UNKNOWN_COURSE_ERROR = 'Cannot assign badge {badge_id} for team {community_id} in unknown course'
INVALID_COMMUNITY_ERROR = 'Cannot assign badge {badge_id} for invalid community {community_id}'
INVALID_TEAM_ERROR = 'Cannot assign badge {badge_id} for invalid team {community_id}'
FILTER_BADGES_ERROR = 'Unable to get badges for team {team_id}'
COURSE_ERROR = 'Course {course_id} not found'
BADGES_KEY = 'badges'
