# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badging', '0002_UserBadge_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.AddField(
            model_name='badge',
            name='congrats_message',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='badge',
            name='color_image',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='threshold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ('type', 'threshold')},
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('type', 'threshold')]),
        ),
    ]
