# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 15:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0006_remove_module_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='done',
            field=models.CharField(choices=[(u'na', u'NOT_APPLICABLE'), (u'f', u'FINISHED'), (u'i', u'INCOMPLETE')], default=u'na', max_length=8),
        ),
    ]
