# Generated by Django 1.11.13 on 2018-05-29 15:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0006_remove_module_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='done',
            field=models.CharField(choices=[('na', 'NOT_APPLICABLE'), ('f', 'FINISHED'), ('i', 'INCOMPLETE')], default='na', max_length=8),
        ),
    ]
