# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0007_remove_done_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodule',
            name='test_field_1',
            field=models.CharField(default=b'foobar', max_length=20),
        ),
    ]
