# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-28 19:32
from __future__ import unicode_literals

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0007_remove_done_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='module_state_key',
            field=opaque_keys.edx.django.models.UsageKeyField(db_column=b'module_id', db_index=True, max_length=255),
        ),
    ]
