# Generated by Django 1.11.22 on 2019-07-09 15:59


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0009_auto_20190703_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
