# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 04:54
#
# This migration does not produce any actual database changes; it only affects
# the python code. You can confirm this with:
#    ./manage.py lms sqlmigrate courseware 0012_adjust_fields


from django.conf import settings
from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseware', '0011_csm_id_bigint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='course_id',
            field=opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentmodule',
            name='module_type',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
