# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-01 18:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0012_adjust_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedynamicupgradedeadlineconfiguration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orgdynamicupgradedeadlineconfiguration',
            options={},
        ),
    ]
