# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 10:07


from django.db import migrations


def fix_nan_value_for_global_speed(apps, schema_editor):
    XModuleStudentPrefsField = apps.get_model('courseware', 'XModuleStudentPrefsField')
    XModuleStudentPrefsField.objects.filter(
        field_name='global_speed', value='NaN'
    ).update(
        value=1.0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0013_auto_20191001_1858'),
    ]

    operations = [
        migrations.RunPython(fix_nan_value_for_global_speed, reverse_code=migrations.RunPython.noop)
    ]
