# Generated by Django 2.2.18 on 2021-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0014_fix_nan_value_for_global_speed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentmodule',
            index=models.Index(fields=['module_state_key', 'grade', 'student'], name='courseware_stats'),
        ),
    ]
