# Generated by Django 3.2.12 on 2022-04-11 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseware', '0016_lastseencoursewaretimezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssistanceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('api_base_url', models.URLField(help_text='Financial Assistance Backend API Base URL.', verbose_name='Internal API Base URL')),
                ('service_username', models.CharField(default='financial_assistance_service_user', help_text='Username created for Financial Assistance Backend, e.g. financial_assistance_service_user.', max_length=100)),
                ('fa_backend_enabled_courses_percentage', models.IntegerField(default=0, help_text='Percentage of courses allowed to use edx-financial-assistance')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
