# Generated by Django 2.2.20 on 2021-05-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_student', '0013_add_expiration_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwaresecurephotoverification',
            name='expiry_date',
        ),
    ]
