# Generated by Django 4.2.15 on 2024-09-26 18:59

from django.db import migrations, models
import django.utils.timezone
import lms.djangoapps.verify_student.statuses
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verify_student', '0016_verificationattempt_status_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationattempt',
            name='created',
        ),
        migrations.RemoveField(
            model_name='verificationattempt',
            name='modified',
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='hide_status_from_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='verificationattempt',
            name='status',
            field=model_utils.fields.StatusField(choices=[(lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['CREATED'], lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['CREATED']), (lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['PENDING'], lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['PENDING']), (lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['APPROVED'], lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['APPROVED']), (lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['DENIED'], lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['DENIED'])], default=lms.djangoapps.verify_student.statuses.VerificationAttemptStatus['CREATED'], max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
