version: 2
updates:
    # Adding new check for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    reviewers:
      - "openedx/arbi-bom"
