# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:09


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_comment_common', '0005_coursediscussionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursediscussionsettings',
            name='discussions_id_map',
            field=jsonfield.fields.JSONField(blank=True, help_text=u'Key/value store mapping discussion IDs to discussion XBlock usage keys.', null=True),
        ),
    ]
