# Generated by Django 3.2.12 on 2022-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comment_common', '0008_role_user_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursediscussionsettings',
            name='reported_content_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
