# Generated by Django 4.2.20 on 2025-06-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comment_common', '0009_coursediscussionsettings_reported_content_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscussionsettings',
            name='division_scheme',
            field=models.CharField(choices=[('none', 'None'), ('cohort', 'Cohort'), ('enrollment_track', 'Enrollment Track'), ('user_group', 'User Group')], default='none', max_length=20),
        ),
    ]
