# Generated by Django 3.2.13 on 2022-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comment_common', '0009_coursediscussionsettings_reported_content_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscussionsettings',
            name='division_scheme',
            field=models.CharField(choices=[('none', 'None'), ('cohort', 'Cohort')], default='none', max_length=20),
        ),
    ]
