# Generated by Django 5.2.7 on 2025-10-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comment_common', '0009_coursediscussionsettings_reported_content_email_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumsConfig',
        ),
    ]
