# Generated by Django 5.2.7 on 2025-11-27 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comment_common', '0009_coursediscussionsettings_reported_content_email_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionMute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('course', 'Course-wide')], default='personal', help_text='Scope of mute: personal or course-wide', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for muting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mute is currently active')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(help_text='Course where the mute applies', max_length=255)),
                ('muted_by', models.ForeignKey(help_text='User who performed the mute action', on_delete=django.db.models.deletion.CASCADE, related_name='mutes_created', to=settings.AUTH_USER_MODEL)),
                ('muted_user', models.ForeignKey(help_text='User being muted', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_user_mute',
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(is_active=True, scope='personal'), fields=('muted_user', 'muted_by', 'course_id', 'scope'), name='unique_active_personal_mute'),
                    models.UniqueConstraint(condition=models.Q(is_active=True, scope='course'), fields=('muted_user', 'course_id'), name='unique_active_course_mute'),
                ],
                'indexes': [
                    models.Index(fields=['muted_user', 'course_id', 'is_active'], name='django_comment_common_discussionmute_muted_user_course_id_is_active_idx'),
                    models.Index(fields=['muted_by', 'course_id', 'scope'], name='django_comment_common_discussionmute_muted_by_course_id_scope_idx'),
                    models.Index(fields=['scope', 'course_id', 'is_active'], name='django_comment_common_discussionmute_scope_course_id_is_active_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DiscussionMuteException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exception is currently active')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(help_text='Course where the exception applies', max_length=255)),
                ('exception_user', models.ForeignKey(help_text='User who can see content from muted user', on_delete=django.db.models.deletion.CASCADE, related_name='mute_exceptions_received', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(help_text='User who granted the exception', on_delete=django.db.models.deletion.CASCADE, related_name='mute_exceptions_granted', to=settings.AUTH_USER_MODEL)),
                ('muted_user', models.ForeignKey(help_text='Muted user whose content can be seen', on_delete=django.db.models.deletion.CASCADE, related_name='mute_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_mute_exception',
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(is_active=True), fields=('muted_user', 'exception_user', 'course_id'), name='unique_active_mute_exception'),
                ],
                'indexes': [
                    models.Index(fields=['muted_user', 'course_id'], name='django_comment_common_discussionmuteexception_muted_user_course_id_idx'),
                    models.Index(fields=['exception_user', 'course_id'], name='django_comment_common_discussionmuteexception_exception_user_course_id_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DiscussionModerationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action_type', models.CharField(choices=[('mute', 'Mute'), ('unmute', 'Unmute'), ('mute_and_report', 'Mute and Report')], help_text='Type of moderation action performed', max_length=20)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('course', 'Course-wide')], default='personal', help_text='Scope of the moderation action', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for moderation')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(help_text='Course where the action was performed', max_length=255)),
                ('moderator', models.ForeignKey(help_text='User performing the moderation action', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_moderation_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='User on whom the action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_moderation_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_moderation_log',
                'indexes': [
                    models.Index(fields=['target_user', 'course_id', 'timestamp'], name='django_comment_common_discussionmoderationlog_target_user_course_id_timestamp_idx'),
                    models.Index(fields=['moderator', 'course_id', 'action_type'], name='django_comment_common_discussionmoderationlog_moderator_course_id_action_type_idx'),
                    models.Index(fields=['course_id', 'action_type', 'timestamp'], name='django_comment_common_discussionmoderationlog_course_id_action_type_timestamp_idx'),
                ],
            },
        ),
    ]