# Generated by Django 3.2.12 on 2022-03-18 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentstore', '0006_courseoutlineregenerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillCourseTabsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('start_index', models.IntegerField(default=0, help_text='Index of first course to start backfilling (in an alphabetically sorted list of courses)')),
                ('count', models.IntegerField(default=0, help_text='How many courses to backfill in this run (or zero for all courses)')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': 'Arguments for backfill_course_tabs',
                'verbose_name_plural': 'Arguments for backfill_course_tabs',
            },
        ),
    ]
