# Generated by Django 4.2.18 on 2025-02-19 23:32

from django.db import migrations
from opaque_keys.edx.django.models import UsageKeyField
from opaque_keys.edx.keys import UsageKey


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0009_learningcontextlinksstatus_publishableentitylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishableentitylink',
            name='downstream_parent_usage_key',
            field=UsageKeyField(
                db_index=True,
                # Adds a default invalid value to the field to prevent the migration from failing
                default=UsageKey.from_string('block-v1:edX+DemoX+Demo_Course+type@vertical+block@invalid'),
                max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='publishableentitylink',
            name='downstream_parent_usage_key',
            field=UsageKeyField(db_index=True, max_length=255),
        ),
    ]
