# Generated by Django 4.2.20 on 2025-04-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oel_components', '0003_remove_componentversioncontent_learner_downloadable'),
        ('contentstore', '0009_learningcontextlinksstatus_publishableentitylink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishableEntityLink',
            new_name='ComponentLink',
        ),
        migrations.AlterModelOptions(
            name='componentlink',
            options={'verbose_name': 'Component Link', 'verbose_name_plural': 'Component Links'},
        ),
        migrations.AlterField(
            model_name='componentlink',
            name='upstream_block',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='links',
                to='oel_components.component',
            ),
        ),
    ]
