# Generated by Django 4.2.20 on 2025-05-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentstore', '0010_container_link_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('description', models.TextField()),
                ('course_template', models.URLField(help_text='Link to the .gz (gzip) course template file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
