# Generated by Django 4.2.20 on 2025-05-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0010_container_link_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerlink',
            name='ready_to_sync',
            field=models.BooleanField(default=False, help_text='True if the downstream has an available sync from upstream. It changes to True when the upstream is published, and it changes to False when the sync is declined/accepted. The version number is not used to check this value because containers do not change version if a component is edited/deleted within them. '),
        ),
    ]
