# Generated by Django 4.2.23 on 2025-08-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0011_enable_markdown_editor_flag_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentlink',
            name='top_level_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentstore.containerlink'),
        ),
        migrations.AddField(
            model_name='containerlink',
            name='top_level_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentstore.containerlink'),
        ),
    ]
