# Generated by Django 4.2.24 on 2025-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0012_componentlink_top_level_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentlink',
            name='downstream_is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='containerlink',
            name='downstream_is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
