# Generated by Django 5.2.7 on 2025-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0013_componentlink_downstream_is_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentlink',
            name='downstream_is_modified',
        ),
        migrations.RemoveField(
            model_name='containerlink',
            name='downstream_is_modified',
        ),
        migrations.AddField(
            model_name='componentlink',
            name='downstream_customized',
            field=models.JSONField(
                default=list,
                help_text=(
                    'Names of the fields which have values set on the upstream block yet have been explicitly'
                    ' overridden on this downstream block'
                ),
            ),
        ),
        migrations.AddField(
            model_name='containerlink',
            name='downstream_customized',
            field=models.JSONField(
                default=list,
                help_text=(
                    'Names of the fields which have values set on the upstream block yet have been explicitly'
                    ' overridden on this downstream block'
                ),
            ),
        ),
    ]
