# Generated by Django 5.2.10 on 2026-01-25 21:52

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0014_remove_componentlink_downstream_is_modified_and_more'),
        ('oel_authoring', '0001_initial'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='componentlink',
                    name='upstream_block',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='oel_authoring.component'),
                ),
                migrations.AlterField(
                    model_name='containerlink',
                    name='upstream_container',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='oel_authoring.container'),
                ),
            ]
        ),
    ]
