extends:
  - '@commitlint/config-conventional'

rules:
  footer-leading-blank: [1, 'always']
  type-case: [2, 'always', 'lower-case']
  type-empty: [2, 'never']
  type-enum: [
      2,
      'always',
    [
        'build',
        'chore',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'temp',
    ]
  ]
