version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: "requirements/edx/doc.txt"
  - method: pip
    path: .
