SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."domain" LIKE 'testserver' ESCAPE '\' LIMIT 21
SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."id" = 1 LIMIT 21
SELECT "django_redirect"."id", "django_redirect"."site_id", "django_redirect"."old_path", "django_redirect"."new_path" FROM "django_redirect" WHERE "django_redirect"."site_id" = 1 ORDER BY "django_redirect"."old_path" ASC
SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2025-04-10 21:04:37.513578' AND "django_session"."session_key" = 'zqdj3zj8zpwkj138ejat1jlar0k78m41') LIMIT 21
SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 LIMIT 21
SELECT "student_userstanding"."id", "student_userstanding"."user_id", "student_userstanding"."account_status", "student_userstanding"."changed_by_id", "student_userstanding"."standing_last_changed_at" FROM "student_userstanding" WHERE "student_userstanding"."user_id" = 1 LIMIT 21
SELECT "site_configuration_siteconfiguration"."id", "site_configuration_siteconfiguration"."site_id", "site_configuration_siteconfiguration"."enabled", "site_configuration_siteconfiguration"."site_values" FROM "site_configuration_siteconfiguration" WHERE "site_configuration_siteconfiguration"."site_id" = 1 LIMIT 21
SELECT "dark_lang_darklangconfig"."id", "dark_lang_darklangconfig"."change_date", "dark_lang_darklangconfig"."changed_by_id", "dark_lang_darklangconfig"."enabled", "dark_lang_darklangconfig"."released_languages", "dark_lang_darklangconfig"."enable_beta_languages", "dark_lang_darklangconfig"."beta_languages" FROM "dark_lang_darklangconfig" ORDER BY "dark_lang_darklangconfig"."change_date" DESC LIMIT 1
SELECT "embargo_ipfilter"."id", "embargo_ipfilter"."change_date", "embargo_ipfilter"."changed_by_id", "embargo_ipfilter"."enabled", "embargo_ipfilter"."whitelist", "embargo_ipfilter"."blacklist" FROM "embargo_ipfilter" ORDER BY "embargo_ipfilter"."change_date" DESC LIMIT 1
SELECT "user_api_userpreference"."id", "user_api_userpreference"."user_id", "user_api_userpreference"."key", "user_api_userpreference"."value" FROM "user_api_userpreference" WHERE ("user_api_userpreference"."key" = 'preview-site-theme' AND "user_api_userpreference"."user_id" = 1) LIMIT 21
SELECT "theming_sitetheme"."id", "theming_sitetheme"."site_id", "theming_sitetheme"."theme_dir_name" FROM "theming_sitetheme" WHERE "theming_sitetheme"."site_id" = 1 ORDER BY "theming_sitetheme"."id" ASC LIMIT 1
SAVEPOINT "s139673514867584_x38"
SELECT 1 AS "a" FROM "course_overviews_courseoverview" WHERE "course_overviews_courseoverview"."id" = 'course-v1:org.15+course_15+Run_15' LIMIT 1
SELECT "split_modulestore_django_splitmodulestorecourseindex"."id", "split_modulestore_django_splitmodulestorecourseindex"."objectid", "split_modulestore_django_splitmodulestorecourseindex"."course_id", "split_modulestore_django_splitmodulestorecourseindex"."org", "split_modulestore_django_splitmodulestorecourseindex"."draft_version", "split_modulestore_django_splitmodulestorecourseindex"."published_version", "split_modulestore_django_splitmodulestorecourseindex"."library_version", "split_modulestore_django_splitmodulestorecourseindex"."wiki_slug", "split_modulestore_django_splitmodulestorecourseindex"."base_store", "split_modulestore_django_splitmodulestorecourseindex"."edited_by_id", "split_modulestore_django_splitmodulestorecourseindex"."edited_on", "split_modulestore_django_splitmodulestorecourseindex"."last_update" FROM "split_modulestore_django_splitmodulestorecourseindex" WHERE "split_modulestore_django_splitmodulestorecourseindex"."course_id" = 'course-v1:org.15+course_15+Run_15' LIMIT 21
SELECT "split_modulestore_django_splitmodulestorecourseindex"."id", "split_modulestore_django_splitmodulestorecourseindex"."objectid", "split_modulestore_django_splitmodulestorecourseindex"."course_id", "split_modulestore_django_splitmodulestorecourseindex"."org", "split_modulestore_django_splitmodulestorecourseindex"."draft_version", "split_modulestore_django_splitmodulestorecourseindex"."published_version", "split_modulestore_django_splitmodulestorecourseindex"."library_version", "split_modulestore_django_splitmodulestorecourseindex"."wiki_slug", "split_modulestore_django_splitmodulestorecourseindex"."base_store", "split_modulestore_django_splitmodulestorecourseindex"."edited_by_id", "split_modulestore_django_splitmodulestorecourseindex"."edited_on", "split_modulestore_django_splitmodulestorecourseindex"."last_update" FROM "split_modulestore_django_splitmodulestorecourseindex" WHERE "split_modulestore_django_splitmodulestorecourseindex"."course_id" = 'course-v1:org.15+course_15+Run_15' LIMIT 21
SELECT "site_configuration_siteconfiguration"."id", "site_configuration_siteconfiguration"."site_id", "site_configuration_siteconfiguration"."enabled", "site_configuration_siteconfiguration"."site_values" FROM "site_configuration_siteconfiguration" WHERE ("site_configuration_siteconfiguration"."enabled" AND "site_configuration_siteconfiguration"."site_values" LIKE '%org.15%' ESCAPE '\')
SELECT "course_modes_coursemode"."id", "course_modes_coursemode"."course_id", "course_modes_coursemode"."mode_slug", "course_modes_coursemode"."mode_display_name", "course_modes_coursemode"."min_price", "course_modes_coursemode"."currency", "course_modes_coursemode"."expiration_datetime", "course_modes_coursemode"."expiration_datetime_is_explicit", "course_modes_coursemode"."expiration_date", "course_modes_coursemode"."suggested_prices", "course_modes_coursemode"."description", "course_modes_coursemode"."sku", "course_modes_coursemode"."android_sku", "course_modes_coursemode"."ios_sku", "course_modes_coursemode"."bulk_sku" FROM "course_modes_coursemode" WHERE "course_modes_coursemode"."course_id" = 'course-v1:org.15+course_15+Run_15'
SELECT "site_configuration_siteconfiguration"."id", "site_configuration_siteconfiguration"."site_id", "site_configuration_siteconfiguration"."enabled", "site_configuration_siteconfiguration"."site_values", "django_site"."id", "django_site"."domain", "django_site"."name" FROM "site_configuration_siteconfiguration" INNER JOIN "django_site" ON ("site_configuration_siteconfiguration"."site_id" = "django_site"."id") WHERE ("site_configuration_siteconfiguration"."enabled" AND "site_configuration_siteconfiguration"."site_values" LIKE '%org.15%' ESCAPE '\')
SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."id" = 1 LIMIT 21
SELECT "content_type_gating_contenttypegatingconfig"."id", "content_type_gating_contenttypegatingconfig"."change_date", "content_type_gating_contenttypegatingconfig"."changed_by_id", "content_type_gating_contenttypegatingconfig"."enabled", "content_type_gating_contenttypegatingconfig"."site_id", "content_type_gating_contenttypegatingconfig"."org", "content_type_gating_contenttypegatingconfig"."org_course", "content_type_gating_contenttypegatingconfig"."course_id", "content_type_gating_contenttypegatingconfig"."enabled_as_of", "content_type_gating_contenttypegatingconfig"."studio_override_enabled", 1 AS "is_active" FROM "content_type_gating_contenttypegatingconfig" WHERE ("content_type_gating_contenttypegatingconfig"."id" IN (SELECT MAX(U0."id") AS "max" FROM "content_type_gating_contenttypegatingconfig" U0 GROUP BY U0."site_id", U0."org", U0."org_course", U0."course_id") AND (("content_type_gating_contenttypegatingconfig"."course_id" IS NULL AND "content_type_gating_contenttypegatingconfig"."org" IS NULL AND "content_type_gating_contenttypegatingconfig"."org_course" IS NULL AND "content_type_gating_contenttypegatingconfig"."site_id" IS NULL) OR ("content_type_gating_contenttypegatingconfig"."course_id" IS NULL AND "content_type_gating_contenttypegatingconfig"."org" IS NULL AND "content_type_gating_contenttypegatingconfig"."org_course" IS NULL AND "content_type_gating_contenttypegatingconfig"."site_id" = 1) OR ("content_type_gating_contenttypegatingconfig"."course_id" IS NULL AND "content_type_gating_contenttypegatingconfig"."org" = 'org.15' AND "content_type_gating_contenttypegatingconfig"."org_course" IS NULL AND "content_type_gating_contenttypegatingconfig"."site_id" IS NULL) OR ("content_type_gating_contenttypegatingconfig"."course_id" IS NULL AND "content_type_gating_contenttypegatingconfig"."org" IS NULL AND "content_type_gating_contenttypegatingconfig"."org_course" = 'org.15+course_15' AND "content_type_gating_contenttypegatingconfig"."site_id" IS NULL) OR ("content_type_gating_contenttypegatingconfig"."course_id" = 'course-v1:org.15+course_15+Run_15' AND "content_type_gating_contenttypegatingconfig"."org" IS NULL AND "content_type_gating_contenttypegatingconfig"."org_course" IS NULL AND "content_type_gating_contenttypegatingconfig"."site_id" IS NULL)))
SELECT "course_modes_coursemode"."id", "course_modes_coursemode"."course_id", "course_modes_coursemode"."mode_slug", "course_modes_coursemode"."mode_display_name", "course_modes_coursemode"."min_price", "course_modes_coursemode"."currency", "course_modes_coursemode"."expiration_datetime", "course_modes_coursemode"."expiration_datetime_is_explicit", "course_modes_coursemode"."expiration_date", "course_modes_coursemode"."suggested_prices", "course_modes_coursemode"."description", "course_modes_coursemode"."sku", "course_modes_coursemode"."android_sku", "course_modes_coursemode"."ios_sku", "course_modes_coursemode"."bulk_sku" FROM "course_modes_coursemode" WHERE ("course_modes_coursemode"."course_id" = 'course-v1:org.15+course_15+Run_15' AND NOT ("course_modes_coursemode"."mode_slug" IN ('credit')))
SELECT "oel_tagging_objecttag"."object_id", COUNT("oel_tagging_objecttag"."id") AS "num_tags", GROUP_CONCAT("oel_tagging_objecttag"."tag_id") AS "tag_ids_str_1", GROUP_CONCAT("oel_tagging_tag"."parent_id") AS "tag_ids_str_2", GROUP_CONCAT(T4."parent_id") AS "tag_ids_str_3", GROUP_CONCAT(T5."parent_id") AS "tag_ids_str_4" FROM "oel_tagging_objecttag" INNER JOIN "oel_tagging_taxonomy" ON ("oel_tagging_objecttag"."taxonomy_id" = "oel_tagging_taxonomy"."id") LEFT OUTER JOIN "oel_tagging_tag" ON ("oel_tagging_objecttag"."tag_id" = "oel_tagging_tag"."id") LEFT OUTER JOIN "oel_tagging_tag" T4 ON ("oel_tagging_tag"."parent_id" = T4."id") LEFT OUTER JOIN "oel_tagging_tag" T5 ON (T4."parent_id" = T5."id") WHERE ("oel_tagging_objecttag"."object_id" IN ('course-v1:org.15+course_15+Run_15') AND NOT ("oel_tagging_objecttag"."taxonomy_id" IS NULL) AND NOT (NOT "oel_tagging_taxonomy"."enabled") AND NOT ("oel_tagging_objecttag"."tag_id" IS NULL AND NOT "oel_tagging_taxonomy"."allow_free_text")) GROUP BY "oel_tagging_objecttag"."object_id" ORDER BY "oel_tagging_objecttag"."object_id" ASC
SELECT "oel_tagging_objecttag"."object_id", COUNT("oel_tagging_objecttag"."id") AS "num_tags", GROUP_CONCAT("oel_tagging_objecttag"."tag_id") AS "tag_ids_str_1", GROUP_CONCAT("oel_tagging_tag"."parent_id") AS "tag_ids_str_2", GROUP_CONCAT(T4."parent_id") AS "tag_ids_str_3", GROUP_CONCAT(T5."parent_id") AS "tag_ids_str_4" FROM "oel_tagging_objecttag" INNER JOIN "oel_tagging_taxonomy" ON ("oel_tagging_objecttag"."taxonomy_id" = "oel_tagging_taxonomy"."id") LEFT OUTER JOIN "oel_tagging_tag" ON ("oel_tagging_objecttag"."tag_id" = "oel_tagging_tag"."id") LEFT OUTER JOIN "oel_tagging_tag" T4 ON ("oel_tagging_tag"."parent_id" = T4."id") LEFT OUTER JOIN "oel_tagging_tag" T5 ON (T4."parent_id" = T5."id") WHERE ("oel_tagging_objecttag"."object_id" LIKE 'block-v1:org.15+course\_15+Run\_15+type@%' ESCAPE '\' AND NOT ("oel_tagging_objecttag"."taxonomy_id" IS NULL) AND NOT (NOT "oel_tagging_taxonomy"."enabled") AND NOT ("oel_tagging_objecttag"."tag_id" IS NULL AND NOT "oel_tagging_taxonomy"."allow_free_text")) GROUP BY "oel_tagging_objecttag"."object_id" ORDER BY "oel_tagging_objecttag"."object_id" ASC
SELECT "discussions_discussionsconfiguration"."created", "discussions_discussionsconfiguration"."modified", "discussions_discussionsconfiguration"."context_key", "discussions_discussionsconfiguration"."enabled", "discussions_discussionsconfiguration"."posting_restrictions", "discussions_discussionsconfiguration"."lti_configuration_id", "discussions_discussionsconfiguration"."enable_in_context", "discussions_discussionsconfiguration"."enable_graded_units", "discussions_discussionsconfiguration"."unit_level_visibility", "discussions_discussionsconfiguration"."plugin_configuration", "discussions_discussionsconfiguration"."provider_type" FROM "discussions_discussionsconfiguration" WHERE "discussions_discussionsconfiguration"."context_key" = 'course-v1:org.15+course_15+Run_15' LIMIT 21
SELECT "course_action_state_coursererunstate"."id", "course_action_state_coursererunstate"."created_time", "course_action_state_coursererunstate"."updated_time", "course_action_state_coursererunstate"."created_user_id", "course_action_state_coursererunstate"."updated_user_id", "course_action_state_coursererunstate"."course_key", "course_action_state_coursererunstate"."action", "course_action_state_coursererunstate"."state", "course_action_state_coursererunstate"."should_display", "course_action_state_coursererunstate"."message", "course_action_state_coursererunstate"."source_course_key", "course_action_state_coursererunstate"."display_name" FROM "course_action_state_coursererunstate" WHERE ("course_action_state_coursererunstate"."action" = 'rerun' AND "course_action_state_coursererunstate"."course_key" = 'course-v1:org.15+course_15+Run_15' AND "course_action_state_coursererunstate"."should_display")
SELECT "xblock_django_xblockconfiguration"."id", "xblock_django_xblockconfiguration"."change_date", "xblock_django_xblockconfiguration"."changed_by_id", "xblock_django_xblockconfiguration"."enabled", "xblock_django_xblockconfiguration"."name", "xblock_django_xblockconfiguration"."deprecated", 1 AS "is_active" FROM "xblock_django_xblockconfiguration" WHERE ("xblock_django_xblockconfiguration"."id" IN (SELECT MAX(U0."id") AS "max" FROM "xblock_django_xblockconfiguration" U0 GROUP BY U0."name") AND "xblock_django_xblockconfiguration"."deprecated") ORDER BY "xblock_django_xblockconfiguration"."change_date" DESC
SELECT "site_configuration_siteconfiguration"."id", "site_configuration_siteconfiguration"."site_id", "site_configuration_siteconfiguration"."enabled", "site_configuration_siteconfiguration"."site_values" FROM "site_configuration_siteconfiguration" WHERE ("site_configuration_siteconfiguration"."enabled" AND "site_configuration_siteconfiguration"."site_values" LIKE '%course\_org\_filter%' ESCAPE '\')
SELECT "xblock_django_xblockstudioconfigurationflag"."id", "xblock_django_xblockstudioconfigurationflag"."change_date", "xblock_django_xblockstudioconfigurationflag"."changed_by_id", "xblock_django_xblockstudioconfigurationflag"."enabled" FROM "xblock_django_xblockstudioconfigurationflag" ORDER BY "xblock_django_xblockstudioconfigurationflag"."change_date" DESC LIMIT 1
SELECT "content_staging_userclipboard"."user_id", "content_staging_userclipboard"."content_id", "content_staging_userclipboard"."source_usage_key" FROM "content_staging_userclipboard" WHERE "content_staging_userclipboard"."user_id" = 1 LIMIT 21
SELECT "site_configuration_siteconfiguration"."id", "site_configuration_siteconfiguration"."site_id", "site_configuration_siteconfiguration"."enabled", "site_configuration_siteconfiguration"."site_values" FROM "site_configuration_siteconfiguration" WHERE ("site_configuration_siteconfiguration"."enabled" AND "site_configuration_siteconfiguration"."site_values" LIKE '%course\_org\_filter%' ESCAPE '\')
SELECT "site_configuration_siteconfiguration"."id", "site_configuration_siteconfiguration"."site_id", "site_configuration_siteconfiguration"."enabled", "site_configuration_siteconfiguration"."site_values" FROM "site_configuration_siteconfiguration" WHERE ("site_configuration_siteconfiguration"."enabled" AND "site_configuration_siteconfiguration"."site_values" LIKE '%course\_org\_filter%' ESCAPE '\')
RELEASE SAVEPOINT "s139673514867584_x38"
SELECT "user_api_userpreference"."id", "user_api_userpreference"."user_id", "user_api_userpreference"."key", "user_api_userpreference"."value" FROM "user_api_userpreference" WHERE ("user_api_userpreference"."key" = 'pref-lang' AND "user_api_userpreference"."user_id" = 1) LIMIT 21
