# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-07 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartreferral',
            name='is_referral_step_complete',
            field=models.BooleanField(default=False, verbose_name='Is referral steps completed'),
        ),
        migrations.RemoveField(
            model_name='smartreferral',
            name='is_contact_reg_completed',
        ),
        migrations.AlterUniqueTogether(
            name='smartreferral',
            unique_together=set([('contact_email', 'user')]),
        ),
    ]
