# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_survey', '0025_auto_20170924_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='community_learner_for_similar_org',
            new_name='community_of_interest_learner_for_similar_org',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='community_learner_from_my_region',
            new_name='community_of_interest_learner_from_my_region',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='community_learner_interested_in_similar_org_capacity',
            new_name='community_of_interest_learner_interested_in_similar_org_capacity',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='english_prof',
            new_name='english_proficiency',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='is_country_or_city_different',
            new_name='is_employment_location_different',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='administration',
            new_name='org_capacity_administration',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='external_relation',
            new_name='org_capacity_external_relation',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='finance',
            new_name='org_capacity_finance',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='leadership',
            new_name='org_capacity_leadership',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='logistics',
            new_name='org_capacity_logistics',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='program',
            new_name='org_capacity_program',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='city',
            new_name='org_city',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='country',
            new_name='org_country',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='focus_area',
            new_name='org_focus_area',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='founding_year',
            new_name='org_founding_year',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='level_of_op',
            new_name='org_level_of_operation',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='sector',
            new_name='org_sector',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='start_month_year',
            new_name='org_start_month_year',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='total_annual_clients_or_beneficiary',
            new_name='org_total_annual_clients_or_beneficiary',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='total_annual_revenue_for_last_fiscal',
            new_name='org_total_annual_revenue_for_last_fiscal_year',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='total_employees',
            new_name='org_total_employees',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='total_volunteers',
            new_name='org_total_volunteers',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='url',
            new_name='org_url',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='build_relation_with_other',
            new_name='personal_goal_build_relation_with_other',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='contribute_to_organization',
            new_name='personal_goal_contribute_to_organization',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='develop_leadership',
            new_name='personal_goal_develop_leadership',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='gain_new_skill',
            new_name='personal_goal_gain_new_skill',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='improve_job_prospect',
            new_name='personal_goal_improve_job_prospect',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='reason_of_interest',
            new_name='reason_of_selected_interest',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='interestssurvey',
            old_name='reason_of_interest',
            new_name='reason_of_selected_interest',
        ),
        migrations.RenameField(
            model_name='organizationsurvey',
            old_name='level_of_op',
            new_name='level_of_operation',
        ),
        migrations.RenameField(
            model_name='organizationsurvey',
            old_name='total_annual_revenue_for_last_fiscal',
            new_name='total_annual_revenue_for_last_fiscal_year',
        ),
        migrations.RenameField(
            model_name='userinfosurvey',
            old_name='english_prof',
            new_name='english_proficiency',
        ),
        migrations.RenameField(
            model_name='userinfosurvey',
            old_name='is_country_or_city_different',
            new_name='is_employment_location_different',
        ),
    ]
