"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('third_party_auth.management.commands.remove_social_auth_users', 'common.djangoapps.third_party_auth.management.commands.remove_social_auth_users')

from common.djangoapps.third_party_auth.management.commands.remove_social_auth_users import *
