# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 20:54


import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_api', '0003_userretirementrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRetirementPartnerReportingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('original_username', models.CharField(db_index=True, max_length=150)),
                ('original_email', models.EmailField(db_index=True, max_length=254)),
                ('original_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_being_processed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Retirement Reporting Status',
                'verbose_name_plural': 'User Retirement Reporting Statuses',
            },
        ),
    ]
