"""
Django models for AI Learning integration.
"""

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel
from opaque_keys.edx.django.models import CourseKeyField, UsageKeyField


class AIGeneratedCourse(TimeStampedModel):
    """
    Tracks courses that were generated by the AI Engine.
    """
    course_key = CourseKeyField(
        max_length=255,
        db_index=True,
        unique=True,
        help_text=_("Course identifier")
    )
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='ai_generated_courses',
        help_text=_("User who requested the course generation")
    )
    generation_prompt = models.TextField(
        help_text=_("Original prompt used to generate the course")
    )
    curriculum_data = models.JSONField(
        default=dict,
        help_text=_("Structured curriculum data from AI Engine")
    )
    generation_status = models.CharField(
        max_length=20,
        choices=[
            ('pending', _('Pending')),
            ('generating', _('Generating')),
            ('completed', _('Completed')),
            ('failed', _('Failed')),
        ],
        default='pending',
        db_index=True,
        help_text=_("Current status of course generation")
    )
    ai_engine_course_id = models.CharField(
        max_length=255,
        db_index=True,
        help_text=_("Course ID in the AI Engine system")
    )
    metadata = models.JSONField(
        default=dict,
        help_text=_("Additional metadata about the course generation")
    )

    class Meta:
        app_label = 'ai_learning'
        verbose_name = _('AI Generated Course')
        verbose_name_plural = _('AI Generated Courses')
        ordering = ['-created']

    def __str__(self):
        return f"AI Course: {self.course_key}"


class StudentLearningProfile(TimeStampedModel):
    """
    Stores student learning profile data synced with AI Engine.
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_learning_profile',
        help_text=_("Student user account")
    )
    ai_engine_profile_id = models.CharField(
        max_length=255,
        db_index=True,
        unique=True,
        help_text=_("Profile ID in the AI Engine system")
    )
    learning_style = models.CharField(
        max_length=50,
        blank=True,
        help_text=_("Identified learning style (visual, auditory, kinesthetic, etc.)")
    )
    mastered_concepts = models.JSONField(
        default=list,
        help_text=_("List of concepts the student has mastered")
    )
    struggling_concepts = models.JSONField(
        default=list,
        help_text=_("List of concepts the student is struggling with")
    )
    preferences = models.JSONField(
        default=dict,
        help_text=_("Student learning preferences")
    )
    last_sync = models.DateTimeField(
        auto_now=True,
        help_text=_("Last time profile was synced with AI Engine")
    )

    class Meta:
        app_label = 'ai_learning'
        verbose_name = _('Student Learning Profile')
        verbose_name_plural = _('Student Learning Profiles')

    def __str__(self):
        return f"Learning Profile: {self.user.username}"


class AdaptiveInteraction(TimeStampedModel):
    """
    Logs adaptive interactions between students and AI-powered components.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='adaptive_interactions',
        help_text=_("Student who performed the interaction")
    )
    course_key = CourseKeyField(
        max_length=255,
        db_index=True,
        help_text=_("Course where interaction occurred")
    )
    usage_key = UsageKeyField(
        max_length=255,
        db_index=True,
        help_text=_("Specific XBlock where interaction occurred")
    )
    interaction_type = models.CharField(
        max_length=50,
        choices=[
            ('assessment', _('Assessment')),
            ('tutor_chat', _('Tutor Chat')),
            ('content_view', _('Content View')),
            ('adaptation', _('Adaptation')),
        ],
        db_index=True,
        help_text=_("Type of adaptive interaction")
    )
    interaction_data = models.JSONField(
        default=dict,
        help_text=_("Data about the interaction")
    )
    ai_response = models.JSONField(
        default=dict,
        help_text=_("Response from AI Engine")
    )
    response_time_ms = models.IntegerField(
        null=True,
        blank=True,
        help_text=_("Time taken for AI Engine to respond (milliseconds)")
    )

    class Meta:
        app_label = 'ai_learning'
        verbose_name = _('Adaptive Interaction')
        verbose_name_plural = _('Adaptive Interactions')
        ordering = ['-created']
        indexes = [
            models.Index(fields=['user', 'course_key', '-created']),
            models.Index(fields=['interaction_type', '-created']),
        ]

    def __str__(self):
        return f"{self.interaction_type} by {self.user.username} at {self.created}"


class AIEngineWebhook(TimeStampedModel):
    """
    Logs webhook calls from AI Engine for debugging and auditing.
    """
    webhook_type = models.CharField(
        max_length=50,
        db_index=True,
        help_text=_("Type of webhook event")
    )
    payload = models.JSONField(
        help_text=_("Webhook payload data")
    )
    status = models.CharField(
        max_length=20,
        choices=[
            ('received', _('Received')),
            ('processing', _('Processing')),
            ('completed', _('Completed')),
            ('failed', _('Failed')),
        ],
        default='received',
        db_index=True,
        help_text=_("Processing status")
    )
    error_message = models.TextField(
        blank=True,
        help_text=_("Error message if processing failed")
    )

    class Meta:
        app_label = 'ai_learning'
        verbose_name = _('AI Engine Webhook')
        verbose_name_plural = _('AI Engine Webhooks')
        ordering = ['-created']

    def __str__(self):
        return f"Webhook: {self.webhook_type} - {self.status}"
