"""
Integration tests for IdP-initiated SSO with minimal mocking.

These tests use real database models and Django components to test the flow
as close to production as possible.
"""

from unittest.mock import patch
from urllib.parse import parse_qs, urlparse

from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings, modify_settings, RequestFactory
from django.urls import reverse

from common.djangoapps.third_party_auth.models import OAuth2ProviderConfig, cache as config_cache
from common.djangoapps.third_party_auth.idp_initiated_sso import IdpInitiatedSsoView
from common.djangoapps.third_party_auth.tests.testutil import ThirdPartyAuthTestMixin

User = get_user_model()


@modify_settings(
    INSTALLED_APPS={'remove': ['debug_toolbar']},
    MIDDLEWARE={'remove': ['debug_toolbar.middleware.DebugToolbarMiddleware']},
)
@override_settings(
    DEBUG=False,
    FEATURES={
        'ENABLE_THIRD_PARTY_AUTH': True,
    }
)
class IdpInitiatedSsoIntegrationTest(ThirdPartyAuthTestMixin, TestCase):
    """
    Integration tests for IdP-initiated SSO that use real database models
    and minimize mocking to test the actual flow.
    """

    def setUp(self):
        super().setUp()
        self.hostname = 'example.com'
        self.factory = RequestFactory()
        self.endpoint_url = reverse('idp_initiated_sso_login')
        
        # Create a real OAuth2 provider configuration in the database
        self.oauth_provider = OAuth2ProviderConfig.objects.create(
            name='Auth0 Test Provider',
            enabled=True,
            backend_name='google-oauth2',
            # Client credentials
            key='test-client-id',
            secret='test-client-secret',
        )
        
        # Clear cache to ensure registry picks up the new provider
        config_cache.clear()

    def test_idp_initiated_flow_with_real_provider(self):
        """
        Test the full IdP-initiated SSO flow using a real OAuth2 provider
        from the database, without mocking the provider registry.
        """
        # Make request with connection parameter
        connection_name = 'enterprise-saml-connection'
        request = self.factory.get(
            self.endpoint_url,
            {'connection': connection_name, 'next': '/dashboard'},
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        response = view(request)
        
        # Should redirect (302)
        self.assertEqual(response.status_code, 302)
        
        # Parse the redirect URL
        redirect_url = response.url
        parsed = urlparse(redirect_url)
        query_params = parse_qs(parsed.query)
        
        # Verify the connection parameter was added
        self.assertIn('connection', query_params)
        self.assertEqual(query_params['connection'][0], connection_name)
        
        # Verify the redirect points to the authorization URL
        # (The actual URL will be generated by the pipeline)
        self.assertTrue(redirect_url.startswith('/auth/login'))

    def test_multiple_providers_first_oauth_selected(self):
        """
        Test that when multiple providers exist, the first OAuth provider
        is correctly selected.
        """
        # Create a SAML provider (should be ignored)
        OAuth2ProviderConfig.objects.create(
            name='SAML Provider',
            enabled=True,
            backend_name='tpa-saml',
        )
        
        # Create another OAuth provider
        OAuth2ProviderConfig.objects.create(
            name='Auth0 Provider 2',
            enabled=True,
            backend_name='facebook',
            key='client-id-2',
            secret='client-secret-2',
        )
        
        # Clear cache
        config_cache.clear()
        
        # Make request
        request = self.factory.get(
            self.endpoint_url,
            {'connection': 'test-connection'},
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        response = view(request)
        
        # Should successfully redirect using one of the OAuth providers
        self.assertEqual(response.status_code, 302)

    def test_disabled_provider_not_used(self):
        """
        Test that disabled OAuth providers are not used.
        """
        # Disable the OAuth provider
        self.oauth_provider.enabled = False
        self.oauth_provider.save()
        config_cache.clear()
        
        # Make request
        request = self.factory.get(
            self.endpoint_url,
            {'connection': 'test-connection'},
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        
        # Should raise Http404 (no suitable provider found)
        from django.http import Http404
        with self.assertRaises(Http404):
            view(request)

    def test_connection_parameter_preserved_in_pipeline(self):
        """
        Test that the connection parameter is correctly preserved
        through the authentication pipeline.
        """
        connection_name = 'enterprise-okta-saml'
        next_url = '/courses/course-v1:edX+DemoX+Demo_Course/course/'
        
        request = self.factory.get(
            self.endpoint_url,
            {
                'connection': connection_name,
                'next': next_url,
            },
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        response = view(request)
        
        self.assertEqual(response.status_code, 302)
        
        # Parse redirect URL
        redirect_url = response.url
        parsed = urlparse(redirect_url)
        query_params = parse_qs(parsed.query)
        
        # Verify both connection and next are in the URL
        self.assertIn('connection', query_params)
        self.assertEqual(query_params['connection'][0], connection_name)
        
        # The next URL should be encoded in the pipeline
        # (exact parameter name may vary based on pipeline implementation)
        self.assertTrue(
            any('next' in key or 'redirect' in key for key in query_params.keys())
        )

    def test_special_characters_in_connection_name(self):
        """
        Test that special characters in connection names are properly encoded.
        """
        # Connection name with special characters
        connection_name = 'enterprise-saml+connection/test'
        
        request = self.factory.get(
            self.endpoint_url,
            {'connection': connection_name},
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        response = view(request)
        
        self.assertEqual(response.status_code, 302)
        
        # Verify the connection is properly URL-encoded in the redirect
        redirect_url = response.url
        self.assertIn('connection', redirect_url)

    def test_real_database_transaction(self):
        """
        Test that the view works correctly within database transactions.
        """
        # This tests that the view properly uses the database
        # and doesn't have transaction-related issues
        
        request = self.factory.get(
            self.endpoint_url,
            {'connection': 'test'},
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        
        with self.assertNumQueries(1):  # Should only query for provider configs
            response = view(request)
        
        self.assertEqual(response.status_code, 302)


@modify_settings(
    INSTALLED_APPS={'remove': ['debug_toolbar']},
    MIDDLEWARE={'remove': ['debug_toolbar.middleware.DebugToolbarMiddleware']},
)
@override_settings(
    DEBUG=False,
    FEATURES={
        'ENABLE_THIRD_PARTY_AUTH': True,
    }
)
class IdpInitiatedSsoAuthFlowTest(ThirdPartyAuthTestMixin, TestCase):
    """
    Tests that verify the IdP-initiated SSO integrates correctly with
    the authentication pipeline (with minimal external mocking).
    """

    def setUp(self):
        super().setUp()
        self.hostname = 'example.com'
        self.factory = RequestFactory()
        
        # Create OAuth2 provider
        self.oauth_provider = OAuth2ProviderConfig.objects.create(
            name='Auth0',
            enabled=True,
            backend_name='google-oauth2',
            key='client-id',
            secret='client-secret',
        )
        config_cache.clear()

    @patch('social_core.backends.oauth.BaseOAuth2.auth_url')
    def test_auth_backend_receives_connection_parameter(self, mock_auth_url):
        """
        Test that when the pipeline redirects to the OAuth backend,
        the connection parameter is included (mocking only the external Auth0 call).
        """
        # Mock only the external Auth0 authorization URL generation
        mock_auth_url.return_value = 'https://test.auth0.com/authorize?client_id=test&...'
        
        # Make request
        request = self.factory.get(
            reverse('idp_initiated_sso_login'),
            {'connection': 'enterprise-okta'},
            SERVER_NAME=self.hostname
        )
        
        view = IdpInitiatedSsoView.as_view()
        response = view(request)
        
        # Follow the redirect chain (if any)
        if response.status_code == 302:
            # Check that connection parameter is in the final URL
            final_url = response.url
            self.assertIn('connection=enterprise-okta', final_url)

    def test_session_state_preservation(self):
        """
        Test that the session state is correctly maintained through
        the IdP-initiated flow.
        """
        from importlib import import_module
        from django.conf import settings
        
        # Create a session with some data
        engine = import_module(settings.SESSION_ENGINE)
        session = engine.SessionStore()
        session['test_key'] = 'test_value'
        session.save()
        
        # Make IdP-initiated request
        request = self.factory.get(
            reverse('idp_initiated_sso_login'),
            {'connection': 'test', 'next': '/dashboard'},
            SERVER_NAME=self.hostname
        )
        request.session = session
        
        view = IdpInitiatedSsoView.as_view()
        response = view(request)
        
        # Session should still be valid (RequestFactory doesn't persist it like Client,
        # but we check if the view modified/accessed it correctly or if it's still attached)
        # IdpInitiatedSsoView doesn't modify session, but pipeline might.
        # Here we just verify the session object on the request is preserved/accessible.
        self.assertIn('test_key', request.session)
        self.assertEqual(request.session['test_key'], 'test_value')
