# Generated by Django 2.2.17 on 2021-06-16 05:48

import django.core.validators
from django.db import migrations, models
import openedx.adg.lms.our_team.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add a name of max 70 characters', max_length=70, verbose_name='Name')),
                ('designation', models.CharField(help_text='Add a designation of max 70 characters', max_length=70, verbose_name='Designation')),
                ('image', models.ImageField(help_text='Add a square image i.e image with 1:1 aspect ratio for optimal results', upload_to='team-members/images/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'svg')), openedx.adg.lms.our_team.helpers.validate_profile_image_size], verbose_name='Image')),
                ('description', models.TextField(help_text='Add a description of max 200 characters', max_length=200, verbose_name='Description')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('member_type', models.CharField(choices=[('team_member', 'Team Member'), ('board_of_trustee', 'Board Of Trustee')], default='team_member', max_length=20, verbose_name='Member Type')),
            ],
        ),
    ]
