# Generated by Django 2.2.17 on 2021-03-30 12:10

import django.core.validators
from django.db import migrations, models
import openedx.adg.lms.our_team.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('image', models.ImageField(upload_to='team-members/images/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'svg')), openedx.adg.lms.our_team.helpers.validate_profile_image_size], verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
            ],
        ),
    ]
