# Generated by Django 2.2.17 on 2021-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteammember',
            name='member_type',
            field=models.CharField(choices=[('team_member', 'Team Member'), ('board_of_trustee', 'Board Of Trustee')], default='team_member', max_length=20, verbose_name='Member Type'),
        ),
    ]
