# Generated by Django 2.2.15 on 2020-08-27 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_clean_duplicate_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdemographics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
