# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-30 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0028_education_experience_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtype',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationType',
        ),
    ]
