# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-20 09:56
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields
import openedx.custom.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0029_auto_20200130_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserextendedprofile',
            name='function_areas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'strategy_planning', b'Strategy and planning'), (b'leadership_governance', b'Leadership and governance'), (b'program_design', b'Program design and development'), (b'measurement_eval', b'Measurement evaluation and learning'), (b'stakeholder_engagement', b'External relations and partnerships'), (b'human_resource', b'Human resource management'), (b'financial_management', b'Financial management'), (b'fundraising', b'Fundraising and resource mobilization'), (b'marketing_communication', b'Marketing communications and PR'), (b'system_tools', b'Systems tools and processes')], max_length=179, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserextendedprofile',
            name='goals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'contribute_to_org', b'Help improve my organization'), (b'gain_new_skill', b'Develop new skills'), (b'improve_job_prospect', b'Get a job'), (b'relation_with_other', b'Build relationships with other nonprofit leaders')], max_length=73, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserextendedprofile',
            name='hear_about_philanthropyu',
            field=openedx.custom.db.fields.MultiSelectWithOtherField(blank=True, choices=[(b'philanthropy_partner', b'A Philanthropy University Partner (Global Giving, +Acumen or another'), (b'colleague_same_organization', b'A Colleague From My Organization'), (b'friend_new_organization', b'A Friend Or Colleague (Not From My Organization)'), (b'interest_search', b'An Internet Search'), (b'linkedIn_advertisement', b'A LinkedIn Advertisement'), (b'facebook_advertisement', b'A Facebook Advertisement'), (b'twitter_not_colleague', b'Twitter (Not From A Colleague'), (b'other', b'Other')], max_length=417, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserextendedprofile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'strategy_planning', b'Strategy and planning'), (b'leadership_governance', b'Leadership and governance'), (b'program_design', b'Program design and development'), (b'measurement_eval', b'Measurement, evaluation, and learning'), (b'stakeholder_engagement', b'External relations and partnerships'), (b'human_resource', b'Human resource management'), (b'financial_management', b'Financial management'), (b'fundraising', b'Fundraising and resource mobilization'), (b'marketing_communication', b'Marketing, communications, and PR'), (b'system_tools', b'Systems, tools, and processes')], max_length=179, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserextendedprofile',
            name='learners_related',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'same_region', b'Learners from my region or country'), (b'similar_oe_interest', b'Learners interested in same areas of organization effectiveness'), (b'similar_org', b'Learners working for similar organizations'), (b'diff_who_are_different', b'Learners who are different from me')], max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='userextendedprofile',
            name='function_areas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'strategy_planning', b'Strategy and planning'), (b'leadership_governance', b'Leadership and governance'), (b'program_design', b'Program design and development'), (b'measurement_eval', b'Measurement evaluation and learning'), (b'stakeholder_engagement', b'External relations and partnerships'), (b'human_resource', b'Human resource management'), (b'financial_management', b'Financial management'), (b'fundraising', b'Fundraising and resource mobilization'), (b'marketing_communication', b'Marketing communications and PR'), (b'system_tools', b'Systems tools and processes')], max_length=179, null=True),
        ),
        migrations.AddField(
            model_name='userextendedprofile',
            name='goals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'contribute_to_org', b'Help improve my organization'), (b'gain_new_skill', b'Develop new skills'), (b'improve_job_prospect', b'Get a job'), (b'relation_with_other', b'Build relationships with other nonprofit leaders')], max_length=73, null=True),
        ),
        migrations.AddField(
            model_name='userextendedprofile',
            name='hear_about_philanthropyu',
            field=openedx.custom.db.fields.MultiSelectWithOtherField(blank=True, choices=[(b'philanthropy_partner', b'A Philanthropy University Partner (Global Giving, +Acumen or another'), (b'colleague_same_organization', b'A Colleague From My Organization'), (b'friend_new_organization', b'A Friend Or Colleague (Not From My Organization)'), (b'interest_search', b'An Internet Search'), (b'linkedIn_advertisement', b'A LinkedIn Advertisement'), (b'facebook_advertisement', b'A Facebook Advertisement'), (b'twitter_not_colleague', b'Twitter (Not From A Colleague'), (b'other', b'Other')], max_length=417, null=True),
        ),
        migrations.AddField(
            model_name='userextendedprofile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'strategy_planning', b'Strategy and planning'), (b'leadership_governance', b'Leadership and governance'), (b'program_design', b'Program design and development'), (b'measurement_eval', b'Measurement, evaluation, and learning'), (b'stakeholder_engagement', b'External relations and partnerships'), (b'human_resource', b'Human resource management'), (b'financial_management', b'Financial management'), (b'fundraising', b'Fundraising and resource mobilization'), (b'marketing_communication', b'Marketing, communications, and PR'), (b'system_tools', b'Systems, tools, and processes')], max_length=179, null=True),
        ),
        migrations.AddField(
            model_name='userextendedprofile',
            name='learners_related',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'same_region', b'Learners from my region or country'), (b'similar_oe_interest', b'Learners interested in same areas of organization effectiveness'), (b'similar_org', b'Learners working for similar organizations'), (b'diff_who_are_different', b'Learners who are different from me')], max_length=66, null=True),
        ),
    ]
