# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-18 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0029_auto_20200130_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserextendedprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserextendedprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicaluserextendedprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalOrganization',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
        migrations.DeleteModel(
            name='HistoricalUserExtendedProfile',
        ),
    ]
