# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-20 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0032_data_migration_model_optimization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_financial_management',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_fundraising',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_human_resource',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_leadership_governance',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_marketing_communication',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_measurement_eval',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_program_design',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_stakeholder_engagement',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_strategy_planning',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='function_system_tools',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='goal_contribute_to_org',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='goal_gain_new_skill',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='goal_improve_job_prospect',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='goal_relation_with_other',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='hear_about_philanthropy',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='hear_about_philanthropy_other',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_financial_management',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_fundraising',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_human_resource',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_leadership_governance',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_marketing_communication',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_measurement_eval',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_program_design',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_stakeholder_engagement',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_strategy_planning',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='interest_system_tools',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='learners_diff_who_are_different',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='learners_same_region',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='learners_similar_oe_interest',
        ),
        migrations.RemoveField(
            model_name='userextendedprofile',
            name='learners_similar_org',
        ),
    ]
