# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2022-06-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0033_auto_20200720_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_organization_registered',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Is Organization Registered as 501c3?'),
        ),
    ]
