# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2022-07-07 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0034_organization_is_organization_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextendedprofile',
            name='hubspot_contact_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
