# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_structures', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStructure',
        ),
    ]
