# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-08-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0010_customsettings_course_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='is_mini_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
