# Generated by Django 2.2.25 on 2022-07-26 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('profile_pic', models.ImageField(help_text='Upload the image which will be seen by student on their dashboard', upload_to='gen_plus_avatars')),
                ('standing', models.ImageField(help_text='Provide standing image of character', upload_to='gen_plus_avatars')),
                ('running', models.ImageField(help_text='Provide running image of character', upload_to='gen_plus_avatars')),
                ('crouching', models.ImageField(help_text='Provide crouching image of character', upload_to='gen_plus_avatars')),
                ('jumping', models.ImageField(help_text='Provide jumping image of character', upload_to='gen_plus_avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('group_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, choices=[('#E53935', '#E53935'), ('#AEEA00', '#AEEA00'), ('#EF6C00', '#EF6C00'), ('#304FFE', '#304FFE'), ('#0097A7', '#0097A7'), ('#1E88E5', '#1E88E5'), ('#388E3C', '#388E3C')], max_length=32, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gen_plus_classes')),
                ('name', models.CharField(max_length=128)),
                ('is_visible', models.BooleanField(default=False, help_text='Manage Visibility to Genplus platform')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Affiliate', 'Affiliate'), ('Employee', 'Employee'), ('TeachingStaff', 'TeachingStaff'), ('NonTeachingStaff', 'NonTeachingStaff')], max_length=32, null=True)),
                ('year_of_entry', models.CharField(blank=True, max_length=32, null=True)),
                ('registration_group', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('guid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=32)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='gen_plus_teachers')),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('gen_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teachers', through='genplus.TeacherClass', to='genplus.Class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gen_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='genplus.GenUser'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarded', models.BooleanField(default=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Character')),
                ('gen_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='genplus.GenUser')),
            ],
        ),
        migrations.AddField(
            model_name='genuser',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.School'),
        ),
        migrations.AddField(
            model_name='genuser',
            name='temp_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.TempUser'),
        ),
        migrations.AddField(
            model_name='genuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
