# Generated by Django 2.2.25 on 2022-06-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='genplus.Student'),
        ),
    ]
