# Generated by Django 2.2.25 on 2022-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0002_auto_20220701_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gen_plus_classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='gen_plus_teachers'),
        ),
    ]
