# Generated by Django 2.2.25 on 2022-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0002_auto_20220629_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='characters', to='genplus.Skill'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='genplus.Student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='genplus.Class'),
        ),
    ]
