# Generated by Django 2.2.25 on 2022-06-17 06:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0001_initial'),
        ('genplus', '0002_auto_20220613_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('profile_pic', models.ImageField(help_text='Upload the image which will be seen by student on their dashboard', upload_to='gen_plus_avatars')),
                ('standing', models.ImageField(help_text='Provide standing image of character', upload_to='gen_plus_avatars')),
                ('running', models.ImageField(help_text='Provide running image of character', upload_to='gen_plus_avatars')),
                ('crouching', models.ImageField(help_text='Provide crouching image of character', upload_to='gen_plus_avatars')),
                ('jumping', models.ImageField(help_text='Provide jumping image of character', upload_to='gen_plus_avatars')),
                ('skills', models.ManyToManyField(related_name='skills', to='genplus_learning.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('group_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('is_visible', models.BooleanField(default=False, help_text='Manage Visibility to Genplus platform')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.School')),
                ('year_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus_learning.YearGroup')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(null=True, upload_to='gen_plus_teachers')),
                ('classes', models.ManyToManyField(related_name='classes', to='genplus.Class')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genplus.GenUser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_board', models.BooleanField(default=False)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Character')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genplus.GenUser')),
                ('year_groups', models.ManyToManyField(related_name='year_groups', to='genplus_learning.YearGroup')),
            ],
        ),
    ]
