# Generated by Django 2.2.25 on 2022-06-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0003_character_class_student_teacher_tempstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_profile',
            new_name='gen_user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='on_board',
            new_name='onboarded',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user_profile',
            new_name='gen_user',
        ),
    ]
