# Generated by Django 2.2.25 on 2022-12-13 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0003_auto_20221208_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='journalpost',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='favorite_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='genplus.Class'),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
    ]
