# Generated by Django 2.2.25 on 2022-10-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0003_auto_20221006_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', through='genplus.ClassStudents', to='genplus.Student'),
        ),
        migrations.AlterField(
            model_name='classstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.Student'),
        ),
    ]
