# Generated by Django 2.2.25 on 2022-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0003_auto_20220705_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='favourite_classes',
            field=models.ManyToManyField(blank=True, to='genplus.Class'),
        ),
    ]
