# Generated by Django 2.2.25 on 2022-09-11 18:50

from django.db import migrations, models
import openedx.features.genplus_features.genplus.models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0004_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='crouching',
            field=models.FileField(help_text='Provide crouching position of character', upload_to='gen_plus_avatars', validators=[openedx.features.genplus_features.genplus.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='character',
            name='jumping',
            field=models.FileField(help_text='Provide jumping position of character', upload_to='gen_plus_avatars', validators=[openedx.features.genplus_features.genplus.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='character',
            name='running',
            field=models.FileField(help_text='Provide running position of character', upload_to='gen_plus_avatars', validators=[openedx.features.genplus_features.genplus.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='character',
            name='standing',
            field=models.FileField(help_text='Provide standing position of character', upload_to='gen_plus_avatars', validators=[openedx.features.genplus_features.genplus.models.validate_file_extension]),
        ),
    ]
