# Generated by Django 2.2.25 on 2022-12-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0004_auto_20221213_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuser',
            name='identity_guid',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
