# Generated by Django 2.2.25 on 2022-11-04 09:20

from django.db import migrations, models
import django.utils.timezone
import openedx.features.genplus_features.genplus.models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0004_auto_20221011_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='running',
            new_name='dance1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='crouching',
            new_name='dance2',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='jumping',
            new_name='dance3',
        ),
        migrations.AddField(
            model_name='character',
            name='dance4',
            field=models.FileField(default=django.utils.timezone.now, help_text='Provide jumping position of character', upload_to='gen_plus_avatars', validators=[openedx.features.genplus_features.genplus.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
