# Generated by Django 2.2.25 on 2022-11-25 04:36

from django.db import migrations, models


def set_email_default(apps, schema_editor):
    GenUser = apps.get_model('genplus', 'GenUser')
    for gen_user in GenUser.objects.all():
        if gen_user.user:
            gen_user.email = gen_user.user.email
            gen_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0006_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuser',
            name='email',
            field=models.EmailField(null=True, max_length=254, unique=True),
        ),
        migrations.RunPython(set_email_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='genuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
