# Generated by Django 2.2.25 on 2022-09-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0006_merge_20220923_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalpost',
            old_name='type',
            new_name='entry_type',
        ),
    ]
