# Generated by Django 2.2.25 on 2023-03-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0007_genlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlog',
            name='gen_log_type',
            field=models.CharField(choices=[('RMUnify provision update user deleted', 'RMUnify provision update user deleted'), ('Student removed from class', 'Student removed from class'), ('Student added to class', 'Student added to class')], max_length=128),
        ),
        migrations.AlterField(
            model_name='genuser',
            name='has_password_changed',
            field=models.BooleanField(default=True, help_text='If selected, the user has changed their password. De-select to force user to change password (enforced immediately).'),
        ),
    ]
