# Generated by Django 2.2.25 on 2022-09-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0007_auto_20220923_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalpost',
            old_name='entry_type',
            new_name='journal_type',
        ),
    ]
