# Generated by Django 2.2.25 on 2022-11-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0007_genuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genuser',
            name='temp_user',
        ),
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
