# Generated by Django 2.2.25 on 2022-11-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0008_auto_20221126_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Class'),
        ),
    ]
