# Generated by Django 2.2.25 on 2023-04-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0008_auto_20230315_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gen_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.School')),
            ],
        ),
    ]
