# Generated by Django 2.2.25 on 2023-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0009_generror'),
    ]

    operations = [
        migrations.AddField(
            model_name='generror',
            name='browser',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='generror',
            name='error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
