# Generated by Django 2.2.25 on 2023-05-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0010_auto_20230406_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
