# Generated by Django 2.2.25 on 2023-05-04 09:44

from django.db import migrations, models
from openedx.features.genplus_features.genplus.constants import JournalTypes
import uuid


def force_uuid(apps, schema_editor):
    JournalPost = apps.get_model('genplus', 'JournalPost')
    for instance in JournalPost.objects.filter(is_editable=True):
        instance.uuid = uuid.uuid4()
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0011_student_scn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalpost',
            options={},
        ),
        migrations.AddField(
            model_name='journalpost',
            name='uuid',
            field=models.CharField(null=True, unique=False, editable=False, max_length=64),
        ),
        # Force uuid on existing records
        migrations.RunPython(force_uuid),
        migrations.AlterField(
            model_name='journalpost',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, null=False, unique=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='journalpost',
            unique_together={('uuid', 'student')},
        ),
    ]
