# Generated by Django 2.2.25 on 2023-05-04 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0011_student_scn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalpost',
            options={},
        ),
        migrations.AddField(
            model_name='journalpost',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='journalpost',
            unique_together={('uuid', 'student')},
        ),
    ]
