# Generated by Django 2.2.25 on 2023-05-31 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0013_auto_20230525_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlog',
            name='gen_log_type',
            field=models.CharField(choices=[('RMUnify provision update user deleted', 'RMUnify provision update user deleted'), ('Student removed from class', 'Student removed from class'), ('Student added to class', 'Student added to class'), ('Program Enrollment remove', 'Program Enrollment remove'), ('Student part of more than one school', 'Student part of more than one school'), ('School Updated', 'School Updated')], max_length=128),
        ),
        migrations.AlterField(
            model_name='genuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
