# Generated by Django 2.2.25 on 2023-07-03 23:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0015_auto_20230618_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, choices=[('RmUnify', 'RmUnify'), ('Private', 'Private'), ('Xporter', 'Xporter')], max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='XporterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_secret', models.CharField(blank=True, max_length=1024, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_exception_message', models.TextField(blank=True, null=True)),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xporter_detail', to='genplus.School')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
