# Generated by Django 2.2.25 on 2023-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0016_auto_20230703_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If De-selected the users related to this school cannot access the platform'),
        ),
    ]
