# Generated by Django 2.2.25 on 2023-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0018_auto_20230919_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
