# Generated by Django 2.2.25 on 2023-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0018_auto_20231006_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(blank=True, choices=[('TeachingGroup', 'TeachingGroup'), ('RegistrationGroup', 'RegistrationGroup'), ('TeachingGrp', 'TeachingGrp'), ('RegGrp', 'RegGrp')], max_length=32, null=True),
        ),
    ]
