# Generated by Django 2.2.25 on 2023-10-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0019_auto_20231009_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cost_center',
            field=models.EmailField(blank=True, default=None, help_text='Need in the case of xporter schools.', max_length=254, null=True, unique=True),
        ),
    ]
