# Generated by Django 2.2.25 on 2023-10-11 13:21

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0021_auto_20231010_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthorityDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='genlog',
            name='gen_log_type',
            field=models.CharField(choices=[('RMUnify provision update user deleted', 'RMUnify provision update user deleted'), ('Student removed from class', 'Student removed from class'), ('Student added to class', 'Student added to class'), ('Program Enrollment remove', 'Program Enrollment remove'), ('Student part of more than one school', 'Student part of more than one school'), ('School Updated', 'School Updated'), ('Registration failed', 'Registration failed')], max_length=128),
        ),
        migrations.AddField(
            model_name='localauthority',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='local_authorities', to='genplus.LocalAuthorityDomain'),
        ),
    ]
