# Generated by Django 3.2.15 on 2022-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_auto_20191024_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceconfiguration',
            name='basket_checkout_page',
            field=models.CharField(default='http://localhost:1998', help_text='Path to course(s) checkout page hosted by the E-Commerce service.', max_length=255),
        ),
    ]
