# Generated by Django 3.2.16 on 2022-10-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcourseappstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course app status', 'verbose_name_plural': 'historical course app statuss'},
        ),
    ]
