# Generated by Django 3.2.13 on 2023-01-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('program_id', models.CharField(default='', max_length=250)),
                ('courses_list', models.JSONField()),
            ],
        ),
    ]
