# Generated by Django 3.2.13 on 2023-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(default='', max_length=250)),
                ('name', models.CharField(default='', max_length=1000)),
                ('course_list', models.CharField(default='', max_length=10000)),
                ('id_course_list', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
