# Generated by Django 3.2.13 on 2023-02-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxprograms',
            name='metadata',
            field=models.JSONField(default=''),
        ),
    ]
