# Generated by Django 2.2.20 on 2021-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('course_creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreator',
            name='all_organizations',
            field=models.BooleanField(default=True, help_text='To restrict the course creation by user in                                                 specific organizations'),
        ),
        migrations.AddField(
            model_name='coursecreator',
            name='orgs',
            field=models.ManyToManyField(blank=True, help_text='Organizations for which content creator is a part of', to='organizations.Organization'),
        ),
    ]
