# Generated by Django 2.2.20 on 2021-05-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('course_creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreator',
            name='all_organizations',
            field=models.BooleanField(default=True, help_text='Grant the user the permission to create courses in all organizations'),
        ),
        migrations.AddField(
            model_name='coursecreator',
            name='orgs',
            field=models.ManyToManyField(blank=True, help_text='Organizations under which the user is allowed to create courses', to='organizations.Organization'),
        ),
    ]
