# Generated by Django 2.2.19 on 2021-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_creators', '0002_coursecreator_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreator',
            name='all_organizations',
            field=models.BooleanField(default=True, help_text='To restrict the course creation by user in specific organizations'),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='orgs',
            field=models.ManyToManyField(blank=True, help_text='Organizations for which content creator is a part of', to='organizations.Organization'),
        ),
    ]
