# Generated by Django 2.2.12 on 2020-04-22 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('percentage_discount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegCodeItemAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=128, unique=True)),
                ('annotation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode_slug', models.CharField(max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('company_contact_name', models.CharField(max_length=255)),
                ('company_contact_email', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('total_amount', models.FloatField()),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('internal_reference', models.CharField(blank=True, help_text='Internal reference code for this invoice.', max_length=255, null=True)),
                ('customer_reference_number', models.CharField(blank=True, help_text="Customer's reference code for this invoice.", max_length=63, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qty', models.IntegerField(default=1, help_text='The number of items sold.')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='The price per item sold, including discounts.', max_digits=30)),
                ('currency', models.CharField(default='usd', help_text='Lower-case ISO currency codes', max_length=8)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The amount of the transaction.  Use positive amounts for payments and negative amounts for refunds.', max_digits=30)),
                ('currency', models.CharField(default='usd', help_text='Lower-case ISO currency codes', max_length=8)),
                ('comments', models.TextField(blank=True, help_text='Optional: provide additional information for this transaction', null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='started', help_text="The status of the payment or refund. 'started' means that payment is expected, but money has not yet been transferred. 'completed' means that the payment or refund was received. 'cancelled' means that payment or refund was expected, but was cancelled before money was transferred. ", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('status', models.CharField(choices=[('cart', 'cart'), ('paying', 'paying'), ('purchased', 'purchased'), ('refunded', 'refunded'), ('defunct-cart', 'defunct-cart'), ('defunct-paying', 'defunct-paying')], default='cart', max_length=32)),
                ('purchase_time', models.DateTimeField(blank=True, null=True)),
                ('refunded_time', models.DateTimeField(blank=True, null=True)),
                ('bill_to_first', models.CharField(blank=True, max_length=64)),
                ('bill_to_last', models.CharField(blank=True, max_length=64)),
                ('bill_to_street1', models.CharField(blank=True, max_length=128)),
                ('bill_to_street2', models.CharField(blank=True, max_length=128)),
                ('bill_to_city', models.CharField(blank=True, max_length=64)),
                ('bill_to_state', models.CharField(blank=True, max_length=8)),
                ('bill_to_postalcode', models.CharField(blank=True, max_length=16)),
                ('bill_to_country', models.CharField(blank=True, max_length=64)),
                ('bill_to_ccnum', models.CharField(blank=True, max_length=8)),
                ('bill_to_cardtype', models.CharField(blank=True, max_length=32)),
                ('processor_reply_dump', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_reference_number', models.CharField(blank=True, max_length=63, null=True)),
                ('order_type', models.CharField(choices=[('personal', 'personal'), ('business', 'business')], default='personal', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('cart', 'cart'), ('paying', 'paying'), ('purchased', 'purchased'), ('refunded', 'refunded'), ('defunct-cart', 'defunct-cart'), ('defunct-paying', 'defunct-paying')], db_index=True, default='cart', max_length=32)),
                ('qty', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('line_desc', models.CharField(default='Misc. Item', max_length=1024)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('fulfilled_time', models.DateTimeField(db_index=True, null=True)),
                ('refund_requested_time', models.DateTimeField(db_index=True, null=True)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('report_comments', models.TextField(default='')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PaidCourseRegistrationAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=128, unique=True)),
                ('annotation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCodeRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoppingcart.OrderItem')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=128)),
                ('mode', models.SlugField()),
            ],
            bases=('shoppingcart.orderitem',),
        ),
        migrations.CreateModel(
            name='CourseRegCodeItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoppingcart.OrderItem')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=128)),
                ('mode', models.SlugField(default='honor')),
            ],
            bases=('shoppingcart.orderitem',),
        ),
        migrations.CreateModel(
            name='CourseRegistrationCodeInvoiceItem',
            fields=[
                ('invoiceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoppingcart.InvoiceItem')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=128)),
            ],
            bases=('shoppingcart.invoiceitem',),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoppingcart.OrderItem')),
                ('donation_type', models.CharField(choices=[('general', 'A general donation'), ('course', 'A donation to a particular course')], default='general', max_length=32)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
            ],
            bases=('shoppingcart.orderitem',),
        ),
        migrations.CreateModel(
            name='PaidCourseRegistration',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoppingcart.OrderItem')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=128)),
                ('mode', models.SlugField(default='honor')),
            ],
            bases=('shoppingcart.orderitem',),
        ),
    ]
