# Generated by Django 2.2.15 on 2020-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_extension', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduserprofile',
            name='saudi_national',
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='is_saudi_national',
            field=models.BooleanField(null=True, verbose_name='Are you a Saudi National?'),
        ),
    ]
