# Generated by Django 2.2.14 on 2020-07-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercalendarsyncconfig',
            name='ics_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercalendarsyncconfig',
            name='ics_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
