# Generated by Django 3.2.20 on 2023-08-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0002_auto_20200709_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalusercalendarsyncconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user calendar sync config', 'verbose_name_plural': 'historical user calendar sync configs'},
        ),
    ]
