# Generated by Django 3.2.13 on 2022-06-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseliveconfiguration',
            name='free_tier',
            field=models.BooleanField(default=False, help_text='True, if LTI credential are provided by Org globally'),
        ),
        migrations.AddField(
            model_name='historicalcourseliveconfiguration',
            name='free_tier',
            field=models.BooleanField(default=False, help_text='True, if LTI credential are provided by Org globally'),
        ),
    ]
