# Generated by Django 3.2.13 on 2022-05-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_live', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcourseliveconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course live configuration', 'verbose_name_plural': 'historical course live configurations'},
        ),
    ]
