# Generated by Django 3.2.20 on 2023-08-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_live', '0002_auto_20220617_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcourseliveconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course live configuration', 'verbose_name_plural': 'historical course live configurations'},
        ),
    ]
