# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_remove_null_blank_from_schedules_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
    ]
