# Generated by Django 1.11.28 on 2020-03-04 21:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_historicalschedule_drop_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='start',
            field=models.DateTimeField(db_index=True, default=None, help_text='Date this schedule went into effect', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(db_index=True, default=None, help_text='Date this schedule went into effect', null=True),
        ),
    ]
