# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_schedules_start_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
