# Generated by Django 1.11.27 on 2020-01-07 18:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_schedules_start_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
    ]
