# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-12 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_remove_start_from_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalschedule',
            name='start',
        ),
    ]
