# Generated by Django 3.2.20 on 2023-08-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_remove_config_rollout_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalschedule',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Schedule', 'verbose_name_plural': 'historical Schedules'},
        ),
    ]
