# Generated by Django 3.2.20 on 2023-09-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_alter_historicalschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='deliver_course_due_date_reminder',
            field=models.BooleanField(default=False, help_text='Enable sending emails for due date reminder schedule.'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='enqueue_course_due_date_reminder',
            field=models.BooleanField(default=False, help_text='Enable message queuing process for due date reminder schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='deliver_course_update',
            field=models.BooleanField(default=False, help_text='Enable sending emails for course update schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='deliver_recurring_nudge',
            field=models.BooleanField(default=False, help_text='Enable sending emails for recurring nudge schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='deliver_upgrade_reminder',
            field=models.BooleanField(default=False, help_text='Enable sending emails for upgrade reminder schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='enqueue_course_update',
            field=models.BooleanField(default=False, help_text='Enable message queuing process for course update schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='enqueue_recurring_nudge',
            field=models.BooleanField(default=False, help_text='Enable message queuing process for recurring nudge schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='enqueue_upgrade_reminder',
            field=models.BooleanField(default=False, help_text='Enable message queuing process for upgrade reminder schedule.'),
        ),
    ]
