# Generated by Django 3.2 on 2021-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=250)),
                ('lesson_url', models.URLField(default='', max_length=250)),
                ('unit_title', models.CharField(default='', max_length=250)),
                ('instance_code', models.CharField(default='', max_length=250)),
                ('category_id', models.CharField(default='', max_length=250)),
                ('content', models.CharField(max_length=5000)),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
