# Generated by Django 3.2.13 on 2022-08-28 16:07

from django.db import migrations, models
import lms.djangoapps.feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=250)),
                ('lesson_url', models.URLField(default='', max_length=5000)),
                ('unit_title', models.CharField(default='', max_length=1000)),
                ('instance_code', models.CharField(default='', max_length=250)),
                ('category_id', models.CharField(default='', max_length=250)),
                ('content', models.CharField(max_length=5000)),
                ('attachment', models.ImageField(upload_to=lms.djangoapps.feedback.models.attachment_file_name)),
            ],
        ),
    ]
