# Generated by Django 3.2 on 2021-05-17 16:52

from django.db import migrations, models
import lms.djangoapps.feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.ImageField(upload_to=lms.djangoapps.feedback.models.attachment_file_name),
        ),
    ]
