# Generated by Django 3.2 on 2021-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lesson_url',
            field=models.URLField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='unit_title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]

