# Generated by Django 1.11.20 on 2019-03-11 19:19


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_duration_limits', '0006_auto_20190308_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedurationlimitconfig',
            name='org_course',
            field=models.CharField(blank=True, db_index=True, help_text="Configure values for all course runs associated with this course. This is should be formatted as 'org/course' (i.e. MITx/6.002x, HarvardX/CS50).", max_length=255, null=True, verbose_name='Course in Org'),
        ),
        migrations.AlterField(
            model_name='coursedurationlimitconfig',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Configure values for this course run. This should be formatted as the CourseKey (i.e. course-v1://MITx+6.002x+2019_Q1)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_overviews.CourseOverview', verbose_name='Course Run'),
        ),
        migrations.AlterField(
            model_name='coursedurationlimitconfig',
            name='org',
            field=models.CharField(blank=True, db_index=True, help_text='Configure values for all course runs associated with this Organization. This is the organization string (i.e. edX, MITx).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursedurationlimitconfig',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Configure values for all course runs associated with this site.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddIndex(
            model_name='coursedurationlimitconfig',
            index=models.Index(fields=['site', 'org', 'org_course', 'course'], name='course_dura_site_id_b5bbcd_idx'),
        ),
    ]
