# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 12:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_config', '0003_transcriptmigrationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptmigrationsetting',
            name='command_run',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
