# Generated by Django 1.11.14 on 2018-07-19 07:52


from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_config', '0004_transcriptmigrationsetting_command_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationEnqueuedCourse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('command_run', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transcriptmigrationsetting',
            name='batch_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
