# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_config', '0006_videothumbnailetting_updatedcoursevideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedcoursevideos',
            name='course_id',
            field=models.CharField(max_length=255),
        ),
    ]
