# Generated by Django 2.2.16 on 2021-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='course_experience',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Video')], default=0),
        ),
    ]
