# Generated by Django 2.2.16 on 2021-09-23 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_squashed_0007_historicalorganization'),
        ('custom_settings', '0002_courseoverviewcontent_course_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='card_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='publisher_logo_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='CourseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=256, null=True)),
                ('video_url', models.CharField(blank=True, max_length=256, null=True)),
                ('publisher_org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='course_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_settings.CourseSet'),
        ),
    ]
