# Generated by Django 2.2.25 on 2022-08-26 10:25

from django.db import migrations

GTCS_LIST = [
    '2.1.1 - Professional Knowledge and Understanding, Curriculum & Pedagogy',
    '2.1.2 - Professional Knowledge and Understanding, Curriculum & Pedagogy',
    '2.1.3 - Professional Knowledge and Understanding, Curriculum & Pedagogy',
    '2.1.4 - Professional Knowledge and Understanding, Curriculum & Pedagogy',
    '2.2.1 - Professional Knowledge and Understanding, Professional Responsibilities',
    '2.2.2 - Professional Knowledge and Understanding, Professional Responsibilities',
    '2.2.3 - Professional Knowledge and Understanding, Professional Responsibilities',
    '2.2.4 - Professional Knowledge and Understanding, Professional Responsibilities',
    '3.1.1 – Professional Skills and Abilities, Curriculum and Pedagogy',
    '3.1.2 – Professional Skills and Abilities, Curriculum and Pedagogy',
    '3.1.3 – Professional Skills and Abilities, Curriculum and Pedagogy',
    '3.1.4 – Professional Skills and Abilities, Curriculum and Pedagogy',
    '3.2.1 - Professional Skills  and Abilities, The Learning Context',
    '3.2.2 - Professional Skills  and Abilities, The Learning Context',
    '3.2.3 - Professional Skills  and Abilities, The Learning Context',
    '3.2.4 - Professional Skills  and Abilities, The Learning Context',
    '3.3.1 - Professional Skills  and Abilities, The Learning Context, Professional Learning',
    '3.3.2 - Professional Skills  and Abilities, The Learning Context, Professional Learning',
    '3.4.1 - Professional Skills  and Abilities, The Learning Context, Self-Evaluation',
    '3.4.2 - Professional Skills  and Abilities, The Learning Context, Self-Evaluation',
    '3.4.3 - Professional Skills  and Abilities, The Learning Context, Self-Evaluation',
    '3.4.4 - Professional Skills  and Abilities, The Learning Context, Self-Evaluation',
    '3.5.1 - Professional Skills  and Abilities, Resources',
    '3.5.2 - Professional Skills  and Abilities, Resources'
]
MEDIA_TYPES = ['text', 'audio', 'video']

def dump_gtcs(apps, schema_editor):
    '''
    dump list of gtcs
    '''
    Gtcs = apps.get_model('genplus_teach', 'Gtcs')
    MediaType = apps.get_model('genplus_teach', 'MediaType')
    for gtcs in GTCS_LIST:
        Gtcs.objects.create(name=gtcs)

    for media_type in MEDIA_TYPES:
        MediaType.objects.create(name=media_type)


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_teach', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dump_gtcs),
    ]
