# Generated by Django 2.2.25 on 2022-10-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0004_auto_20221011_0751'),
        ('genplus_teach', '0002_dump_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reflectionanswer',
            name='reflection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='genplus_teach.Reflection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reflectionanswer',
            unique_together={('reflection', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='reflectionanswer',
            name='article',
        ),
    ]
