# Generated by Django 2.2.25 on 2022-11-14 17:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0005_auto_20221104_0920'),
        ('genplus_teach', '0007_alertbarentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpGuideRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField()),
                ('help_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='genplus_teach.HelpGuide')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.Teacher')),
            ],
            options={
                'unique_together': {('teacher', 'help_guide')},
            },
        ),
    ]
