# Generated by Django 2.2.25 on 2022-11-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_teach', '0009_auto_20221124_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioentry',
            name='gtcs',
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='gtcs',
            field=models.ManyToManyField(blank=True, to='genplus_teach.Gtcs'),
        ),
    ]
