"""
Settings for OpenStack deployments.
"""

from .production import *  # pylint: disable=wildcard-import, unused-wildcard-import

SWIFT_AUTH_URL = EDXAPP_CONFIG.get('SWIFT_AUTH_URL')
SWIFT_AUTH_VERSION = EDXAPP_CONFIG.get('SWIFT_AUTH_VERSION', 1)
SWIFT_USERNAME = EDXAPP_CONFIG.get('SWIFT_USERNAME')
SWIFT_KEY = EDXAPP_CONFIG.get('SWIFT_KEY')
SWIFT_TENANT_NAME = EDXAPP_CONFIG.get('SWIFT_TENANT_NAME')
SWIFT_TENANT_ID = EDXAPP_CONFIG.get('SWIFT_TENANT_ID')
SWIFT_CONTAINER_NAME = FILE_UPLOAD_STORAGE_BUCKET_NAME
SWIFT_NAME_PREFIX = FILE_UPLOAD_STORAGE_PREFIX
SWIFT_USE_TEMP_URLS = EDXAPP_CONFIG.get('SWIFT_USE_TEMP_URLS', False)
SWIFT_TEMP_URL_KEY = EDXAPP_CONFIG.get('SWIFT_TEMP_URL_KEY')
SWIFT_TEMP_URL_DURATION = EDXAPP_CONFIG.get('SWIFT_TEMP_URL_DURATION', 1800)  # seconds
SWIFT_CONTENT_LENGTH_FROM_FD = EDXAPP_CONFIG.get('SWIFT_CONTENT_LENGTH_FROM_FD', False)
SWIFT_LAZY_CONNECT = EDXAPP_CONFIG.get('SWIFT_LAZY_CONNECT', True)

if EDXAPP_CONFIG.get('SWIFT_REGION_NAME'):
    SWIFT_EXTRA_OPTIONS = {'region_name': EDXAPP_CONFIG['SWIFT_REGION_NAME']}

if EDXAPP_CONFIG.get('DEFAULT_FILE_STORAGE'):
    DEFAULT_FILE_STORAGE = EDXAPP_CONFIG.get('DEFAULT_FILE_STORAGE')
elif SWIFT_AUTH_URL and SWIFT_USERNAME and SWIFT_KEY:
    DEFAULT_FILE_STORAGE = 'swift.storage.SwiftStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Use default file storage class set above for course import/export
COURSE_IMPORT_EXPORT_STORAGE = DEFAULT_FILE_STORAGE
