# Generated by Django 2.2.16 on 2021-06-22 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overrides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgressStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('completion_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('grade', models.CharField(default=None, max_length=4)),
                ('email_reminder_status', models.PositiveSmallIntegerField(choices=[(0, 'No email sent'), (1, 'Reminder email sent'), (2, 'Course completion email sent')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_id')},
            },
        ),
        migrations.DeleteModel(
            name='CourseProgressEmailModel',
        ),
    ]
