# Generated by Django 2.2.16 on 2021-06-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_userprofile_organization'),
        ('overrides', '0002_auto_20210622_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogressstats',
            options={'verbose_name_plural': 'Course Progress Stats'},
        ),
        migrations.AddField(
            model_name='courseprogressstats',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_stats', to='student.CourseEnrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprogressstats',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courseprogressstats',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='courseprogressstats',
            name='user',
        ),
    ]
