# Generated by Django 2.2.16 on 2021-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overrides', '0003_auto_20210628_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogressstats',
            name='grade',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
