"""
Constants for ou team app
"""

ALLOWED_PROFILE_IMAGE_EXTENSIONS = ('png', 'jpg', 'jpeg', 'svg')
PROFILE_IMAGE_MAX_SIZE = 2 * 1024 * 1024
MAX_NAME_LENGTH = 70
MAX_DESIGNATION_LENGTH = 70
MAX_DESCRIPTION_LENGTH = 200
