# Generated by Django 1.11.28 on 2020-02-24 18:36


from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_user_ids', '0002_mb_coaching_20200210_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalid',
            unique_together={('user', 'external_id_type')},
        ),
    ]
