# Generated by Django 2.2.12 on 2020-04-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_user_ids', '0003_auto_20200224_1836'),
    ]

    lti_type = 'lti'

    def create_lti_type(apps, schema_editor):
        """
        Add a LTI type
        """
        ExternalIdType = apps.get_model('external_user_ids', 'ExternalIdType')
        ExternalIdType.objects.update_or_create(name=Migration.lti_type, description='LTI Xblock launches')

    def delete_lti_type(apps, schema_editor):
        """
        Delete the LTI type
        """
        ExternalIdType = apps.get_model('external_user_ids', 'ExternalIdType')
        ExternalIdType.objects.filter(
            name=Migration.lti_type
        ).delete()

    operations = [
        migrations.RunPython(create_lti_type, reverse_code=delete_lti_type),
    ]
