# Generated by Django 3.2.18 on 2023-03-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_user_ids', '0004_add_lti_type'),
    ]

    caliper_type = 'caliper'
    xapi_type = 'xapi'

    def create_caliper_and_xapi_type(apps, schema_editor):
        """
        Add CALIPER and XAPI type
        """
        ExternalIdType = apps.get_model('external_user_ids', 'ExternalIdType')
        ExternalIdType.objects.update_or_create(name=Migration.caliper_type, description='Caliper Specification event transformer')
        ExternalIdType.objects.update_or_create(name=Migration.xapi_type, description='xAPI Specification event transformer')

    def delete_caliper_and_xapi_type(apps, schema_editor):
        """
        Delete CALIPER and XAPI type
        """
        ExternalIdType = apps.get_model('external_user_ids', 'ExternalIdType')
        ExternalIdType.objects.filter(
            name__in=[Migration.caliper_type, Migration.xapi_type]
        ).delete()

    operations = [
        migrations.RunPython(create_caliper_and_xapi_type, reverse_code=delete_caliper_and_xapi_type),
    ]
