# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-31 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucsd_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalregistrationfields',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
