# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-06 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdlyUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edly_sub_organizations', models.ManyToManyField(to='edly.EdlySubOrganization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edly_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
