# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0002_edlyuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edlysuborganization',
            name='lms_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edly_sub_org_for_lms', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='edlysuborganization',
            name='studio_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edly_sub_org_for_studio', to='sites.Site'),
        ),
    ]
