# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0004_edlysuborganization_preview_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlyorganization',
            name='enable_all_edly_sub_org_login',
            field=models.BooleanField(default=False),
        ),
    ]
