# pylint: skip-file
# Generated by Django 2.2.16 on 2021-08-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0007_make_edx_organizations_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlyuserprofile',
            name='is_blocked',
            field=models.BooleanField(
                default=False,
                help_text='Block/Unblock user from logging in to the platform.',
                verbose_name='Blocked'
            ),
        ),
    ]
