# Generated by Django 2.2.16 on 2023-04-17 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('edly', '0010_studentcourseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdlyMultiSiteAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_blocked', models.BooleanField(default=False, help_text='Block/Unblock user from logging in to the platform.', verbose_name='Blocked')),
                ('course_activity_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='groups')),
                ('sub_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_site', to='edly.EdlySubOrganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edly_multisite_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sub_org')},
            },
        ),
    ]
