# Generated by Django 2.2.24 on 2024-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0012_auto_20230418_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlymultisiteaccess',
            name='has_unsubscribed_email',
            field=models.BooleanField(default=False, help_text='Unsubscribe system generated emails.', verbose_name='Unsubscribe Email'),
        ),
    ]
