# Generated by Django 2.2.14 on 2020-07-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0001_squashed_0026_auto_20200401_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlproviderconfig',
            name='country',
            field=models.CharField(blank=True, help_text=('URN of SAML attribute containing the user`s country.',), max_length=128),
        ),
    ]
