# Generated by Django 2.2.15 on 2020-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0002_auto_20200721_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlconfiguration',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When checked, customers will be able to choose this SAML Configuration in the admin portal.', verbose_name='Allow customers to see and use this SAML configuration'),
        ),
    ]
