# Generated by Django 2.2.16 on 2020-09-19 09:55

from django.db import migrations, models
import openedx.core.lib.hash_utils


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0003_samlconfiguration_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiproviderconfig',
            name='lti_consumer_secret',
            field=models.CharField(blank=True, default=openedx.core.lib.hash_utils.create_hash256, help_text='The shared secret that the LTI Tool Consumer will use to authenticate requests. Only this edX instance and this tool consumer instance should know this value. For increased security, you can avoid storing this in your database by leaving this field blank and setting SOCIAL_AUTH_LTI_CONSUMER_SECRETS = {"consumer key": "secret", ...} in your instance\'s Django setttigs (or lms.yml)', max_length=255),
        ),
        migrations.AlterField(
            model_name='oauth2providerconfig',
            name='secret',
            field=models.TextField(blank=True, help_text='For increased security, you can avoid storing this in your database by leaving  this field blank and setting SOCIAL_AUTH_OAUTH_SECRETS = {"(backend name)": "secret", ...} in your instance\'s Django settings (or lms.yml)', verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='private_key',
            field=models.TextField(blank=True, help_text='To generate a key pair as two files, run "openssl req -new -x509 -days 3652 -nodes -out saml.crt -keyout saml.key". Paste the contents of saml.key here. For increased security, you can avoid storing this in your database by leaving this field blank and setting it via the SOCIAL_AUTH_SAML_SP_PRIVATE_KEY setting in your instance\'s Django settings (or lms.yml).'),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='public_key',
            field=models.TextField(blank=True, help_text="Public key certificate. For increased security, you can avoid storing this in your database by leaving this field blank and setting it via the SOCIAL_AUTH_SAML_SP_PUBLIC_CERT setting in your instance's Django settings (or lms.yml)."),
        ),
    ]
