# Generated by Django 3.2.12 on 2022-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0005_auto_20210723_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlproviderconfig',
            name='display_name',
            field=models.CharField(blank=True, help_text='A configuration nickname.', max_length=35),
        ),
        migrations.AlterField(
            model_name='ltiproviderconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this provider (shown to users)', max_length=50),
        ),
        migrations.AlterField(
            model_name='oauth2providerconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this provider (shown to users)', max_length=50),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='slug',
            field=models.SlugField(blank=True, default='default', help_text='A short string uniquely identifying this configuration. Cannot contain spaces. Examples: "ubc", "mit-staging"', max_length=30),
        ),
        migrations.AlterField(
            model_name='samlproviderconfig',
            name='backend_name',
            field=models.CharField(blank=True, default='tpa-saml', help_text="Which python-social-auth provider backend to use. 'tpa-saml' is the standard edX SAML backend.", max_length=50),
        ),
        migrations.AlterField(
            model_name='samlproviderconfig',
            name='entity_id',
            field=models.CharField(blank=True, help_text='Example: https://idp.testshib.org/idp/shibboleth', max_length=255, verbose_name='Entity ID'),
        ),
        migrations.AlterField(
            model_name='samlproviderconfig',
            name='identity_provider_type',
            field=models.CharField(blank=True, choices=[('standard_saml_provider', 'Standard SAML provider'), ('sap_success_factors', 'SAP SuccessFactors provider')], default='standard_saml_provider', help_text='Some SAML providers require special behavior. For example, SAP SuccessFactors SAML providers require an additional API call to retrieve user metadata not provided in the SAML response. Select the provider type which best matches your use case. If in doubt, choose the Standard SAML Provider type.', max_length=128, verbose_name='Identity Provider Type'),
        ),
        migrations.AlterField(
            model_name='samlproviderconfig',
            name='metadata_source',
            field=models.CharField(blank=True, help_text="URL to this provider's XML metadata. Should be an HTTPS URL. Example: https://www.testshib.org/metadata/testshib-providers.xml", max_length=255),
        ),
        migrations.AlterField(
            model_name='samlproviderconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this provider (shown to users)', max_length=50),
        ),
    ]
