# Generated by Django 3.2.12 on 2022-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0007_samlproviderconfig_was_valid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiproviderconfig',
            name='was_valid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamped field that indicates a user has successfully logged in using this configuration at least once.', null=True),
        ),
        migrations.AddField(
            model_name='oauth2providerconfig',
            name='was_valid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamped field that indicates a user has successfully logged in using this configuration at least once.', null=True),
        ),
    ]
