# Generated by Django 3.2.13 on 2022-04-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0009_historicalusersocialauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUserSocialAuth',
        ),
    ]
