# Generated by Django 3.2.18 on 2023-02-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0010_delete_historicalusersocialauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleMigrationUserIdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_apple_id', models.CharField(max_length=255)),
                ('transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('new_apple_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Apple User Id Migration Info',
                'verbose_name_plural': 'Apple User Id Migration Info',
            },
        ),
    ]
