# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0013_sync_learner_profile_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiproviderconfig',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='ltiproviderconfig',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='ltiproviderconfig',
            name='secondary',
        ),
    ]
