# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 07:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0021_sso_id_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlproviderconfig',
            name='default_email',
            field=models.CharField(blank=True, help_text=u'Default value for email to be used if not present in SAML response.', max_length=255, verbose_name=u'Default Value for Email'),
        ),
        migrations.AddField(
            model_name='samlproviderconfig',
            name='default_first_name',
            field=models.CharField(blank=True, help_text=u'Default value for first name to be used if not present in SAML response.', max_length=255, verbose_name=u'Default Value for First Name'),
        ),
        migrations.AddField(
            model_name='samlproviderconfig',
            name='default_full_name',
            field=models.CharField(blank=True, help_text=u'Default value for full name to be used if not present in SAML response.', max_length=255, verbose_name=u'Default Value for Full Name'),
        ),
        migrations.AddField(
            model_name='samlproviderconfig',
            name='default_last_name',
            field=models.CharField(blank=True, help_text=u'Default value for last name to be used if not present in SAML response.', max_length=255, verbose_name=u'Default Value for Last Name'),
        ),
        migrations.AddField(
            model_name='samlproviderconfig',
            name='default_username',
            field=models.CharField(blank=True, help_text=u'Default value for username to be used if not present in SAML response.', max_length=255, verbose_name=u'Default Value for Username'),
        ),
    ]
