# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 14:48


from django.db import migrations, models

import openedx.core.lib.hash_utils


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0024_fix_edit_disallowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiproviderconfig',
            name='lti_consumer_secret',
            field=models.CharField(blank=True, default=openedx.core.lib.hash_utils.create_hash256, help_text='The shared secret that the LTI Tool Consumer will use to authenticate requests. Only this edX instance and this tool consumer instance should know this value. For increased security, you can avoid storing this in your database by leaving this field blank and setting SOCIAL_AUTH_LTI_CONSUMER_SECRETS = {"consumer key": "secret", ...} in your instance\'s Django setttigs (or lms.auth.json)', max_length=255),
        ),
    ]
