"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('contentstore.tests.test_import_pure_xblock', 'cms.djangoapps.contentstore.tests.test_import_pure_xblock')

from cms.djangoapps.contentstore.tests.test_import_pure_xblock import *
