"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('contentstore.tests.test_core_caching', 'cms.djangoapps.contentstore.tests.test_core_caching')

from cms.djangoapps.contentstore.tests.test_core_caching import *
