# Generated by Django 4.2.20 on 2025-05-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursewarehistoryextended', '0002_force_studentmodule_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodulehistoryextended',
            name='student_module',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='courseware.studentmodule'),
        ),
        # This SeparateDatabaseAndState operation updates the state to match the model.
        # database_operations is left empty because the indexes were already dropped
        # by the previous operation in the database.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterIndexTogether(
                    name='studentmodulehistoryextended',
                    index_together=set(),
                ),
            ],
        ),
        # Adds back the index on 'student_module' to ensure there is a single index on this field.
        migrations.AddIndex(
            model_name='studentmodulehistoryextended',
            index=models.Index(fields=['student_module'], name='student_module_idx'),
        ),
    ]
