# Generated by Django 2.2.18 on 2021-02-10 03:34

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NexBlockLearnerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_context_key', opaque_keys.edx.django.models.LearningContextKeyField(max_length=255)),
                ('block_type', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('learning_context_key', 'block_type')},
            },
        ),
    ]
