""" Constants used throughout ESG """

# Query params
PARAM_ORA_LOCATION = "oraLocation"
PARAM_SUBMISSION_ID = "submissionUUID"
PARAM_ASSESSMENT_FILTER = "assessmentFilter"

# Error codes
ERR_UNKNOWN = "ERR_UNKNOWN"
ERR_INTERNAL = "ERR_INTERNAL"
ERR_MISSING_PARAM = "ERR_MISSING_PARAM"
ERR_BAD_ORA_LOCATION = "ERR_BAD_ORA_LOCATION"
ERR_LOCK_CONTESTED = "ERR_LOCK_CONTESTED"
ERR_GRADE_CONTESTED = "ERR_GRADE_CONTESTED"
