# Generated by Django 2.2.14 on 2020-07-22 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0002_coursesectionsequence_inaccessible_after_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContext',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('learning_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='course_context', serialize=False, to='learning_sequences.LearningContext')),
                ('course_visibility', models.CharField(choices=[('private', 'private'), ('public_outline', 'public_outline'), ('public', 'public')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course_context',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning_sequences.CourseContext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='course_context',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section_sequences', to='learning_sequences.CourseContext'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('course_context', 'usage_key')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesectionsequence',
            unique_together={('course_context', 'ordering')},
        ),
        migrations.AlterIndexTogether(
            name='coursesection',
            index_together={('course_context', 'ordering')},
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='learning_context',
        ),
        migrations.RemoveField(
            model_name='coursesectionsequence',
            name='learning_context',
        ),
    ]
