# Generated by Django 2.2.15 on 2020-09-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0004_coursecontext_self_paced'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontext',
            name='days_early_for_beta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
