# Generated by Django 2.2.14 on 2020-07-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0005_coursecontext_days_early_for_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontext',
            name='entrance_exam_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
