# Generated by Django 2.2.19 on 2021-03-12 16:31

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0008_add_learning_context_title_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_errors', models.PositiveIntegerField()),
                ('num_sections', models.PositiveIntegerField()),
                ('num_sequences', models.PositiveIntegerField()),
                ('learning_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish_report', to='learning_sequences.LearningContext')),
            ],
        ),
        migrations.CreateModel(
            name='ContentError',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255, null=True)),
                ('message', models.TextField(max_length=10000)),
                ('publish_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_errors', to='learning_sequences.PublishReport')),
            ],
        ),
    ]
