# Generated by Django 2.2.19 on 2021-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0009_contenterror_publishreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishreport',
            name='num_errors',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='publishreport',
            name='num_sections',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='publishreport',
            name='num_sequences',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
