# Generated by Django 2.2.19 on 2021-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0011_course_meta_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartitionGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('partition_id', models.BigIntegerField()),
                ('group_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='userpartitiongroup',
            index=models.Index(fields=['partition_id', 'group_id'], name='learning_se_partiti_6e2d28_idx'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='user_partition_groups',
            field=models.ManyToManyField(to='learning_sequences.UserPartitionGroup'),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='user_partition_groups',
            field=models.ManyToManyField(to='learning_sequences.UserPartitionGroup'),
        ),
    ]
