# Generated by Django 2.2.24 on 2021-07-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0015_add_user_partition_group_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpartitiongroup',
            unique_together=set(),
        ),
    ]
