# Generated by Django 2.2.24 on 2021-07-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0015_add_user_partition_group_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='user_partition_groups',
        ),
        migrations.RemoveField(
            model_name='coursesectionsequence',
            name='user_partition_groups',
        ),
    ]
