# Generated by Django 3.2.23 on 2023-12-14 23:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0016_through_model_for_user_partition_groups_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSequenceAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_access_controlled', models.BooleanField(default=False)),
                ('access_control_type', models.CharField(max_length=255, null=True)),
                ('course_section_sequence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='learning_sequences.coursesectionsequence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
