# Generated by Django 2.2.24 on 2021-08-11 20:48

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0016_through_model_for_user_partition_groups_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsequence',
            name='usage_key_hash',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='learningsequence',
            name='usage_key',
            field=opaque_keys.edx.django.models.UsageKeyField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='learningsequence',
            unique_together={('learning_context', 'usage_key_hash')},
        ),
    ]
