# Generated by Django 2.2.25 on 2022-08-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import openedx.features.genplus_features.genplus_badges.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genplus', '0004_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[openedx.features.genplus_features.genplus_badges.models.validate_lowercase])),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='booster_badge_classes', validators=[openedx.features.genplus_features.genplus_badges.models.validate_badge_image])),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='BoosterBadgeAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('feedback', models.TextField()),
                ('image_url', models.URLField()),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_awards', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_badges.BoosterBadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
