# Generated by Django 2.2.25 on 2022-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosterbadgeaward',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
