# Generated by Django 2.2.25 on 2022-09-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('genplus_badges', '0003_auto_20220914_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterBadgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='booster_badge_types')),
            ],
        ),
        migrations.RenameField(
            model_name='boosterbadge',
            old_name='skill',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='boosterbadge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_badges.BoosterBadgeType'),
        ),
    ]
