# Generated by Django 2.2.14 on 2020-07-22 11:06

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDiscussionsIdMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('external_discussion_id', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='externaldiscussionsidmapping',
            index=models.Index(fields=['context_key', 'usage_key'], name='discussions_context_5e655a_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaldiscussionsidmapping',
            constraint=models.UniqueConstraint(fields=('context_key', 'usage_key'), name='unique_externaldiscussionsidmapping_context_usage'),
        ),
    ]
