# Generated by Django 2.2.16 on 2020-10-16 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields
import opaque_keys.edx.django.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organizations', '0001_squashed_0007_historicalorganization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionProviderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('name',
                 models.CharField(help_text='A user-friendly name for this configuration. e.g. SomeOrg Discourse',
                     max_length=100)),
                ('provider', models.CharField(db_index=True, help_text='The discussion tool/provider.', max_length=100,
                    verbose_name='Discussion provider')),
                ('config', jsonfield.fields.JSONField(default={},
                    blank=True,
                    dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')},
                    help_text='The configuration data for this provider.', load_kwargs={})),
                ('restrict_to_org', models.ForeignKey(blank=True,
                    help_text='Optionally restrict this config for use only on this Organization.', null=True,
                    on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('restrict_to_site',
                 models.ForeignKey(blank=True, help_text='Optionally restrict this config for use only on this site.',
                     null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningContextDiscussionConfig',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('context_key',
                 opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255, primary_key=True,
                     serialize=False, unique=True, verbose_name='Learning Context')),
                ('enabled', models.BooleanField(default=True,
                    help_text='If disabled, the discussions in the associated learning context/course will be disabled.')),
                ('config_overrides', jsonfield.fields.JSONField(default={},
                    blank=True,
                    dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')},
                    help_text='Overrides course-specific configuration.', load_kwargs={})),
                ('provider_config',
                 models.ForeignKey(blank=True, help_text='The configuration to use for this learning context.',
                     null=True, on_delete=django.db.models.deletion.SET_NULL,
                     to='discussions.DiscussionProviderConfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalLearningContextDiscussionConfig',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255,
                    verbose_name='Learning Context')),
                ('enabled', models.BooleanField(default=True,
                    help_text='If disabled, the discussions in the associated learning context/course will be disabled.')),
                ('config_overrides', jsonfield.fields.JSONField(default={},
                    blank=True,
                    dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')},
                    help_text='Overrides course-specific configuration.', load_kwargs={})),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('provider_config', models.ForeignKey(blank=True, db_constraint=False,
                    help_text='The configuration to use for this learning context.', null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                    to='discussions.DiscussionProviderConfig')),
            ],
            options={
                'verbose_name': 'historical learning context discussion config',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiscussionProviderConfig',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('name',
                 models.CharField(help_text='A user-friendly name for this configuration. e.g. SomeOrg Discourse',
                     max_length=100)),
                ('provider', models.CharField(db_index=True, help_text='The discussion tool/provider.', max_length=100,
                    verbose_name='Discussion provider')),
                ('config', jsonfield.fields.JSONField(default={},
                    blank=True,
                    dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')},
                    help_text='The configuration data for this provider.', load_kwargs={})),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('restrict_to_org', models.ForeignKey(blank=True, db_constraint=False,
                    help_text='Optionally restrict this config for use only on this Organization.', null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.Organization')),
                ('restrict_to_site', models.ForeignKey(blank=True, db_constraint=False,
                    help_text='Optionally restrict this config for use only on this site.', null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.Site')),
            ],
            options={
                'verbose_name': 'historical discussion provider config',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
