# Generated by Django 2.2.19 on 2021-03-01 14:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_add_provider_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionsconfiguration',
            name='plugin_configuration',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='The plugin configuration data for this context/provider.'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussionsconfiguration',
            name='plugin_configuration',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='The plugin configuration data for this context/provider.'),
        ),
    ]
