# Generated by Django 2.2.24 on 2021-08-31 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0012_rename_courseeditltifieldsenabledflag_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0003_alter_provider_filter_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDiscussionsConfiguration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program_uuid', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Program UUID')),
                ('enabled', models.BooleanField(default=True, help_text='If disabled, the discussions in the associated program will be disabled.')),
                ('provider_type', models.CharField(help_text="The discussion provider's id", max_length=50, verbose_name='Discussion provider')),
                ('lti_configuration', models.ForeignKey(blank=True, help_text='The LTI configuration data for this program/provider.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti_consumer.LtiConfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProgramDiscussionsConfiguration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program_uuid', models.CharField(db_index=True, max_length=50, verbose_name='Program UUID')),
                ('enabled', models.BooleanField(default=True, help_text='If disabled, the discussions in the associated program will be disabled.')),
                ('provider_type', models.CharField(help_text="The discussion provider's id", max_length=50, verbose_name='Discussion provider')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lti_configuration', models.ForeignKey(blank=True, db_constraint=False, help_text='The LTI configuration data for this program/provider.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lti_consumer.LtiConfiguration')),
            ],
            options={
                'verbose_name': 'historical program discussions configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
