# Generated by Django 2.2.24 on 2021-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_alter_provider_filter_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionsconfiguration',
            name='context_key',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Learning Context Key'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussionsconfiguration',
            name='context_key',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Learning Context Key'),
        ),
    ]
