# Generated by Django 2.2.24 on 2021-10-06 04:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20210910_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionsconfiguration',
            name='enable_graded_units',
            field=models.BooleanField(default=False, help_text='If enabled, discussion topics will be created for graded units as well.'),
        ),
        migrations.AddField(
            model_name='discussionsconfiguration',
            name='enable_in_context',
            field=models.BooleanField(default=True, help_text='If enabled, discussion topics will be created for each non-graded unit in the course. A UI for discussions will show up with each unit.'),
        ),
        migrations.AddField(
            model_name='discussionsconfiguration',
            name='unit_level_visibility',
            field=models.BooleanField(default=False, help_text='If enabled, discussions will need to be manually enabled for each unit.'),
        ),
        migrations.AddField(
            model_name='historicaldiscussionsconfiguration',
            name='enable_graded_units',
            field=models.BooleanField(default=False, help_text='If enabled, discussion topics will be created for graded units as well.'),
        ),
        migrations.AddField(
            model_name='historicaldiscussionsconfiguration',
            name='enable_in_context',
            field=models.BooleanField(default=True, help_text='If enabled, discussion topics will be created for each non-graded unit in the course. A UI for discussions will show up with each unit.'),
        ),
        migrations.AddField(
            model_name='historicaldiscussionsconfiguration',
            name='unit_level_visibility',
            field=models.BooleanField(default=False, help_text='If enabled, discussions will need to be manually enabled for each unit.'),
        ),
        migrations.AlterField(
            model_name='discussionsconfiguration',
            name='provider_type',
            field=models.CharField(default='legacy', help_text="The discussion tool/provider's id", max_length=100, verbose_name='Discussion provider'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussionsconfiguration',
            name='provider_type',
            field=models.CharField(default='legacy', help_text="The discussion tool/provider's id", max_length=100, verbose_name='Discussion provider'),
        ),
        migrations.AlterField(
            model_name='providerfilter',
            name='allow',
            field=django_mysql.models.ListCharField(models.CharField(
                choices=[('legacy', 'legacy'), ('ed-discuss', 'ed-discuss'), ('inscribe', 'inscribe'),
                         ('piazza', 'piazza'), ('yellowdig', 'yellowdig')], max_length=20), blank=True,
                help_text='Comma-separated list of providers to allow, eg: legacy,ed-discuss,inscribe,piazza,yellowdig',
                max_length=63, size=3, verbose_name='Allow List'),
        ),
        migrations.AlterField(
            model_name='providerfilter',
            name='deny',
            field=django_mysql.models.ListCharField(models.CharField(
                choices=[('legacy', 'legacy'), ('ed-discuss', 'ed-discuss'), ('inscribe', 'inscribe'),
                         ('piazza', 'piazza'), ('yellowdig', 'yellowdig')], max_length=20), blank=True,
                help_text='Comma-separated list of providers to deny, eg: legacy,ed-discuss,inscribe,piazza,yellowdig',
                max_length=63, size=3, verbose_name='Deny List'),
        ),
    ]
