# Generated by Django 3.2.8 on 2021-10-21 12:02

import django.db.models.deletion
import django_mysql.models
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course_groups', '0003_auto_20170609_1455'),
        ('discussions', '0006_auto_20211006_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerfilter',
            name='allow',
            field=django_mysql.models.ListCharField(models.CharField(
                choices=[('legacy', 'legacy'), ('openedx', 'openedx'), ('ed-discuss', 'ed-discuss'),
                         ('inscribe', 'inscribe'), ('piazza', 'piazza'), ('yellowdig', 'yellowdig')], max_length=20),
                blank=True,
                help_text='Comma-separated list of providers to allow, eg: legacy,openedx,ed-discuss,inscribe,piazza,yellowdig',
                max_length=63, size=3, verbose_name='Allow List'),
        ),
        migrations.AlterField(
            model_name='providerfilter',
            name='deny',
            field=django_mysql.models.ListCharField(models.CharField(
                choices=[('legacy', 'legacy'), ('openedx', 'openedx'), ('ed-discuss', 'ed-discuss'),
                         ('inscribe', 'inscribe'), ('piazza', 'piazza'), ('yellowdig', 'yellowdig')], max_length=20),
                blank=True,
                help_text='Comma-separated list of providers to deny, eg: legacy,openedx,ed-discuss,inscribe,piazza,yellowdig',
                max_length=63, size=3, verbose_name='Deny List'),
        ),
        migrations.CreateModel(
            name='DiscussionTopicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True,
                    help_text='Context key for context in which this discussion topic exists.', max_length=255,
                    verbose_name='Learning Context Key')),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(blank=True, db_index=True,
                    help_text='Usage key for in-context discussion topic. Set to null for course-level topics.',
                    max_length=255, null=True)),
                ('title', models.CharField(help_text='Title for discussion topic.', max_length=255)),
                ('provider_id', models.CharField(help_text='Provider id for discussion provider.', max_length=32)),
                ('external_id', models.CharField(db_index=True,
                    help_text='Discussion context ID in external forum provider. e.g. commentable_id for cs_comments_service.',
                    max_length=255)),
                ('enabled_in_context', models.BooleanField(default=True,
                    help_text='Whether this topic should be shown in-context in the course.')),
                ('group', models.ForeignKey(blank=True, help_text='Group for divided discussions.', null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='course_groups.courseusergroup')),
            ],
        ),
    ]
