# Generated by Django 3.2.9 on 2021-12-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_add_discussion_topic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopiclink',
            name='ordering',
            field=models.PositiveIntegerField(help_text='Ordering of this topic in its learning context', null=True),
        ),
    ]
