# Generated by Django 3.2.11 on 2022-01-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_auto_20220119_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopiclink',
            name='ordering',
            field=models.PositiveIntegerField(help_text='Ordering of this topic in its learning context', null=True),
        ),
    ]
