# Generated by Django 3.2.15 on 2022-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0013_auto_20220802_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionsconfiguration',
            name='unit_level_visibility',
            field=models.BooleanField(default=True, help_text='If enabled, discussions will need to be manually enabled for each unit.'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussionsconfiguration',
            name='unit_level_visibility',
            field=models.BooleanField(default=True, help_text='If enabled, discussions will need to be manually enabled for each unit.'),
        ),
    ]
