# Generated by Django 3.2.15 on 2022-09-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0014_auto_20220826_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopiclink',
            name='context',
            field=models.JSONField(
                default=dict,
                help_text='Additional context for this topic, such as its section, and subsection'
            ),
        ),
    ]
