# Generated by Django 3.2.19 on 2023-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_discussiontopiclink_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionsconfiguration',
            name='posting_restrictions',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('scheduled', 'Scheduled')], default='scheduled', help_text='If enabled, posting in discussions will be indefinitely disabled.', max_length=15),
        ),
        migrations.AddField(
            model_name='historicaldiscussionsconfiguration',
            name='posting_restrictions',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('scheduled', 'Scheduled')], default='scheduled', help_text='If enabled, posting in discussions will be indefinitely disabled.', max_length=15),
        ),
    ]
