# Generated by Django 3.2.16 on 2022-10-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_discussiontopiclink_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldiscussionsconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical discussions configuration', 'verbose_name_plural': 'historical discussions configurations'},
        ),
    ]
