# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_utils', '0002_data__default_rate_limit_config'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ratelimitconfiguration',
            table='common_utils_ratelimitconfiguration',
        ),
    ]
