from import_shims.warn import warn_deprecated_import

warn_deprecated_import('student.management.tests.test_populate_created_on_site_user_attribute', 'common.djangoapps.student.management.tests.test_populate_created_on_site_user_attribute')

from common.djangoapps.student.management.tests.test_populate_created_on_site_user_attribute import *
