swagger: '2.0'
info:
  title: Instructor Dashboard ORA API v2
  version: 2.0.0
  description: |
    REST API for Open Response Assessment (ORA) operations in the Instructor Dashboard.
    Designed to support the Instructor Dashboard Micro-Frontend (MFE).

    **Design Principles:**
    - RESTful resource-oriented URLs
    - Course-scoped endpoints
    - Read-only operations
    - Centralized permission checks
    - Consistent error handling

host: courses.example.com
basePath: /
schemes:
  - https

securityDefinitions:
  JWTAuth:
    type: apiKey
    in: header
    name: Authorization
    description: JWT token authentication (e.g. `JWT <token>`).

security:
  - JWTAuth: []

tags:
  - name: ORA
    description: Open Response Assessment instructor data

paths:
  /api/instructor/v2/courses/{course_id}/ora/summary:
    get:
      tags:
        - ORA
      summary: Get ORA summary statistics
      description: |
        Retrieve an overview of Open Response Assessments (ORA) for a course,
        including total assessments, responses, and grading state breakdowns.
      operationId: getORASummary
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/CourseId'
      responses:
        200:
          description: ORA summary retrieved successfully
          schema:
            $ref: '#/definitions/ORASummary'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        404:
          $ref: '#/responses/NotFound'

  /api/instructor/v2/courses/{course_id}/ora:
    get:
      tags:
        - ORA
      summary: List ORA assessments with detailed statistics
      description: |
        Retrieve detailed information for all Open Response Assessments (ORA)
        in a course, including response counts and grading states per assessment.
      operationId: listORA
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/CourseId'
      responses:
        200:
          description: ORA assessment list retrieved successfully
          schema:
            $ref: '#/definitions/ORAList'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        404:
          $ref: '#/responses/NotFound'

parameters:
  CourseId:
    name: course_id
    in: path
    required: true
    description: Course identifier in format `course-v1:{org}+{course}+{run}`
    type: string
    pattern: '^course-v1:[^/+]+(\\+[^/+]+)+(\\+[^/]+)$'
    x-example: "course-v1:edX+DemoX+Demo_Course"

responses:
  BadRequest:
    description: Bad request - Invalid parameters or malformed request
    schema:
      $ref: '#/definitions/Error'
    examples:
      application/json:
        error: "INVALID_PARAMETER"
        message: "Invalid course key format"

  Unauthorized:
    description: Unauthorized - Authentication required
    schema:
      $ref: '#/definitions/Error'
    examples:
      application/json:
        error: "AUTHENTICATION_REQUIRED"
        message: "You must be authenticated to access this endpoint"

  Forbidden:
    description: Forbidden - Insufficient permissions
    schema:
      $ref: '#/definitions/Error'
    examples:
      application/json:
        error: "PERMISSION_DENIED"
        message: "You do not have instructor permissions for this course"

  NotFound:
    description: Not found - Resource does not exist
    schema:
      $ref: '#/definitions/Error'
    examples:
      application/json:
        error: "RESOURCE_NOT_FOUND"
        message: "The specified resource does not exist"

definitions:
  ORASummary:
    type: object
    description: Aggregated ORA statistics for a course
    required:
      - total_units
      - total_assessments
      - total_responses
      - training
      - peer
      - self
      - waiting
      - staff
      - final_grade_received
    properties:
      total_units:
        type: integer
        minimum: 0
        description: Total number of ORA units in the course
        example: 12
      total_assessments:
        type: integer
        minimum: 0
        description: Total number of ORA assessments
        example: 25
      total_responses:
        type: integer
        minimum: 0
        description: Total number of learner responses
        example: 350
      training:
        type: integer
        minimum: 0
        description: Responses in training step
        example: 40
      peer:
        type: integer
        minimum: 0
        description: Responses in peer grading
        example: 120
      self:
        type: integer
        minimum: 0
        description: Responses in self assessment
        example: 60
      waiting:
        type: integer
        minimum: 0
        description: Responses waiting for grading
        example: 30
      staff:
        type: integer
        minimum: 0
        description: Responses requiring staff grading
        example: 20
      final_grade_received:
        type: integer
        minimum: 0
        description: Responses with final grade assigned
        example: 80

  ORAList:
    type: object
    description: List of ORA assessments with detailed statistics
    required:
      - assessments
    properties:
      assessments:
        type: array
        items:
          $ref: '#/definitions/ORAAssessment'

  ORAAssessment:
    type: object
    description: Detailed ORA assessment statistics
    required:
      - block_id
      - unit_name
      - display_name
      - total_responses
      - training
      - peer
      - self
      - waiting
      - staff
      - final_grade_received
      - staff_ora_grading_url
    properties:
      block_id:
        type: string
        description: ORA block usage key
        example: "block-v1:edX+DemoX+Demo_Course+type@openassessment+block@ora1"
      unit_name:
        type: string
        description: Name of the unit containing the ORA assessment
        example: "Week 1: Introduction"
      display_name:
        type: string
        description: Display name of the ORA assessment
        example: "Peer Review Assignment 1"
      total_responses:
        type: integer
        minimum: 0
        description: Total responses submitted
        example: 120
      training:
        type: integer
        minimum: 0
        description: Responses in training step
        example: 15
      peer:
        type: integer
        minimum: 0
        description: Responses in peer grading
        example: 50
      self:
        type: integer
        minimum: 0
        description: Responses in self assessment
        example: 20
      waiting:
        type: integer
        minimum: 0
        description: Responses waiting for grading
        example: 10
      staff:
        type: integer
        minimum: 0
        description: Responses requiring staff grading
        example: 5
      final_grade_received:
        type: integer
        minimum: 0
        description: Responses with final grade assigned
        example: 20
      staff_ora_grading_url:
        type: string
        format: uri
        description: URL to the staff grading interface for this ORA assessment
        example: "http://apps.local.openedx.io:1993/ora-grading/block-v1:WGU+CS002+2025_T1+type@openassessment+block@ff4f5fddf42d4b9787e69c1a8cbeb058"
  Error:
    type: object
    description: Error response
    required:
      - error
      - message
    properties:
      error:
        type: string
        description: Machine-readable error code
      message:
        type: string
        description: Human-readable error message
      field_errors:
        type: object
        description: Field-specific validation errors
        additionalProperties:
          type: string
