# Generated by Django 1.11.20 on 2019-03-06 15:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_gating', '0004_auto_20181128_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttypegatingconfig',
            name='enabled_as_of',
            field=models.DateTimeField(blank=True, default=None, help_text='If the configuration is Enabled, then all enrollments created after this date and time (user local time) will be affected.', null=True, verbose_name='Enabled As Of'),
        ),
    ]
