# Generated by Django 1.11.20 on 2019-03-08 14:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_type_gating', '0005_auto_20190306_1547'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contenttypegatingconfig',
            index=models.Index(fields=['site', 'org', 'course'], name='content_typ_site_id_e91576_idx'),
        ),
    ]
