# Generated by Django 3.2.10 on 2023-13-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunixSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name' , models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('created' ,models.DateTimeField(auto_now_add=True) )
            ],
        ),
        migrations.CreateModel(
            name='FunixSpecializationCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id' , models.CharField(max_length=255)),
                ('spec' , models.ForeignKey('FunixSpecialization', on_delete=models.CASCADE)),
                ('user_id', models.CharField(max_length=255))
            ]
        )
    ]