# Generated by Django 3.2.20 on 2023-08-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalusersocialauth',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user social auth', 'verbose_name_plural': 'historical user social auths'},
        ),
    ]
