# Generated by Django 4.2.10 on 2024-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_course_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresetaudit',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
