# Generated by Django 4.2.10 on 2024-03-29 18:56

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_add_comment_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresetcourseoptin',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(max_length=255, unique=True),
        ),
    ]
