# Generated by Django 2.2.24 on 2021-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffle_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waffleflagcourseoverridemodel',
            name='note',
            field=models.TextField(blank=True, help_text='e.g. why this exists and when/if it can be dropped'),
        ),
    ]
