# Generated by Django 3.2.11 on 2022-01-13 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waffle_utils', '0002_waffleflagcourseoverridemodel_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaffleFlagOrgOverrideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('waffle_flag', models.CharField(db_index=True, max_length=255)),
                ('org', models.CharField(db_index=True, max_length=255)),
                ('override_choice', models.CharField(choices=[('on', 'Force On'), ('off', 'Force Off')], default='on', max_length=3)),
                ('note', models.TextField(blank=True, help_text='e.g. why this exists and when/if it can be dropped')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': 'Waffle flag org override',
                'verbose_name_plural': 'Waffle flag org overrides',
            },
        ),
        migrations.AddIndex(
            model_name='waffleflagorgoverridemodel',
            index=models.Index(fields=['org', 'waffle_flag'], name='waffle_org_and_waffle_flag'),
        ),
    ]
