# Generated by Django 3.2.12 on 2022-03-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_for_later', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcourse',
            name='marketing_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='max_effort',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='min_effort',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='org_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='weeks_to_complete',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='email_sent_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='savedcourse',
            unique_together={('email', 'course_id')},
        ),
        migrations.AddField(
            model_name='savedprogram',
            name='email_sent_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='savedprogram',
            unique_together={('email', 'program_uuid')},
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='reminder_email_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='savedprogram',
            name='reminder_email_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
