# Generated by Django 3.2.20 on 2023-07-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save_for_later', '0002_auto_20220322_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedCourse',
        ),
        migrations.DeleteModel(
            name='SavedProgram',
        ),
    ]
