# Generated by Django 4.2.18 on 2025-01-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embargo', '0002_data__add_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRestrictedCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(help_text='The country to be restricted.', on_delete=django.db.models.deletion.CASCADE, to='embargo.country', unique=True)),
            ],
            options={
                'verbose_name': 'Global Restricted Country',
                'verbose_name_plural': 'Global Restricted Countries',
            },
        ),
    ]
