"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('contentstore.management.commands.tests.test_generate_courses', 'cms.djangoapps.contentstore.management.commands.tests.test_generate_courses')

from cms.djangoapps.contentstore.management.commands.tests.test_generate_courses import *
