// Once generated by CoffeeScript 1.9.3, but now lives as pure JS
/* eslint-disable */
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.VerticalDescriptor = (function(superClass) {
    extend(VerticalDescriptor, superClass);

    function VerticalDescriptor() {
      return VerticalDescriptor.__super__.constructor.apply(this, arguments);
    }

    return VerticalDescriptor;

  })(XModule.Descriptor);

}).call(this);
