# Generated by Django 3.2.10 on 2021-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunixRelativeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('block_id', models.EmailField(max_length=255)),
                ('type', models.EmailField(max_length=255)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
