# Generated by Django 3.2.10 on 2021-12-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funix_relative_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funixrelativedate',
            name='block_id',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
