# Generated by Django 3.2.10 on 2021-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funix_relative_date', '0003_funixrelativedate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funixrelativedate',
            name='block_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funixrelativedate',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
