# Generated by Django 4.2.22 on 2025-06-16 23:39

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCoreCourseStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('structure', models.BinaryField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningcorecoursestructure',
            constraint=models.UniqueConstraint(models.F('course_key'), name='xblock_lccs_uniq_course_key'),
        ),
    ]
