# Generated by Django 4.2.22 on 2025-06-16 18:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBlockVersionFieldData',
            fields=[
                ('publishable_entity_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oel_publishing.publishableentityversion')),
                ('content', jsonfield.fields.JSONField(default=dict, help_text='XBlock content scope fields as JSON')),
                ('settings', jsonfield.fields.JSONField(default=dict, help_text='XBlock settings scope fields as JSON')),
            ],
            options={
                'verbose_name': 'XBlock Version Field Data',
                'verbose_name_plural': 'XBlock Version Field Data',
            },
        ),
    ]
