# Generated by Django 4.2.22 on 2025-06-20 02:05

from django.db import migrations, models
import openedx.core.djangoapps.xblock.models


class Migration(migrations.Migration):

    dependencies = [
        ('xblock_new', '0002_learningcorecoursestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xblockversionfielddata',
            name='definition_object_id',
            field=models.CharField(
                default=openedx.core.djangoapps.xblock.models.XBlockVersionFieldData.generate_object_id_str,
                max_length=24,
                null=True,
            ),
        ),
    ]
