# Generated by Django 4.2.22 on 2025-06-20 14:07

from django.db import migrations, models
import openedx.core.djangoapps.xblock.models


class Migration(migrations.Migration):

    dependencies = [
        ('xblock_new', '0004_generate_def_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name="XBlockVersionFieldData",
            name="definition_object_id",
            field=models.CharField(
                max_length=24,
                unique=True,
                null=False,
                default=openedx.core.djangoapps.xblock.models.XBlockVersionFieldData.generate_object_id_str,
            )
        )
    ]
