# Generated by Django 4.2.22 on 2025-06-21 02:57

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
        ('xblock_new', '0005_unique_def_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', opaque_keys.edx.django.models.UsageKeyField(max_length=255, unique=True)),
                ('children', models.JSONField(default=None, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentity')),
            ],
        ),
        migrations.CreateModel(
            name='LearningContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', opaque_keys.edx.django.models.LearningContextKeyField(max_length=255, unique=True)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xblock_new.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xblock_new.learningcontext'),
        ),
    ]
