# Generated by Django 4.2.22 on 2025-06-21 03:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xblock_new', '0006_block_learningcontext_block_learning_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='children',
        ),
        migrations.AddField(
            model_name='xblockversionfielddata',
            name='children',
            field=jsonfield.fields.JSONField(default=None, help_text='XBlock children scope fields as JSON'),
        ),
    ]
