# Generated by Django 4.2.22 on 2025-06-21 03:39

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('xblock_new', '0007_remove_block_children_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCoreLearningContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', opaque_keys.edx.django.models.LearningContextKeyField(max_length=255, unique=True)),
                ('use_learning_core', models.BooleanField(default=True)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xblock_new.block')),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xblock_new.learningcorelearningcontext'),
        ),
        migrations.DeleteModel(
            name='LearningContext',
        ),
    ]
