# Generated by Django 4.2.22 on 2025-06-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
        ('xblock_new', '0008_learningcorelearningcontext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentity'),
        ),
    ]
