# Generated by Django 4.2.22 on 2025-06-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xblock_new', '0009_alter_block_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='xblock_new.learningcorelearningcontext'),
        ),
    ]
