# Generated by Django 4.2.22 on 2025-06-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xblock_new', '0010_alter_block_learning_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcorelearningcontext',
            name='root',
        ),
    ]
