"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('course_wiki.plugins.markdownedx.mdx_video', 'lms.djangoapps.course_wiki.plugins.markdownedx.mdx_video')

from lms.djangoapps.course_wiki.plugins.markdownedx.mdx_video import *
