# Generated by Django 1.11.25 on 2019-10-22 14:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteam',
            name='discussion_topic_id',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='courseteam',
            name='team_id',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
