# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200318_1349'),
        ('teams', '0004_alter_defaults'),
    ]

    operations = [
    ]
