# Generated by Django 3.2.20 on 2023-07-11 22:57

from django.db import migrations
from django.core.management import call_command

def load_system_defined_taxonomies(apps, schema_editor):
    """
    Creates system defined taxonomies and loads tags
    """ 

    # Create system defined taxonomy instances
    call_command('loaddata', '--app=oel_tagging', 'system_defined.yaml')
    call_command('loaddata', '--app=content_tagging', 'system_defined.yaml')

    # Loads language tags
    call_command('loaddata', '--app=oel_tagging', 'language_taxonomy.yaml')


def revert_system_defined_taxonomies(apps, schema_editor):
    """
    Deletes all system defined taxonomies
    """
    Taxonomy = apps.get_model('oel_tagging', 'Taxonomy')
    Tag = apps.get_model('oel_tagging', 'Tag')

    # For some reason the tags are not deleted when deleting the taxonomy
    Tag.objects.filter(taxonomy__system_defined=True).delete()
    Taxonomy.objects.filter(system_defined=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content_tagging', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_system_defined_taxonomies, revert_system_defined_taxonomies),
    ]
