# Generated by Django 3.2.20 on 2023-07-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0003_auto_20230721_1238'),
        ('content_tagging', '0002_system_defined_taxonomies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAuthorTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.usersystemdefinedtaxonomy',),
        ),
        migrations.CreateModel(
            name='ContentLanguageTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.languagetaxonomy',),
        ),
        migrations.CreateModel(
            name='OrganizarionSystemDefinedTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.modelsystemdefinedtaxonomy',),
        ),
        migrations.CreateModel(
            name='OrganizationModelObjectTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.modelobjecttag',),
        ),
        migrations.CreateModel(
            name='ContentOrganizationTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content_tagging.organizarionsystemdefinedtaxonomy',),
        ),
    ]
