# Generated by Django 3.2.20 on 2023-07-11 22:57

from django.db import migrations
from django.core.management import call_command
from openedx.features.content_tagging.models import ContentLanguageTaxonomy


def load_system_defined_taxonomies(apps, schema_editor):
    """
    Creates system defined taxonomies
    """ 

    # Create system defined taxonomy instances
    call_command('loaddata', '--app=content_tagging', 'system_defined.yaml')

    # Adding taxonomy class to the language taxonomy
    Taxonomy = apps.get_model('oel_tagging', 'Taxonomy')
    language_taxonomy = Taxonomy.objects.get(id=-1)
    language_taxonomy.taxonomy_class = ContentLanguageTaxonomy


def revert_system_defined_taxonomies(apps, schema_editor):
    """
    Deletes all system defined taxonomies
    """
    Taxonomy = apps.get_model('oel_tagging', 'Taxonomy')
    Taxonomy.objects.get(id=-2).delete()
    Taxonomy.objects.get(id=-3).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content_tagging', '0002_system_defined_taxonomies'),
    ]

    operations = [
        migrations.RunPython(load_system_defined_taxonomies, revert_system_defined_taxonomies),
    ]
