# Generated by Django 3.2.20 on 2023-07-11 22:57

from django.db import migrations


def load_system_defined_taxonomies(apps, schema_editor):
    """
    Creates system defined taxonomies
    """

    # Create system defined taxonomy instances
    Taxonomy = apps.get_model("oel_tagging", "Taxonomy")
    author_taxonomy = Taxonomy(
        pk=-2,
        name="Content Authors",
        description="Allows tags for any user ID created on the instance.",
        enabled=True,
        required=True,
        allow_multiple=False,
        allow_free_text=False,
        visible_to_authors=False,
    )
    ContentAuthorTaxonomy = apps.get_model("content_tagging", "ContentAuthorTaxonomy")
    author_taxonomy.taxonomy_class = ContentAuthorTaxonomy
    author_taxonomy.save()

    org_taxonomy = Taxonomy(
        pk=-3,
        name="Organizations",
        description="Allows tags for any organization ID created on the instance.",
        enabled=True,
        required=True,
        allow_multiple=False,
        allow_free_text=False,
        visible_to_authors=False,
    )
    ContentOrganizationTaxonomy = apps.get_model("content_tagging", "ContentOrganizationTaxonomy")
    org_taxonomy.taxonomy_class = ContentOrganizationTaxonomy
    org_taxonomy.save()

    # Adding taxonomy class to the language taxonomy
    language_taxonomy = Taxonomy.objects.get(id=-1)
    ContentLanguageTaxonomy = apps.get_model("content_tagging", "ContentLanguageTaxonomy")
    language_taxonomy.taxonomy_class = ContentLanguageTaxonomy
    language_taxonomy.save()


def revert_system_defined_taxonomies(apps, schema_editor):
    """
    Deletes all system defined taxonomies
    """
    Taxonomy = apps.get_model("oel_tagging", "Taxonomy")
    Taxonomy.objects.get(id=-2).delete()
    Taxonomy.objects.get(id=-3).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content_tagging", "0002_system_defined_taxonomies"),
    ]

    operations = [
        migrations.RunPython(load_system_defined_taxonomies, revert_system_defined_taxonomies),
    ]
