// Once generated by CoffeeScript 1.9.3, but now lives as pure JS
/* eslint-disable */
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.JSONEditingDescriptor = (function(superClass) {
    extend(JSONEditingDescriptor, superClass);

    function JSONEditingDescriptor(element) {
      this.element = element;
      this.edit_box = CodeMirror.fromTextArea($(".edit-box", this.element)[0], {
        mode: {
          name: "javascript",
          json: true
        },
        lineNumbers: true,
        lineWrapping: true
      });
    }

    JSONEditingDescriptor.prototype.save = function() {
      return {
        data: JSON.parse(this.edit_box.getValue())
      };
    };

    return JSONEditingDescriptor;

  })(XModule.Descriptor);

}).call(this);
