# Generated by Django 4.2.16 on 2024-11-15 12:40

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalIndexCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(max_length=255, unique=True)),
            ],
        ),
    ]
