"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('static_replace.management.commands.clear_collectstatic_cache', 'common.djangoapps.static_replace.management.commands.clear_collectstatic_cache')

from common.djangoapps.static_replace.management.commands.clear_collectstatic_cache import *
