# Generated by Django 3.2.21 on 2023-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_provider', '0003_auto_20161118_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='auto_link_users_using_email',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
