# Generated by Django 4.2.23 on 2025-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_provider', '0004_require_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='use_lti_pii',
            field=models.BooleanField(blank=True, default=False, help_text='When checked, the platform will automatically use any personal information provided via LTI to create an account. Otherwise an anonymous account will be created.'),
        ),
    ]
