# Generated by Django 2.2.17 on 2021-06-16 05:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openedx.adg.lms.applications.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('logo', models.ImageField(help_text='Accepted extensions: .png, .jpg, .svg', upload_to='business-lines/logos/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'svg')), openedx.adg.lms.applications.helpers.validate_logo_size], verbose_name='Logo')),
                ('description', models.TextField(verbose_name='Description')),
                ('site_url', models.URLField(default='', verbose_name='Site URL')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_line', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organization')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, verbose_name='LinkedIn URL')),
                ('interest_in_business', models.TextField(blank=True, verbose_name='Why are you interested in this business line?')),
                ('is_work_experience_not_applicable', models.BooleanField(default=False, verbose_name='Work Experience Not Applicable')),
                ('background_question', models.TextField(blank=True, verbose_name='Background Question')),
                ('status', models.CharField(choices=[('open', 'Open'), ('waitlist', 'Waitlist'), ('accepted', 'Accepted')], default='open', max_length=8, verbose_name='Application Status')),
                ('internal_admin_note', models.TextField(blank=True, verbose_name='Admin Note')),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.BusinessLine', verbose_name='Business Line')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_started_month', models.IntegerField(choices=[(None, 'Month'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Start Month')),
                ('date_completed_month', models.IntegerField(blank=True, choices=[(None, 'Month'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Completed Month')),
                ('date_started_year', models.IntegerField(validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Start Year')),
                ('date_completed_year', models.IntegerField(blank=True, null=True, validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Completed Year')),
                ('name_of_organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('job_position_title', models.CharField(max_length=255, verbose_name='Job Position / Title')),
                ('is_current_position', models.BooleanField(default=False, verbose_name='Current Position')),
                ('job_responsibilities', models.TextField(verbose_name='Job Responsibilities')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_workexperiences', related_query_name='applications_workexperience', to='applications.UserApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.CharField(max_length=255, verbose_name='Job Position / Title')),
                ('relationship', models.CharField(max_length=255, verbose_name='Relationship to you')),
                ('phone_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers.', regex='^\\+?1?\\d*$')])),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', related_query_name='reference', to='applications.UserApplication')),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualCourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course group name')),
                ('is_program_prerequisite', models.BooleanField(default=False, verbose_name='Is Prerequisite for the Program')),
                ('is_common_business_line_prerequisite', models.BooleanField(default=False, verbose_name='Is Common Prerequisite for all Business Lines')),
                ('business_line_prerequisite', models.ForeignKey(blank=True, default=None, help_text='Select the Business Line that this Course Group is a prerequisite for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_courses', related_query_name='prerequisite_course', to='applications.BusinessLine', verbose_name='Is Prerequisite for Business Line')),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multilingual_course', to='course_overviews.CourseOverview', verbose_name='Multilingual version of a course')),
                ('multilingual_course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multilingual_courses', to='applications.MultilingualCourseGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_started_month', models.IntegerField(choices=[(None, 'Month'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Start Month')),
                ('date_completed_month', models.IntegerField(blank=True, choices=[(None, 'Month'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Completed Month')),
                ('date_started_year', models.IntegerField(validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Start Year')),
                ('date_completed_year', models.IntegerField(blank=True, null=True, validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Completed Year')),
                ('name_of_school', models.CharField(max_length=255, verbose_name='School / University')),
                ('degree', models.CharField(choices=[('HD', 'High School Diploma or GED'), ('AD', 'Associate Degree'), ('BD', 'Bachelor’s Degree'), ('MD', 'Master’s Degree'), ('DD', 'Doctoral Degree')], max_length=2, verbose_name='Degree Received')),
                ('area_of_study', models.CharField(blank=True, max_length=255, verbose_name='Area of Study')),
                ('is_in_progress', models.BooleanField(default=False, verbose_name='In Progress')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_educations', related_query_name='applications_education', to='applications.UserApplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_prerequisite_courses_passed', models.BooleanField(default=False, verbose_name='Prerequisite Courses Passed')),
                ('is_bu_prerequisite_courses_passed', models.BooleanField(default=False, verbose_name='Business Unit Prerequisite Courses Passed')),
                ('is_written_application_completed', models.BooleanField(default=False, verbose_name='Written Application Submitted')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_hub', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
