# Generated by Django 2.2.15 on 2020-12-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_user_application_update_business_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhub',
            name='is_written_application_completed',
            field=models.BooleanField(default=False, verbose_name='Written Application Submitted'),
        ),
        migrations.AddField(
            model_name='applicationhub',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submission Date'),
        ),
    ]
