# Generated by Django 2.2.15 on 2020-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_user_application_update_business_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='ares_of_study',
            new_name='area_of_study',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_responsibilities',
            field=models.TextField(verbose_name='Job Responsibilities'),
        ),
    ]
