# Generated by Django 2.2.17 on 2021-02-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_prerequisitecourse_prerequisitecoursegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='is_work_experience_not_applicable',
            field=models.BooleanField(default=False, verbose_name='Work Experience Not Applicable'),
        ),
    ]
