# Generated by Django 2.2.17 on 2021-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_prerequisitecourse_prerequisitecoursegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='internal_admin_note',
            field=models.TextField(blank=True, default='', verbose_name='Admin Note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waitlist', 'Waitlist'), ('accepted', 'Accepted')], default='open', max_length=8, verbose_name='Application Status'),
        ),
    ]
