# Generated by Django 2.2.17 on 2021-02-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('applications', '0005_userapplication_is_work_experience_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessline',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_line', to='auth.Group'),
        ),
    ]
