# Generated by Django 2.2.15 on 2021-01-07 12:50

from django.db import migrations, models
import openedx.adg.lms.applications.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20201214_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_completed_year',
            field=models.IntegerField(blank=True, null=True, validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Completed Year'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started_year',
            field=models.IntegerField(validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Start Year'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_completed_year',
            field=models.IntegerField(blank=True, null=True, validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Completed Year'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_started_year',
            field=models.IntegerField(validators=[openedx.adg.lms.applications.helpers.min_year_value_validator, openedx.adg.lms.applications.helpers.max_year_value_validator], verbose_name='Start Year'),
        ),
    ]
