# Generated by Django 2.2.15 on 2021-01-11 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20210107_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapplication',
            options={'ordering': ['created'], 'verbose_name': 'Application'},
        ),
        migrations.AddField(
            model_name='userapplication',
            name='internal_admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Note'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name_of_school',
            field=models.CharField(max_length=255, verbose_name='School / University'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Accepted extensions: .pdf, .doc, .jpg, .png', max_length=500, null=True, upload_to='files/resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'jpg', 'png'])], verbose_name='Resume File'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='name_of_organization',
            field=models.CharField(max_length=255, verbose_name='Organization'),
        ),
        migrations.DeleteModel(
            name='AdminNote',
        ),
    ]
