# Generated by Django 2.2.17 on 2021-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20210226_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessline',
            name='site_url',
            field=models.URLField(default='', verbose_name='Site URL'),
        ),
    ]
