# Generated by Django 2.2.17 on 2021-05-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20210310_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilingualcoursegroup',
            name='business_line_prerequisite',
            field=models.ForeignKey(blank=True, default=None, help_text='Select the Business Line that this Course Group is a prerequisite for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_courses', related_query_name='prerequisite_course', to='applications.BusinessLine', verbose_name='Is Prerequisite for Business Line'),
        ),
        migrations.AddField(
            model_name='multilingualcoursegroup',
            name='is_common_business_line_prerequisite',
            field=models.BooleanField(default=False, verbose_name='Is Common Prerequisite for all Business Lines'),
        ),
        migrations.AlterField(
            model_name='multilingualcoursegroup',
            name='is_prerequisite',
            field=models.BooleanField(default=False, verbose_name='Is Prerequisite for the Program'),
        ),
        migrations.RenameField(
            model_name='multilingualcoursegroup',
            old_name='is_prerequisite',
            new_name='is_program_prerequisite',
        ),
    ]
