# Generated by Django 2.2.17 on 2021-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20210520_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhub',
            name='is_bu_prerequisite_courses_passed',
            field=models.BooleanField(default=False, verbose_name='Business Unit Prerequisite Courses Passed'),
        ),
    ]
