# Generated by Django 2.2.17 on 2021-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_applicationhub_is_bu_prerequisite_courses_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='cover_letter_file',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='userapplication',
            name='background_question',
            field=models.TextField(blank=True, verbose_name='Background Question'),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='interest_in_business',
            field=models.TextField(blank=True, verbose_name='Why are you interested in this business line?'),
        ),
    ]
