# Generated by Django 2.2.17 on 2021-06-02 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_applicationhub_is_bu_prerequisite_courses_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.CharField(max_length=255, verbose_name='Job Position / Title')),
                ('relationship', models.CharField(max_length=255, verbose_name='Relationship to you')),
                ('phone_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers.', regex='^\\+?1?\\d*$')])),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('user_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', related_query_name='reference', to='applications.UserApplication')),
            ],
        ),
    ]
