# Generated by Django 2.2.17 on 2021-06-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_applicationhub_is_bu_prerequisite_courses_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationhub',
            name='is_application_submitted',
        ),
    ]
