# Generated by Django 2.2.17 on 2021-06-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20210602_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationhub',
            name='is_application_submitted',
        ),
    ]
