# Generated by Django 2.2.16 on 2021-05-19 13:07

from django.db import migrations
from django.contrib.auth.models import Group
from ..constants import GROUP_TRAINING_MANAGERS


def apply_migration(apps, schema_editor):
    if not Group.objects.filter(name=GROUP_TRAINING_MANAGERS):
        Group.objects.create(name=GROUP_TRAINING_MANAGERS)


def revert_migration(apps, schema_editor):
    Group.objects.filter(name=GROUP_TRAINING_MANAGERS).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
