# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-14 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
