# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-29 16:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import functools
import openedx.features.idea.helpers
import openedx.features.philu_utils.backend_storage


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20200421_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(verbose_name='Idea Description'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, help_text='Accepted extensions: .docx, .pdf, .txt (maximum 4 MB)', null=True, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=functools.partial(openedx.features.idea.helpers.upload_to_path, *(), **{b'folder': 'files'}), validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf', 'txt'])], verbose_name='ADD FILE'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, help_text='Accepted extensions: .jpg, .png (maximum 2 MB)', null=True, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=functools.partial(openedx.features.idea.helpers.upload_to_path, *(), **{b'folder': 'images'}), validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='ADD IMAGE'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='implementation',
            field=models.TextField(blank=True, verbose_name='Have you tried to implement this idea?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='organization_mission',
            field=models.TextField(verbose_name='Organization Mission'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='overview',
            field=models.CharField(max_length=150, verbose_name='Idea Overview'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Idea Title'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='VIDEO LINK'),
        ),
    ]
