# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-15 08:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import openedx.features.philu_utils.backend_storage
import util.philu_utils


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20200429_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, help_text='Accepted extensions: .docx, .pdf, .txt (maximum 4 MB)', max_length=500, null=True, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, path='files'), validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf', 'txt'])], verbose_name='ADD FILE'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, help_text='Accepted extensions: .jpg, .png (maximum 2 MB)', max_length=500, null=True, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, name_prefix='image', path='images'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='ADD IMAGE'),
        ),
    ]
