# Generated by Django 3.2.11 on 2022-01-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('hours_per_day', models.FloatField(default=2.5)),
                ('weekday_0', models.BooleanField(default=True)),
                ('weekday_1', models.BooleanField(default=True)),
                ('weekday_2', models.BooleanField(default=True)),
                ('weekday_3', models.BooleanField(default=True)),
                ('weekday_4', models.BooleanField(default=True)),
                ('weekday_5', models.BooleanField(default=False)),
                ('weekday_6', models.BooleanField(default=False)),
            ],
        ),
    ]
