# Generated by Django 4.2.20 on 2025-05-14 17:31

from django.db import migrations, models
import django.db.models.deletion
from openedx.core.djangoapps.content_libraries.api import ContainerType


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0004_url_textfield'),
        ('import_from_modulestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='created',
        ),
        migrations.RemoveField(
            model_name='import',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='import',
            name='status',
        ),
        migrations.RemoveField(
            model_name='import',
            name='uuid',
        ),
        migrations.AddField(
            model_name='import',
            name='composition_level',
            field=models.CharField(choices=[(ContainerType['Section'], 'CHAPTER'), (ContainerType['Subsection'], 'SEQUENTIAL'), (ContainerType['Unit'], 'VERTICAL'), ('component', 'COMPONENT')], default='component', help_text='The composition level of the target learning package', max_length=255),
        ),
        migrations.AddField(
            model_name='import',
            name='override',
            field=models.BooleanField(default=False, help_text='If true, the import will override any existing content in the target learning package.'),
        ),
        migrations.AddField(
            model_name='import',
            name='user_task_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_event', to='user_tasks.usertaskstatus'),
        ),
    ]
