# Generated by Django 4.2.20 on 2025-04-23 09:52

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0004_url_textfield'),
        ('import_from_modulestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='status',
        ),
        migrations.RemoveField(
            model_name='import',
            name='user',
        ),
        migrations.RemoveField(
            model_name='import',
            name='uuid',
        ),
        migrations.AddField(
            model_name='import',
            name='composition_level',
            field=models.CharField(choices=[('component', 'Component'), ('unit', 'Unit'), ('subsection', 'Subsection'), ('section', 'Section')], default='component', max_length=64),
        ),
        migrations.AddField(
            model_name='import',
            name='override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='import',
            name='target_key',
            field=opaque_keys.edx.django.models.LearningContextKeyField(blank=True, db_index=True, help_text='Target library key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='user_task_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_event', to='user_tasks.usertaskstatus'),
        ),
        migrations.AlterField(
            model_name='import',
            name='source_key',
            field=opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, help_text='Source course key', max_length=255),
        ),
    ]
