# Generated by Django 4.2.23 on 2025-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_from_modulestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('not_started', 'Waiting to stage content'), ('staging', 'Staging content for import'), ('staging_failed', 'Failed to stage content'), ('staged', 'Content is staged and ready for import'), ('importing', 'Importing staged content'), ('importing_failed', 'Failed to import staged content'), ('imported', 'Successfully imported content'), ('canceled', 'Canceled')], db_index=True, default='not_started', max_length=100),
        ),
    ]
