# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0012_historicalcoursemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modes', to='course_overviews.CourseOverview'),
        ),
    ]
