# Generated by Django 2.2.18 on 2021-02-04 16:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0013_auto_20200115_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemode',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='coursemodesarchive',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AddField(
            model_name='historicalcoursemode',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30, verbose_name='Price'),
        ),
    ]
