# Generated by Django 3.2.13 on 2022-05-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0013_auto_20200115_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcoursemode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course mode', 'verbose_name_plural': 'historical course modes'},
        ),
    ]
