# Generated by Django 3.2.18 on 2023-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0014_auto_20230207_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='expiration_datetime_is_explicit',
            field=models.BooleanField(default=False, help_text='OPTIONAL: Set to True to lock in the explicitly defined upgrade deadline date. Set to False if there is no upgrade deadline or to use the default upgrade deadline.', verbose_name='Lock upgrade deadline date'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='expiration_datetime_is_explicit',
            field=models.BooleanField(default=False, help_text='OPTIONAL: Set to True to lock in the explicitly defined upgrade deadline date. Set to False if there is no upgrade deadline or to use the default upgrade deadline.', verbose_name='Lock upgrade deadline date'),
        ),
    ]
