# Generated by Django 3.2.21 on 2023-10-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('content_tagging', '0001_initial'),
        ('content_tagging', '0002_system_defined_taxonomies'),
        ('content_tagging', '0003_system_defined_fixture'),
        ('content_tagging', '0004_system_defined_org'),
        ('content_tagging', '0005_auto_20230830_1517'),
        ('content_tagging', '0006_simplify_models'),
    ]

    initial = True

    dependencies = [
        ("oel_tagging", "0001_squashed"),
        ('organizations', '0003_historicalorganizationcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentObjectTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.objecttag',),
        ),
        migrations.CreateModel(
            name='TaxonomyOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(choices=[('OWN', 'owner')], default='OWN', max_length=3)),
                ('org', models.ForeignKey(default=None, help_text='Organization that is related to this taxonomy.If None, then this taxonomy is related to all organizations.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_tagging.taxonomy')),
            ],
        ),
        migrations.AddIndex(
            model_name='taxonomyorg',
            index=models.Index(fields=['taxonomy', 'rel_type'], name='content_tag_taxonom_b04dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyorg',
            index=models.Index(fields=['taxonomy', 'rel_type', 'org'], name='content_tag_taxonom_70d60b_idx'),
        ),
    ]
