# Generated by Django 3.2.20 on 2023-07-31 21:07

from django.db import migrations
import openedx.core.djangoapps.content_tagging.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0005_language_taxonomy'),
        ('content_tagging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAuthorTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(openedx.core.djangoapps.content_tagging.models.base.ContentTaxonomyMixin, 'oel_tagging.usersystemdefinedtaxonomy'),
        ),
        migrations.CreateModel(
            name='ContentLanguageTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(openedx.core.djangoapps.content_tagging.models.base.ContentTaxonomyMixin, 'oel_tagging.languagetaxonomy'),
        ),
        migrations.CreateModel(
            name='ContentOrganizationTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(openedx.core.djangoapps.content_tagging.models.base.ContentTaxonomyMixin, 'oel_tagging.modelsystemdefinedtaxonomy'),
        ),
        migrations.CreateModel(
            name='OrganizationModelObjectTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.modelobjecttag',),
        ),
    ]
