# Generated by Django 4.2.6 on 2023-12-01 12:32

from django.db import migrations, models
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0005_trim_leading_slashes_in_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockstructuremodel',
            name='staff_visibility',
            field=models.BooleanField(default=False, verbose_name='Indicates block structure data is stored with blocks only visible to staff'),
        ),
        migrations.AlterField(
            model_name='blockstructuremodel',
            name='data_usage_key',
            field=openedx.core.djangoapps.xmodule_django.models.UsageKeyWithRunField(max_length=255, verbose_name='Identifier of the data being collected.'),
        ),
        migrations.AlterUniqueTogether(
            name='blockstructuremodel',
            unique_together={('data_usage_key', 'staff_visibility')},
        ),
    ]
