# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermanagerrole',
            options={'ordering': ['manager_user']},
        ),
        migrations.AlterField(
            model_name='usermanagerrole',
            name='unregistered_manager_email',
            field=models.EmailField(blank=True, help_text=b"The email address for a manager if they haven't currently registered for an account.", max_length=254, null=True),
        ),
    ]
