# Generated by Django 3.2.13 on 2022-04-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_task', '0004_historicalinstructortaskschedule_instructortaskschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructortaskschedule',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='instructor_task.instructortask'),
        ),
    ]
