# Generated by Django 2.2.25 on 2022-06-23 11:50

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    replaces = [('genplus_learning', '0002_unit'), ('genplus_learning', '0003_auto_20220622_1440'), ('genplus_learning', '0004_remove_unit_is_locked')]

    dependencies = [
        ('genplus_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeargroup',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='yeargroup',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('year_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='genplus_learning.YearGroup')),
            ],
        ),
    ]
