# Generated by Django 2.2.25 on 2022-12-07 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genplus_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='intro_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_unit_program', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='program',
            name='outro_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outro_unit_program', to='course_overviews.CourseOverview'),
        ),
        migrations.CreateModel(
            name='ProgramAccessRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=64)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_learning.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program', 'role')},
            },
        ),
    ]
