# Generated by Django 2.2.25 on 2022-08-18 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import openedx.features.genplus_features.genplus_learning.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genplus_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.FloatField(validators=[openedx.features.genplus_features.genplus_learning.models.validate_percent])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_key')},
            },
        ),
        migrations.CreateModel(
            name='UnitBlockCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('block_type', models.CharField(max_length=64)),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.FloatField(validators=[openedx.features.genplus_features.genplus_learning.models.validate_percent])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_key', 'usage_key')},
            },
        ),
    ]
