# Generated by Django 2.2.25 on 2022-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_image',
            field=models.ImageField(blank=True, default='', upload_to='unit_images'),
        ),
    ]
