# Generated by Django 2.2.25 on 2022-08-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0004_skill_image'),
        ('genplus_learning', '0002_unitblockcompletion_unitcompletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='program',
            name='is_current',
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('active', 'active'), ('retired', 'retired')], default='unpublished', max_length=16),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('active', 'active'), ('retired', 'retired')], default='unpublished', max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Skill'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
