# Generated by Django 2.2.25 on 2022-09-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0006_auto_20220830_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='classunit',
            options={'ordering': ['unit__order']},
        ),
    ]
