# Generated by Django 2.2.25 on 2022-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0007_auto_20220915_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='banner_image',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='banner_image',
            field=models.ImageField(default='', upload_to='program_banner_images'),
        ),
    ]
