"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('courseware.tests.test_discussion_xblock', 'lms.djangoapps.courseware.tests.test_discussion_xblock')

from lms.djangoapps.courseware.tests.test_discussion_xblock import *
