# Generated by Django 1.11.8 on 2018-01-30 17:38


import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_remove_certificategenerationcoursesetting_enabled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='generatedcertificate',
            managers=[
                ('eligible_certificates', django.db.models.manager.Manager()),
            ],
        ),
    ]
