# Generated by Django 2.2.18 on 2021-02-18 22:05

from django.db import migrations


class Migration(migrations.Migration):
    """
    Delete all existing AllowListGenerationConfiguration entries because they may contain PII prior to this change
    """

    def remove_existing_configs(apps, schema_editor):
        AllowListGenerationConfiguration = apps.get_model('certificates', 'AllowListGenerationConfiguration')
        AllowListGenerationConfiguration.objects.all().delete()

    dependencies = [
        ('certificates', '0019_allowlistgenerationconfiguration'),
    ]

    operations = [
        migrations.RunPython(remove_existing_configs)
    ]
