# Generated by Django 2.2.19 on 2021-03-12 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0021_remove_certificate_allowlist_duplicate_records'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificatewhitelist',
            unique_together={('course_id', 'user')},
        ),
    ]
