# Generated by Django 2.2.19 on 2021-04-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0023_certificategenerationcommandconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowListGenerationConfiguration',
        ),
    ]
