# Generated by Django 2.2.20 on 2021-06-15 20:33

from django.core.paginator import Paginator
from django.db import migrations


class Migration(migrations.Migration):
    """
    Copy data from the CertificateWhitelist to the CertificateAllowlist
    """
    def copy_to_allowlist(apps, schema_editor):
        CertificateWhitelist = apps.get_model('certificates', 'CertificateWhitelist')
        CertificateAllowlist = apps.get_model('certificates', 'CertificateAllowlist')

        whitelisted = CertificateWhitelist.objects.all().order_by('id')
        paginator = Paginator(whitelisted, 1000)

        for page_num in paginator.page_range:
            page = paginator.page(page_num)

            for w in page.object_list:
                CertificateAllowlist.objects.update_or_create(
                    user_id=w.user_id,
                    course_id=w.course_id,
                    defaults={
                        'allowlist': w.whitelist,
                        'notes': w.notes,
                    }
                )

    dependencies = [
        ('certificates', '0027_historicalcertificateallowlist'),
    ]

    operations = [
        migrations.RunPython(copy_to_allowlist, reverse_code=migrations.RunPython.noop)
    ]

