# Generated by Django 2.2.20 on 2021-06-15 20:33

from django.core.paginator import Paginator
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0027_historicalcertificateallowlist'),
    ]

    operations = [
        # Note: this migration has been superseded by 0029 and is a no-op
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]

