# Generated by Django 2.2.24 on 2021-08-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0030_delete_certificatewhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCertificateDateOverride',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='The date to display on the certificate')),
                ('reason', models.TextField(help_text='The reason why you are overriding the certificate date (Update this when you add OR edit the date.)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('generated_certificate', models.ForeignKey(blank=True, db_constraint=False, help_text='The id of the Generated Certificate to override', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certificates.GeneratedCertificate')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('overridden_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The last person to save this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical certificate date override',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CertificateDateOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(help_text='The date to display on the certificate')),
                ('reason', models.TextField(help_text='The reason why you are overriding the certificate date (Update this when you add OR edit the date.)')),
                ('generated_certificate', models.OneToOneField(help_text='The id of the Generated Certificate to override', on_delete=django.db.models.deletion.CASCADE, related_name='date_override', to='certificates.GeneratedCertificate')),
                ('overridden_by', models.ForeignKey(help_text='The last person to save this record', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
