# Generated by Django 3.2.12 on 2022-02-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0032_change_certificatedateoverride_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='mode',
            field=models.CharField(blank=True, choices=[('verified', 'verified'), ('honor', 'honor'), ('audit', 'audit'), ('professional', 'professional'), ('no-id-professional', 'no-id-professional'), ('masters', 'masters'), ('executive-education', 'executive-education'), ('executive-program', 'executive-program')], default='honor', help_text='The course mode for this template.', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='mode',
            field=models.CharField(choices=[('verified', 'verified'), ('honor', 'honor'), ('audit', 'audit'), ('professional', 'professional'), ('no-id-professional', 'no-id-professional'), ('masters', 'masters'), ('executive-education', 'executive-education'), ('executive-program', 'executive-program')], default='honor', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalgeneratedcertificate',
            name='mode',
            field=models.CharField(choices=[('verified', 'verified'), ('honor', 'honor'), ('audit', 'audit'), ('professional', 'professional'), ('no-id-professional', 'no-id-professional'), ('masters', 'masters'), ('executive-education', 'executive-education'), ('executive-program', 'executive-program')], default='honor', max_length=32),
        ),
    ]
