INTRO_TO_COMPUTING = 'Introduction to computing'
PROGRAMMING = 'Programming'
OOP = 'Object oriented programming'
DATA_STRUCTURES = 'Data Structures'
COMPUTER_ORG_ASSEMBLY_LANG = 'Computer Organization and Assembly Language'
SOFTWARE_ENGINEERING = 'Software Engineering'
COMPUTER_NETWORKS = 'Computer networks'
AI = 'Artificial intelligence'
DATABASES = 'Databases'
OS = 'Operating System'
ALGORITHMS = 'Algorithms'
BIO_INFORMATICS = 'Bio-Informatics'
OTHER = 'Other'

PYTHON_DJANGO = 'Python/Django'
SCRAPPY_DATASCIENCE = 'Scrappy/Data Science'
ANDROID = 'Android'
IOS = 'iOS'
PHP = 'PHP'
JAVASCRIPT = 'Javascript'

STUDIED_COURSES = (
    (INTRO_TO_COMPUTING, INTRO_TO_COMPUTING),
    (PROGRAMMING, PROGRAMMING),
    (OOP, OOP),
    (DATA_STRUCTURES, DATA_STRUCTURES),
    (COMPUTER_ORG_ASSEMBLY_LANG, COMPUTER_ORG_ASSEMBLY_LANG),
    (SOFTWARE_ENGINEERING, SOFTWARE_ENGINEERING),
    (COMPUTER_NETWORKS, COMPUTER_NETWORKS),
    (AI, AI),
    (DATABASES, DATABASES),
    (OS, OS),
    (ALGORITHMS, ALGORITHMS),
    (BIO_INFORMATICS, BIO_INFORMATICS),
    (OTHER, OTHER),
)

EXPERTISE = (
    (INTRO_TO_COMPUTING, INTRO_TO_COMPUTING),
    (PROGRAMMING, PROGRAMMING),
    (OOP, OOP),
    (DATA_STRUCTURES, DATA_STRUCTURES),
    (COMPUTER_ORG_ASSEMBLY_LANG, COMPUTER_ORG_ASSEMBLY_LANG),
    (SOFTWARE_ENGINEERING, SOFTWARE_ENGINEERING),
    (COMPUTER_NETWORKS, COMPUTER_NETWORKS),
    (AI, AI),
    (DATABASES, DATABASES),
    (OS, OS),
    (ALGORITHMS, ALGORITHMS),
    (BIO_INFORMATICS, BIO_INFORMATICS),
)

TECHNOLOGIES = (
    (PYTHON_DJANGO, PYTHON_DJANGO),
    (SCRAPPY_DATASCIENCE, SCRAPPY_DATASCIENCE),
    (ANDROID, ANDROID),
    (IOS, IOS),
    (PHP, PHP),
    (JAVASCRIPT, JAVASCRIPT),
    (OTHER, OTHER),
)

EXPERTISE_RANKING = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
)
