# Generated by Django 2.2.12 on 2020-04-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('entitlements', '0001_initial'),
        ('course_overviews', '0020_courseoverviewtab_url_slug'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcourseentitlement',
            name='enrollment_course_run',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The current Course enrollment for this entitlement. If NULL the Learner has not enrolled.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student.CourseEnrollment'),
        ),
        migrations.AddField(
            model_name='historicalcourseentitlement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcourseentitlement',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseentitlementsupportdetail',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitlements.CourseEntitlement'),
        ),
        migrations.AddField(
            model_name='courseentitlementsupportdetail',
            name='support_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseentitlementsupportdetail',
            name='unenrolled_run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_overviews.CourseOverview'),
        ),
        migrations.AddField(
            model_name='courseentitlementpolicy',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='courseentitlement',
            name='_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entitlements.CourseEntitlementPolicy'),
        ),
        migrations.AddField(
            model_name='courseentitlement',
            name='enrollment_course_run',
            field=models.ForeignKey(blank=True, help_text='The current Course enrollment for this entitlement. If NULL the Learner has not enrolled.', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.CourseEnrollment'),
        ),
        migrations.AddField(
            model_name='courseentitlement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseentitlement',
            unique_together={('course_uuid', 'order_number')},
        ),
    ]
