# Generated by Django 1.11.26 on 2019-12-17 14:08


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):  # lint-amnesty, pylint: disable=missing-class-docstring

    dependencies = [
        ('course_overviews', '0017_auto_20191002_0823'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entitlements', '0012_allow_blank_order_number_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCourseEntitlementSupportDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),  # lint-amnesty, pylint: disable=line-too-long
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),  # lint-amnesty, pylint: disable=line-too-long
                ('reason', models.CharField(choices=[('LEAVE', 'Learner requested leave session for expired entitlement'), ('CHANGE', 'Learner requested session change for expired entitlement'), ('LEARNER_NEW', 'Learner requested new entitlement'), ('COURSE_TEAM_NEW', 'Course team requested entitlement for learnerg'), ('OTHER', 'Other')], max_length=15)),  # lint-amnesty, pylint: disable=line-too-long
                ('action', models.CharField(choices=[('REISSUE', 'Re-issue entitlement'), ('CREATE', 'Create new entitlement')], max_length=15)),  # lint-amnesty, pylint: disable=line-too-long
                ('comments', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),  # lint-amnesty, pylint: disable=line-too-long
                ('entitlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entitlements.CourseEntitlement')),  # lint-amnesty, pylint: disable=line-too-long
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),  # lint-amnesty, pylint: disable=line-too-long
                ('support_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),  # lint-amnesty, pylint: disable=line-too-long
                ('unenrolled_run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_overviews.CourseOverview')),  # lint-amnesty, pylint: disable=line-too-long
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical course entitlement support detail',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
