# Generated by Django 1.11.27 on 2020-01-15 20:22


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # lint-amnesty, pylint: disable=missing-class-docstring

    dependencies = [
        ('entitlements', '0013_historicalcourseentitlementsupportdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentitlementsupportdetail',
            name='unenrolled_run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_overviews.CourseOverview'),  # lint-amnesty, pylint: disable=line-too-long
        ),
    ]
