# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 10:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0014_auto_20200115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentitlement',
            name='order_number',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourseentitlement',
            name='order_number',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseentitlement',
            unique_together=set([('course_uuid', 'order_number')]),
        ),
    ]
