# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0019_auto_20181221_0540'),
        ('sites', '0002_alter_domain_unique'),
        ('subscriptions', '0002_add_lms_site_to_user_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subscription_id', models.PositiveIntegerField()),
                ('expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('subscription_type', models.CharField(choices=[(b'limited-access', b'Limited Access'), (b'full-access-courses', b'Full Access (Courses)'), (b'full-access-time-period', b'Full Access (Time period)'), (b'lifetime-access', b'Lifetime Access')], max_length=30)),
                ('max_allowed_courses', models.PositiveIntegerField(blank=True, help_text='Maximum number of courses allowed to enroll in paid tracks using the subscription.', null=True)),
                ('course_enrollments', models.ManyToManyField(blank=True, to='student.CourseEnrollment')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
    ]
