# Generated by Django 2.2.25 on 2022-11-29 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_id', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('problem_id', models.CharField(max_length=64)),
                ('assessment_time', models.CharField(max_length=64)),
                ('rating', models.IntegerField(db_index=True, default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'User Rating Responses',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('usage_id', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('problem_id', models.CharField(max_length=64)),
                ('assessment_time', models.CharField(max_length=64)),
                ('student_response', models.TextField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('gen_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Class')),
            ],
            options={
                'verbose_name': 'User Text Responses',
            },
        ),
    ]
