# Generated by Django 2.2.25 on 2022-11-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'User Rating Responses'},
        ),
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name': 'User Text Responses'},
        ),
    ]
