# Generated by Django 2.2.25 on 2023-06-13 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0002_auto_20221207_1157'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genplus_assessments', '0002_auto_20221129_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_unit', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('start_unit_location', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('end_unit', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('end_unit_location', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_learning.Program')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAssessmentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('earned_score', models.IntegerField(blank=True, default=0, null=True)),
                ('total_score', models.IntegerField(blank=True, default=6, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_assessments.SkillAssessmentQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
