# Generated by Django 2.2.25 on 2023-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_assessments', '0003_skillassessmentquestion_skillassessmentresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillassessmentquestion',
            options={'ordering': ('question_number',)},
        ),
        migrations.AddField(
            model_name='skillassessmentquestion',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillassessmentresponse',
            name='earned_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='skillassessmentresponse',
            name='total_score',
            field=models.FloatField(blank=True, default=6.0, null=True),
        ),
    ]
