# Generated by Django 2.2.25 on 2023-07-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_assessments', '0005_auto_20230717_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessmentquestion',
            name='problem_type',
            field=models.IntegerField(choices=[('LIKERT', 2), ('NUANCE_INTERROGATION', 1)], null=True),
        ),
    ]
