# Generated by Django 2.2.25 on 2023-08-07 11:13

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_assessments', '0006_skillassessmentquestion_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessmentresponse',
            name='problem_location',
            field=opaque_keys.edx.django.models.UsageKeyField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skillassessmentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='genplus_assessments.SkillAssessmentQuestion'),
        ),
    ]
