# Generated by Django 1.11.12 on 2018-04-25 07:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_lang', '0002_data__enable_on_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='darklangconfig',
            name='beta_languages',
            field=models.TextField(blank=True, help_text='A comma-separated list of language codes to release to the public as beta languages.'),
        ),
        migrations.AddField(
            model_name='darklangconfig',
            name='enable_beta_languages',
            field=models.BooleanField(default=False, help_text='Enable partially supported languages to display in language drop down.'),
        ),
    ]
