# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-24 10:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import openedx.features.custom_fields.multiselect_with_other.db.fields
import openedx.features.idea.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0029_auto_20200130_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Accepted extensions: .jpg, .png', null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('file', models.FileField(blank=True, help_text='Accepted extensions: .docx, .pdf, .txt', null=True, validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf', 'txt'])])),
                ('organization_mission', models.TextField()),
                ('organization_sector', openedx.features.custom_fields.multiselect_with_other.db.fields.MultiSelectWithOtherField(choices=[(b'health-and-well-being', 'Health & Well-being'), (b'education', 'Education'), (b'gender-equality', 'Gender Equality'), (b'sanitation', 'Sanitation'), (b'climate-changes', 'Climate Change'), (b'clean-energy', 'Clean Energy'), (b'environmental-conservation', 'Environmental Conservation'), (b'work-and-economic-growth', 'Work & Economic Growth'), (b'human-rights', 'Human Rights'), (b'social-justice', 'Social Justice'), (b'art-and-culture', 'Art & Culture'), (b'other', b'Other')], help_text='Please select all that apply.', max_length=233, verbose_name='Which sector is your organization working in?')),
                ('organizational_problems', openedx.features.custom_fields.multiselect_with_other.db.fields.MultiSelectWithOtherField(choices=[(b'healthcare-supplies', 'Healthcare Supplies'), (b'remote-working-tools', 'Remote Working Tools'), (b'online-training', 'Online Training'), (b'delivery-services', 'Delivery Services'), (b'mentorship', 'Mentorship'), (b'funding', 'Funding'), (b'human-resources', 'Human Resources'), (b'other', b'Other')], help_text='What are the areas that your organizaiton is currently facing a challenge in?  Please select all that apply.', max_length=159, verbose_name='Current Organizational Problems')),
                ('description', models.TextField(verbose_name='Brief Description of Challenges')),
                ('approach_to_address', models.TextField(blank=True, null=True, verbose_name='How has your organization already tried to address these challenges?')),
                ('resources_currently_using', models.TextField(blank=True, null=True, verbose_name='What tools or resources are you currently using?')),
                ('user_services', openedx.features.custom_fields.multiselect_with_other.db.fields.MultiSelectWithOtherField(choices=[(b'healthcare-supplies', 'Healthcare Supplies'), (b'people-power', 'People Power'), (b'online-training', 'Online Training'), (b'delivery-services', 'Delivery Services'), (b'mentorship', 'Mentorship'), (b'funding', 'Funding'), (b'human-resources', 'Human Resources'), (b'other', b'Other')], help_text='Please select all that apply.', max_length=151, verbose_name='What help can you provide to other organizations?')),
                ('brief_services_summery', models.TextField(blank=True, null=True, verbose_name='Brief explanation of services that you can provide to others.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_marketplacerequests', related_query_name='marketplace_marketplacerequest', to='onboarding.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', related_query_name='challenge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
