# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-27 16:41
from __future__ import unicode_literals

from django.db import migrations
import openedx.features.custom_fields.multiselect_with_other.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacerequest',
            name='user_services',
            field=openedx.features.custom_fields.multiselect_with_other.db.fields.MultiSelectWithOtherField(choices=[(b'healthcare-supplies', 'Healthcare Supplies'), (b'people-power', 'People Power'), (b'online-training', 'Online Training'), (b'delivery-services', 'Delivery Services'), (b'mentorship', 'Mentorship'), (b'funding', 'Funding'), (b'other', b'Other')], help_text='Please select all that apply.', max_length=135, verbose_name='What help can you provide to other organizations?'),
        ),
    ]
