# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-30 13:19
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields
import openedx.custom.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200427_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacerequest',
            old_name='brief_services_summery',
            new_name='brief_services_summary',
        ),
        migrations.AddField(
            model_name='marketplacerequest',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='marketplacerequest',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='marketplacerequest',
            name='organizational_problems',
            field=openedx.custom.db.fields.MultiSelectWithOtherField(choices=[(b'healthcare-supplies', 'Healthcare Supplies'), (b'remote-working-tools', 'Remote Working Tools'), (b'online-training', 'Online Training'), (b'delivery-services', 'Delivery Services'), (b'mentorship', 'Mentorship'), (b'funding', 'Funding'), (b'human-resources', 'Human Resources'), (b'other', b'Other')], help_text='What are the areas that your organization is currently facing a challenge in? Please select all that apply.', max_length=159, verbose_name='Current Organizational Problems'),
        ),
    ]
