# Generated by Django 2.2.12 on 2020-05-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_pipeline', '0003_coursevideouploadsenabledbydefault_videouploadsenabledbydefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='VEMPipelineIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('client_name', models.CharField(default='VEM-Prod', help_text='Oauth client name of VEM service.', max_length=100)),
                ('api_url', models.URLField(help_text='video encode manager API URL.', verbose_name='Internal API URL')),
                ('service_username', models.CharField(default='vem_service_user', help_text='Username created for VEM Integration, e.g. vem_service_user.', max_length=100)),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
