# Generated by Django 2.2.16 on 2020-10-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0006_remove_vempipelineintegration_vem_enabled_courses_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPipelineIntegration',
        ),
    ]
