# Generated by Django 4.2.10 on 2024-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_staging', '0003_olx_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedcontent',
            name='tags',
            field=models.JSONField(help_text='Content tags applied to these blocks', null=True),
        ),
    ]
