# Generated by Django 4.2.16 on 2024-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_staging', '0004_stagedcontent_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedcontent',
            name='version_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
