# Generated by Django 4.2.22 on 2025-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_staging', '0005_stagedcontent_version_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclipboard',
            name='source_usage_key',
            field=models.CharField(help_text='Original usage key/ID of the thing that is in the clipboard.', max_length=255),
        ),
        migrations.RenameField(
            model_name='userclipboard',
            old_name='source_usage_key',
            new_name='_source_usage_key',
        ),
    ]
