# Generated by Django 4.2.17 on 2025-01-25 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("content_staging", "0005_stagedcontent_version_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLibrarySync",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_usage_key",
                    opaque_keys.edx.django.models.UsageKeyField(
                        help_text="Original usage key/ID of the thing that is being synced.", max_length=255
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content_staging.stagedcontent"),
                ),
            ],
        ),
    ]
