# Generated by Django 4.2.22 on 2025-07-24 19:45

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('content_staging', '0005_stagedcontent_version_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclipboard',
            name='source_usage_key',
            field=opaque_keys.edx.django.models.UsageKeyField(blank=True, help_text='Original usage key/ID of the thing that is in the clipboard.', max_length=255),
        ),
    ]
