# Generated by Django 4.2.24 on 2025-09-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0004_url_textfield'),
        ('modulestore_migrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoremigration',
            name='task_status',
            field=models.ForeignKey(help_text='Tracks the status of the task which is executing this migration. In a bulk migration, the same task can be multiple migrations', on_delete=django.db.models.deletion.RESTRICT, related_name='migrations', to='user_tasks.usertaskstatus'),
        ),
    ]
