# Generated by Django 4.2.22 on 2025-06-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulestore_migrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoresource',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, help_text='If set, the system will forward references of this source over to the target of this migration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulestore_migrator.modulestoremigration'),
        ),
    ]
