# Generated by Django 5.2.7 on 2025-11-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modulestore_migrator', '0003_modulestoremigration_is_failed'),
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoreblockmigration',
            name='target',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='oel_publishing.publishableentity',
            ),
        ),
    ]
