# Generated by Django 5.2.7 on 2025-11-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modulestore_migrator', '0004_alter_modulestoreblockmigration_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestoreblockmigration',
            name='unsupported_reason',
            field=models.TextField(
                blank=True, help_text='Reason if the block is unsupported and target is set to null', null=True
            ),
        ),
    ]
