# Generated by Django 4.2.22 on 2025-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulestore_migrator', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestoremigration',
            name='preserve_url_slugs',
            field=models.BooleanField(default=True, help_text='If imported blocks have hashed slugs - do we want to preserve it?'),
        ),
        migrations.AlterField(
            model_name='modulestoremigration',
            name='composition_level',
            field=models.CharField(choices=[('component', 'Component'), ('unit', 'Unit'), ('subsection', 'Subsection'), ('section', 'Section')], default='component', help_text='Maximum hierachy level at which content should be aggregated in target library', max_length=255),
        ),
    ]
