# Generated by Django 5.2.7 on 2025-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulestore_migrator', '0004_modulestoremigration_migration_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestoremigration',
            name='unsupported_reasons',
            field=models.JSONField(default=list, help_text='List of unsuported blocks with the reasons'),
        ),
    ]
