# Generated by Django 5.2.7 on 2025-11-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulestore_migrator', '0004_alter_modulestoreblockmigration_target_squashed_0005_modulestoreblockmigration_unsupported_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestoremigration',
            name='migration_summary',
            field=models.JSONField(default=dict, help_text='Summary that contains number of sections, subsections, units and components migrated'),
        ),
    ]
