# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philu_courseware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencyassessmentrecord',
            options={'verbose_name': 'CompetencyAssessmentRecord'},
        ),
        migrations.AddField(
            model_name='competencyassessmentrecord',
            name='chapter_id',
            field=models.TextField(max_length=255),
            preserve_default=False,
        ),
    ]
