# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philu_courseware', '0002_auto_20200113_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyassessmentrecord',
            name='question_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
