from import_shims.warn import warn_deprecated_import

warn_deprecated_import('commerce.management.commands.tests.test_create_orders_for_old_enterprise_course_enrollmnet', 'lms.djangoapps.commerce.management.commands.tests.test_create_orders_for_old_enterprise_course_enrollmnet')

from lms.djangoapps.commerce.management.commands.tests.test_create_orders_for_old_enterprise_course_enrollmnet import *
