# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(b'remote', b'Remote'), (b'onsite', b'Onsite')], max_length=255)),
                ('compensation', models.CharField(choices=[(b'volunteer', b'Volunteer'), (b'hourly', b'Hourly'), (b'salaried', b'Salaried')], max_length=255)),
                ('hours', models.CharField(choices=[(b'fulltime', b'Full Time'), (b'parttime', b'Part Time'), (b'freelance', b'Freelance')], max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('description', models.TextField()),
                ('function', models.TextField()),
                ('responsibilities', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
