# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_auto_20200424_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Application Link'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(max_length=255, verbose_name='Contact Email'),
        ),
    ]
