# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-29 09:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import openedx.features.job_board.helpers
import util.philu_utils


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_auto_20200427_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, help_text="Please upload a file with your company's logo. (maximum 2MB)", max_length=500, null=True, upload_to=util.philu_utils.UploadToPathAndRename('job-board/uploaded-logos/', 'image'), validators=[django.core.validators.FileExtensionValidator([b'jpg', b'png']), openedx.features.job_board.helpers.validate_file_size], verbose_name='Company Logo'),
        ),
    ]
