// Generated by CoffeeScript 1.3.3
(function() {
  var TestProblemGenerator, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestProblemGenerator = (function(_super) {

    __extends(TestProblemGenerator, _super);

    function TestProblemGenerator(seed, parameters) {
      this.parameters = parameters != null ? parameters : {};
      TestProblemGenerator.__super__.constructor.call(this, seed, this.parameters);
    }

    TestProblemGenerator.prototype.generate = function() {
      this.problemState.value = this.parameters.value;
      return this.problemState;
    };

    return TestProblemGenerator;

  })(XProblemGenerator);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.generatorClass = TestProblemGenerator;

}).call(this);
