# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 20:27


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0007_historicalorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLibrary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('bundle_uuid', models.UUIDField(unique=True)),
                ('allow_public_learning', models.BooleanField(default=False, help_text='\n            Allow any user (even unregistered users) to view and interact with\n            content in this library (in the LMS; not in Studio). If this is not\n            enabled, then the content in this library is not directly accessible\n            in the LMS, and learners will only ever see this content if it is\n            explicitly added to a course. If in doubt, leave this unchecked.\n        ')),
                ('allow_public_read', models.BooleanField(default=False, help_text="\n            Allow any user with Studio access to view this library's content in\n            Studio, use it in their courses, and copy content out of this\n            library. If in doubt, leave this unchecked.\n        ")),
            ],
            options={
                'verbose_name_plural': 'Content Libraries',
            },
        ),
        migrations.CreateModel(
            name='ContentLibraryPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('admin', 'Administer users and author content'), ('author', 'Author content'), ('read', 'Read-only')], max_length=30)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_libraries.ContentLibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contentlibrary',
            name='authorized_users',
            field=models.ManyToManyField(through='content_libraries.ContentLibraryPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentlibrary',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='contentlibrary',
            unique_together=set([('org', 'slug')]),
        ),
    ]
