# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-11 19:20


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentlibrarypermission',
            options={'ordering': ('user__username', 'group__name')},
        ),
        migrations.RemoveField(
            model_name='contentlibrary',
            name='authorized_users',
        ),
        migrations.AddField(
            model_name='contentlibrarypermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', blank=True),
        ),
        migrations.AlterField(
            model_name='contentlibrarypermission',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='content_libraries.ContentLibrary'),
        ),
        migrations.AlterField(
            model_name='contentlibrarypermission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentlibrarypermission',
            unique_together=set([('library', 'user'), ('library', 'group')]),
        ),
    ]
