# Generated by Django 2.2.24 on 2021-08-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_libraries', '0005_contentlibraryblockimporttask'),
        ('content_libraries', '0006_auto_20210615_1916'),
    ]

    operations = [
    ]
