"""
This transitions the content storage for Content Libraries to go from Blockstore
to Learning Core (openedx-learning).
"""
# Generated by Django 3.2.23 on 2024-01-22 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0001_initial'),
        ('content_libraries', '0009_alter_contentlibrary_authorized_lti_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlibrary',
            name='bundle_uuid',
        ),
        migrations.AddField(
            model_name='contentlibrary',
            name='learning_package',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.learningpackage'),
        ),
    ]
