# Generated by Django 4.2.9 on 2024-02-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0001_initial'),
        ('content_libraries', '0009_alter_contentlibrary_authorized_lti_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlibrary',
            name='learning_package',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.learningpackage'),
        ),
        migrations.AlterField(
            model_name='contentlibrary',
            name='bundle_uuid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
