# Generated by Django 4.2.16 on 2024-10-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_libraries', '0010_contentlibrary_learning_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlibrary',
            name='bundle_uuid',
        ),
        migrations.RemoveField(
            model_name='contentlibrary',
            name='type',
        ),
    ]
