# Generated by Django 4.2.16 on 2024-11-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
        ('content_libraries', '0011_remove_contentlibrary_bundle_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLibraryMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', opaque_keys.edx.django.models.LearningContextKeyField(max_length=255, unique=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_libraries.contentlibrary')),
                ('target_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_collections.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ContentLibraryBlockMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.SlugField()),
                ('source_block_id', models.SlugField()),
                ('target_block_id', models.SlugField()),
                ('library_migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_migrations', to='content_libraries.contentlibrarymigration')),
            ],
            options={
                'unique_together': {('library_migration', 'block_type', 'source_block_id')},
            },
        ),
    ]
