# Generated by Django 4.2.23 on 2025-10-17 18:13

from django.db import migrations, models
import django.db.models.deletion


def remove_blockstore_libraries(apps, schema_editor):
    """
    Remove old Blockstore-based libraries

    Content Libraries are always created with a LearningPackage these days, but
    this model was once used for Blockstore-based libraries that did not use
    LearningPackages at all. Very few instances ever used those libraries, and
    those libraries will in a broken state anyway because Blockstore support has
    long since been removed from edx-platform.

    We are deleting these ContentLibrary entries so that we can enforce that all
    libraries going forward must specify a LearningPackage.
    """
    ContentLibrary = apps.get_model("content_libraries", "ContentLibrary")
    ContentLibrary.objects.filter(learning_package__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content_libraries', '0011_remove_contentlibrary_bundle_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_blockstore_libraries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contentlibrary',
            name='learning_package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.learningpackage'),
        ),
    ]
