# Generated by Django 5.2.9 on 2026-01-25 19:44

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('content_libraries', '0011_remove_contentlibrary_bundle_uuid_and_more'),
        ('openedx_content', '0001_initial'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='contentlibrary',
                    name='learning_package',
                    field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='openedx_content.learningpackage'),
                ),
            ]
        ),
    ]
