UNSORTED_CONTACT_LIST_INDEX = 0
SORTED_PLATFORM_CONTACT_LIST_INDEX = 1
SORTED_NON_PLATFORM_CONTACT_LIST_INDEX = 2
SORTED_CONTACT_LIST_INDEX = 3

UNSORTED_CONTACT_LIST_KEY = 'contacts_list'
SORTED_PLATFORM_CONTACT_LIST_KEY = 'platform_contacts_list'
SORTED_NON_PLATFORM_CONTACT_LIST_KEY = 'non_platform_contacts_list'
SORTED_CONTACT_LIST_KEY = 'sorted_contacts_list'
