# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0016_auto_20190703_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistentsubsectiongradeoverridehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersistentSubsectionGradeOverrideHistory',
        ),
    ]
