# Generated by Django 3.2.16 on 2022-10-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0019_auto_20220912_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpersistentsubsectiongradeoverride',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical persistent subsection grade override', 'verbose_name_plural': 'historical persistent subsection grade overrides'},
        ),
    ]
