# Generated by Django 4.2.20 on 2025-05-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0020_alter_historicalpersistentsubsectiongradeoverride_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='persistentcoursegrade',
            new_name='passed_timestamp_course_id_idx',
            old_fields=('passed_timestamp', 'course_id'),
        ),
        migrations.RenameIndex(
            model_name='persistentcoursegrade',
            new_name='modified_course_id_idx',
            old_fields=('modified', 'course_id'),
        ),
    ]
