# Generated by Django 4.2.20 on 2025-05-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0021_rename_persistentcoursegrade_passed_timestamp_course_id_passed_timestamp_course_id_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='persistentsubsectiongrade',
            new_name='first_course_id_user_id_idx',
            old_fields=('first_attempted', 'course_id', 'user_id'),
        ),
        migrations.RenameIndex(
            model_name='persistentsubsectiongrade',
            new_name='course_id_usage_key_idx',
            old_fields=('modified', 'course_id', 'usage_key'),
        ),
    ]
