# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-04 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UCSDCustomRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_nb', models.CharField(choices=[(b'female', b'Female'), (b'male', b'Male'), (b'nonbinary', b'Non-Binary'), (b'decline', b'Decline to state')], max_length=16, verbose_name=b'Gender')),
                ('ethnicity', models.CharField(choices=[(b'aab', b'African American and black'), (b'aian', b'American Indian / Alaska Native'), (b'a', b'Asian'), (b'hl', b'Hispanic / Latinx'), (b'sana', b'Southwest Asia / North African'), (b'w', b'White'), (b'decline', b'Decline to state')], max_length=16, verbose_name=b'Ethnicity')),
                ('age', models.CharField(choices=[(b'1317', b'13 - 17 years old'), (b'1822', b'18 - 22 years old'), (b'2329', b'23 - 29 years old'), (b'3049', b'30 - 49 years old'), (b'50plus', b'50+ years old'), (b'decline', b'Decline to state')], max_length=16, verbose_name=b'Age')),
                ('education', models.CharField(choices=[(b'grad', b'Graduate'), (b'undergrad', b'Undergrad'), (b'highschool', b'Up to high school'), (b'decline', b'Decline to state')], max_length=16, verbose_name=b'Highest level of education completed')),
                ('howheard', models.CharField(choices=[(b'socialmedia', b'Social media'), (b'email', b'Email'), (b'wom', b'Word-of-mouth'), (b'print', b'Print advertisement'), (b'other', b'Other')], max_length=16, verbose_name=b'How did you hear about UC San Diego Online')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
