# Generated by Django 3.2.20 on 2023-09-12 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_auto_20230727_2054'),
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRolesPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRolesRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRolesService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRolesUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_roles.courserolesrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRolesRoleService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_roles.courserolesrole')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_roles.courserolesservice')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRolesRolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_roles.courserolespermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_roles.courserolesrole')),
            ],
        ),
        migrations.AddField(
            model_name='courserolesrole',
            name='permissions',
            field=models.ManyToManyField(through='course_roles.CourseRolesRolePermissions', to='course_roles.CourseRolesPermission'),
        ),
        migrations.AddField(
            model_name='courserolesrole',
            name='services',
            field=models.ManyToManyField(through='course_roles.CourseRolesRoleService', to='course_roles.CourseRolesService'),
        ),
        migrations.AddField(
            model_name='courserolesrole',
            name='users',
            field=models.ManyToManyField(through='course_roles.CourseRolesUserRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
