# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-15 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ondemand_email_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ondemandemailpreferences',
            unique_together=set([('course_id', 'user')]),
        ),
    ]
