# Generated by Django 2.2.20 on 2021-05-07 18:29, manually modified to make "course_id" column case sensitive

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitModulestoreCourseIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.CharField(max_length=24, unique=True)),
                ('course_id', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255, unique=True)),
                ('org', models.CharField(db_index=True, max_length=255)),
                ('draft_version', models.CharField(blank=True, max_length=24)),
                ('published_version', models.CharField(blank=True, max_length=24)),
                ('library_version', models.CharField(blank=True, max_length=24)),
                ('wiki_slug', models.CharField(db_index=True, blank=True, max_length=255)),
                ('base_store', models.CharField(choices=[('mongodb', 'MongoDB'), ('django', 'Django - not implemented yet')], max_length=20)),
                ('edited_on', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('edited_by_id', models.IntegerField(null=True)),
            ],
            options={'ordering': ['course_id'], 'verbose_name_plural': 'Split modulestore course indexes'},
        ),
        migrations.CreateModel(
            name='HistoricalSplitModulestoreCourseIndex',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('objectid', models.CharField(db_index=True, max_length=24)),
                ('course_id', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255)),
                ('org', models.CharField(db_index=True, max_length=255)),
                ('draft_version', models.CharField(blank=True, max_length=24)),
                ('published_version', models.CharField(blank=True, max_length=24)),
                ('library_version', models.CharField(blank=True, max_length=24)),
                ('wiki_slug', models.CharField(db_index=True, blank=True, max_length=255)),
                ('base_store', models.CharField(choices=[('mongodb', 'MongoDB'), ('django', 'Django - not implemented yet')], max_length=20)),
                ('edited_on', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('edited_by_id', models.IntegerField(null=True)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical split modulestore course index',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # Custom code: Convert columns to utf8_bin because we want to allow
        # case-sensitive comparisons for CourseKeys, which were case-sensitive in MongoDB
        migrations.RunSQL(
            'ALTER TABLE split_modulestore_django_splitmodulestorecourseindex MODIFY course_id varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL UNIQUE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            'ALTER TABLE split_modulestore_django_historicalsplitmodulestorecourseindex MODIFY course_id varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
