# Generated by Django 4.2.19 on 2025-05-13 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineRoot',
            fields=[
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oel_publishing.container')),
            ],
            options={
                'abstract': False,
            },
            bases=('oel_publishing.container',),
        ),
        migrations.CreateModel(
            name='OutlineRootVersion',
            fields=[
                ('container_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oel_publishing.containerversion')),
            ],
            options={
                'abstract': False,
            },
            bases=('oel_publishing.containerversion',),
        ),
    ]
