# Generated by Django 1.11.12 on 2018-04-25 12:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0009_remove_emailmarketingconfiguration_sailthru_activation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmarketingconfiguration',
            name='sailthru_verification_failed_template',
            field=models.CharField(blank=True, help_text='Sailthru send template to use on failed ID verification.', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmarketingconfiguration',
            name='sailthru_verification_passed_template',
            field=models.CharField(blank=True, help_text='Sailthru send template to use on passed ID verification.', max_length=20),
        ),
    ]
