# Generated by Django 2.2.20 on 2021-05-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0010_auto_20180425_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMarketingConfiguration',
        ),
    ]
