# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0010_auto_20180425_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmarketingconfiguration',
            name='sailthru_verification_expired_template',
            field=models.CharField(blank=True, help_text='Sailthru email template for expired ID verification', max_length=20),
        ),
    ]
