"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('program_enrollments.management.commands.migrate_saml_uids', 'lms.djangoapps.program_enrollments.management.commands.migrate_saml_uids')

from lms.djangoapps.program_enrollments.management.commands.migrate_saml_uids import *
