# Generated by Django 2.2.17 on 2021-04-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledWebinar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webinars.webinar',),
        ),
    ]
