# Generated by Django 2.2.17 on 2021-04-14 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webinars', '0002_cancelledwebinar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('webinar', 'user')},
        ),
    ]
