# Generated by Django 2.2.17 on 2021-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_auto_20210414_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistration',
            name='is_team_member_registration',
            field=models.BooleanField(default=False, verbose_name='Is Presenter, Co-Host, or Panelist'),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='starting_soon_mandrill_reminder_id',
            field=models.CharField(default='', max_length=255, verbose_name='Scheduled Starting Soon Reminder Id On Mandrill'),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='week_before_mandrill_reminder_id',
            field=models.CharField(default='', max_length=255, verbose_name='Scheduled Week Before Reminder Id On Mandrill'),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Registered'),
        ),
    ]
