# Generated by Django 2.2.17 on 2021-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_auto_20210424_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='is_virtual',
        ),
        migrations.AlterField(
            model_name='webinar',
            name='meeting_link',
            field=models.URLField(verbose_name='Meeting Link'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
