from import_shims.warn import warn_deprecated_import

warn_deprecated_import('verify_student.management.commands.backfill_sso_verifications_for_old_account_links', 'lms.djangoapps.verify_student.management.commands.backfill_sso_verifications_for_old_account_links')

from lms.djangoapps.verify_student.management.commands.backfill_sso_verifications_for_old_account_links import *
