# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 07:23
from __future__ import unicode_literals

import bulk_email.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0006_course_mode_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseemail',
            name='from_addr',
            field=models.CharField(default=bulk_email.models.default_from_email, max_length=255, null=True),
        ),
    ]
