# Generated by Django 3.2.9 on 2021-11-22 16:05

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0006_course_mode_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
