# Generated by Django 2.2.13 on 2020-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0006_course_mode_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseemail',
            name='reply_to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
