# Generated by Django 3.2.21 on 2023-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0007_disabledcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('myself', 'Myself'), ('staff', 'Staff and instructors'), ('learners', 'All students'), ('cohort', 'Specific cohort'), ('track', 'Specific course mode'), ('individual-learners', 'Specific list of students')], max_length=64),
        ),
    ]
