# Generated by Django 3.2.16 on 2023-01-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tours', '0002_auto_20221227_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiscussionstours',
            name='status',
        ),
        migrations.AddField(
            model_name='userdiscussionstours',
            name='show_courseware_tour',
            field=models.BooleanField(default=True),
        ),
    ]
