# Generated by Django 3.2.16 on 2023-01-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tours', '0003_auto_20230104_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdiscussionstours',
            old_name='show_courseware_tour',
            new_name='show_tour',
        ),
    ]
