# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-05 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=100)),
                ('main_logo', models.CharField(default=None, max_length=255, null=True)),
                ('small_logo', models.CharField(default=None, max_length=255, null=True)),
                ('slug', models.CharField(default=None, max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partners.Partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partneruser',
            unique_together=set([('user', 'partner')]),
        ),
    ]
