# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models

from openedx.features.partners.constants import PERFORMANCE_PERM_FRMT


def add_performance_permission_for_g2a(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Partner = apps.get_model('partners', 'Partner')

    Permission.objects.create(codename=PERFORMANCE_PERM_FRMT.format(slug='give2asia'),
                              name='Can access give2asia performance',
                              content_type=ContentType.objects.get_for_model(Partner))


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200101_1222'),
    ]

    operations = [
        migrations.RunPython(add_performance_permission_for_g2a),
        migrations.AddField(
            model_name='partner',
            name='performance_url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
