# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20200120_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='configuration',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='partneruser',
            name='status',
            field=models.CharField(choices=[(b'waiting', b'waiting'), (b'approved', b'approved')], default=b'approved', max_length=32),
        ),
    ]
