# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_config_partneruser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='main_logo',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='small_logo',
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(default='', help_text=b'Contact Email of an Organization', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(default='', help_text=b'Main Logo in Landing page.', upload_to=b'partners/logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='label',
            field=models.CharField(help_text=b'Display as a Title in Landing page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.CharField(help_text=b'A Unique Identifier for an Organization', max_length=100, unique=True),
        ),
    ]
