# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import openedx.features.philu_utils.backend_storage
import util.philu_utils


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20200320_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(help_text=b'Main logo in landing page.', max_length=500, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, name_prefix=b'logo', path=b'images')),
        ),
    ]
