# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-05 14:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20200320_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='configuration',
            field=jsonfield.fields.JSONField(blank=True, default=b'{"USER_LIMIT": ""}'),
        ),
    ]
