# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-11-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import openedx.features.philu_utils.backend_storage
import util.philu_utils


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20200612_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='heading1',
            field=models.CharField(blank=True, help_text=b'Heading 1', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='heading1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='heading2',
            field=models.CharField(blank=True, help_text=b'Heading 2', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='heading2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='main_bg_image',
            field=models.ImageField(blank=True, help_text=b'Background image under main title and description.', max_length=500, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, name_prefix=b'main_bg_image', path=b'images')),
        ),
        migrations.AddField(
            model_name='partner',
            name='main_description',
            field=models.TextField(blank=True, help_text=b'Brief description of partners landing page.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='main_title',
            field=models.CharField(blank=True, help_text=b'Display on partners landing page as main title.', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='parallax_bg_image',
            field=models.ImageField(blank=True, help_text=b'Background image of parallax.', max_length=500, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, name_prefix=b'parallax_bg_image', path=b'images')),
        ),
        migrations.AddField(
            model_name='partner',
            name='testimonials1',
            field=jsonfield.fields.JSONField(blank=True, default={b'description': b'', b'qoute_by': b'', b'address': b''}),
        ),
        migrations.AddField(
            model_name='partner',
            name='testimonials2',
            field=jsonfield.fields.JSONField(blank=True, default={b'description': b'', b'qoute_by': b'', b'address': b''}),
        ),
        migrations.AlterField(
            model_name='partner',
            name='configuration',
            field=jsonfield.fields.JSONField(blank=True, default={b'USER_LIMIT': b''}),
        ),
    ]
