# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-12-03 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import jsonfield.fields
import openedx.features.philu_utils.backend_storage
import util.philu_utils


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20201118_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partnership_year',
            field=models.PositiveIntegerField(blank=True, default=2020),
        ),
        migrations.AlterField(
            model_name='partner',
            name='configuration',
            field=jsonfield.fields.JSONField(blank=True, default=b'{"USER_LIMIT": ""}'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='main_bg_image',
            field=models.ImageField(blank=True, help_text='Accepted extensions: .jpg, .png (maximum 2 MB)', max_length=500, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, name_prefix=b'main_bg_image', path=b'images'), validators=[django.core.validators.FileExtensionValidator([b'jpg', b'png'])], verbose_name='ADD MAIN BACKGROUND IMAGE'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='parallax_bg_image',
            field=models.ImageField(blank=True, help_text='Accepted extensions: .jpg, .png (maximum 2 MB)', max_length=500, storage=openedx.features.philu_utils.backend_storage.CustomS3Storage(), upload_to=util.philu_utils.UploadToPathAndRename(add_path_prefix=True, name_prefix=b'main_bg_image', path=b'images'), validators=[django.core.validators.FileExtensionValidator([b'jpg', b'png'])], verbose_name='ADD PARALLAX BACKGROUND IMAGE'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='testimonials1',
            field=jsonfield.fields.JSONField(blank=True, default=b'{"qoute_by": "", "description": "", "address": ""}'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='testimonials2',
            field=jsonfield.fields.JSONField(blank=True, default=b'{"qoute_by": "", "description": "", "address": ""}'),
        ),
    ]
