# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-12-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20201203_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='heading1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='heading1_description',
            field=models.TextField(blank=True, help_text='max 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='heading2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='heading2_description',
            field=models.TextField(blank=True, help_text='max 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='main_description',
            field=models.TextField(blank=True, help_text='max 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='main_title',
            field=models.CharField(blank=True, help_text='max 100 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_year',
            field=models.PositiveIntegerField(blank=True, default=2020, null=True),
        ),
    ]
