# Generated by Django 2.2.12 on 2020-04-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program_enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourseenrollment',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.CourseEnrollment'),
        ),
        migrations.AddField(
            model_name='programcourseenrollment',
            name='program_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_course_enrollments', to='program_enrollments.ProgramEnrollment'),
        ),
        migrations.AddField(
            model_name='historicalprogramenrollment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprogramenrollment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprogramcourseenrollment',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student.CourseEnrollment'),
        ),
        migrations.AddField(
            model_name='historicalprogramcourseenrollment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprogramcourseenrollment',
            name='program_enrollment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='program_enrollments.ProgramEnrollment'),
        ),
        migrations.AddField(
            model_name='courseaccessroleassignment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_enrollments.ProgramCourseEnrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together={('user', 'program_uuid', 'curriculum_uuid'), ('external_user_key', 'program_uuid', 'curriculum_uuid')},
        ),
        migrations.AlterUniqueTogether(
            name='programcourseenrollment',
            unique_together={('program_enrollment', 'course_key')},
        ),
        migrations.AlterUniqueTogether(
            name='courseaccessroleassignment',
            unique_together={('role', 'enrollment')},
        ),
    ]
