# Generated by Django 1.11.20 on 2019-06-03 13:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_enrollments', '0004_add_programcourseenrollment_relatedname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogramenrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('pending', 'pending'), ('suspended', 'suspended'), ('canceled', 'canceled')], max_length=9),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('pending', 'pending'), ('suspended', 'suspended'), ('canceled', 'canceled')], max_length=9),
        ),
    ]
