# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 16:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_enrollments', '0007_waiting_programcourseenrollment_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogramenrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('pending', 'pending'), ('suspended', 'suspended'), ('canceled', 'canceled'), ('ended', 'ended')], max_length=9),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('pending', 'pending'), ('suspended', 'suspended'), ('canceled', 'canceled'), ('ended', 'ended')], max_length=9),
        ),
    ]
