# Generated by Django 2.2.16 on 2020-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_enrollments', '0010_add_courseaccessroleassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseaccessroleassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programcourseenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='programcourseenrollment',
            constraint=models.UniqueConstraint(fields=('program_enrollment', 'course_key'), name='unique_program_enrollment_course_pair'),
        ),
        migrations.AddConstraint(
            model_name='programenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'program_uuid', 'curriculum_uuid'), name='unique_user_program_curriculum_triple'),
        ),
        migrations.AddConstraint(
            model_name='programenrollment',
            constraint=models.UniqueConstraint(fields=('external_user_key', 'program_uuid', 'curriculum_uuid'), name='unique_ext_user_program_curriculum_triple'),
        ),
        migrations.AddConstraint(
            model_name='courseaccessroleassignment',
            constraint=models.UniqueConstraint(fields=('role', 'enrollment'), name='unique_role_enrollment_pair'),
        ),
    ]
