"""Deprecated import support. Auto-generated by import_shims/generate_shims.sh."""
# pylint: disable=redefined-builtin,wrong-import-position,wildcard-import,useless-suppression,line-too-long

from import_shims.warn import warn_deprecated_import

warn_deprecated_import('commerce.management.commands.create_orders_for_old_enterprise_course_enrollment', 'lms.djangoapps.commerce.management.commands.create_orders_for_old_enterprise_course_enrollment')

from lms.djangoapps.commerce.management.commands.create_orders_for_old_enterprise_course_enrollment import *
