# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_coursenrollment_course_on_delete_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Secondary email address'),
        ),
    ]
