# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 14:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_accountrecovery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
