# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 20:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20181221_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginfailures',
            options={'verbose_name': 'Login Failure', 'verbose_name_plural': 'Login Failures'},
        ),
    ]
