# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20181221_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
