# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-18 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20181221_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalUserProfile',
        ),
    ]
