# Generated by Django 2.2.12 on 2020-05-06 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_removed_logout_view_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers, () and -', regex='^\\(?\\d{3}\\)?( |-)?\\d{3}-?\\d{4}$')]),
        ),
    ]
