# Generated by Django 2.2.12 on 2020-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_userprofile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalAccessRole',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('student.courseaccessrole',),
        ),
    ]
