# Generated by Django 2.2.16 on 2020-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_userpasswordtogglehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinaddtoprofileconfiguration',
            name='dashboard_tracking_code',
        ),
        migrations.RemoveField(
            model_name='linkedinaddtoprofileconfiguration',
            name='trk_partner_name',
        ),
        migrations.AlterField(
            model_name='linkedinaddtoprofileconfiguration',
            name='company_identifier',
            field=models.TextField(blank=True, help_text='Your organization ID (if your organization has an existing page on LinkedIn) e.g 1337. If not provided, will default to sending Platform Name (e.g. edX) instead.'),
        ),
    ]
