# Generated by Django 2.2.16 on 2020-10-21 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_linkedinaddtoprofileconfiguration_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecoveryconfiguration',
            name='csv_file',
            field=models.FileField(help_text='It expect that the data will be provided in a csv file format with                     first row being the header and columns will be as follows:                     username, current_email, desired_email', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
