# Generated by Django 2.2.19 on 2021-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_usercelebration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='activation_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
