# Generated by Django 2.2.20 on 2021-04-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_allow_certificate_null_20210427_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_certificate',
        ),
    ]
