# Generated by Django 3.2.12 on 2022-06-27 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0027_liveclasses'),
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_attendance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='LiveClassEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveclass_attendance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('live_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.liveclasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(blank=True, help_text='Course Chapter Name', max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=10, null=True)),
                ('document_name', models.CharField(blank=True, help_text='Enter Document Name', max_length=50, null=True)),
                ('document', models.FileField(max_length=255, upload_to='course_docs')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='course_overviews.courseoverview')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_doc_storage',
            },
        ),
    ]
