# Generated by Django 3.2.20 on 2023-08-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcourseenrollment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course enrollment', 'verbose_name_plural': 'historical course enrollments'},
        ),
        migrations.AlterModelOptions(
            name='historicalmanualenrollmentaudit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical manual enrollment audit', 'verbose_name_plural': 'historical manual enrollment audits'},
        ),
    ]
