# Generated by Django 3.2.13 on 2022-06-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0027_liveclasses'),
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_attendance',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='LiveClassEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.liveclasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
