# Generated by Django 3.2.13 on 2022-05-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_courseliveclasses'),
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='course_live_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseliveclasses'),
        ),
        migrations.AddField(
            model_name='historicalcourseenrollment',
            name='course_live_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_overviews.courseliveclasses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_attendance',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
