# Generated by Django 3.2.12 on 2022-04-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_courseliveclasses'),
        ('student', '0045_userprofile_user_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='course_live_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseliveclasses'),
        ),
        migrations.AddField(
            model_name='historicalcourseenrollment',
            name='course_live_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_overviews.courseliveclasses'),
        ),
    ]
