# Generated by Django 3.2.13 on 2022-05-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0028_auto_20220517_1345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0045_auto_20220512_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='course_live_class',
        ),
        migrations.RemoveField(
            model_name='historicalcourseenrollment',
            name='course_live_class',
        ),
        migrations.CreateModel(
            name='LiveClassEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.liveclasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
