# Generated by Django 3.2.12 on 2022-06-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_notifycallrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifycallrequest',
            old_name='active_status',
            new_name='seen',
        ),
    ]
