# Generated by Django 3.2.13 on 2022-06-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0027_liveclasses'),
        ('student', '0046_remove_userprofile_user_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(blank=True, help_text='Course Chapter Name', max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=10, null=True)),
                ('document_name', models.CharField(blank=True, help_text='Enter Document Name', max_length=50, null=True)),
                ('document', models.FileField(upload_to='course_docs')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='course_overviews.courseoverview')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_doc_storage',
            },
        ),
    ]
