# Generated by Django 3.2.12 on 2022-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_rename_active_status_notifycallrequest_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycallrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
