# Generated by Django 3.2.12 on 2022-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_documentstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstorage',
            name='document',
            field=models.FileField(max_length=255, upload_to='course_docs'),
        ),
    ]
