# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def migrate_application_data(apps, schema_editor):
    """
    Migrate existing DOT Application models to new ScopedApplication models.
    """
    Application = apps.get_model(settings.OAUTH2_PROVIDER_APPLICATION_MODEL)
    ScopedApplication = apps.get_model('oauth_dispatch', 'ScopedApplication')

    for application in Application.objects.all():
        scoped_application = ScopedApplication(
            client_id=application.client_id,
            user=application.user,
            redirect_uris=application.redirect_uris,
            client_type=application.client_type,
            authorization_grant_type=application.authorization_grant_type,
            client_secret=application.client_secret,
            name=application.name,
            skip_authorization=application.skip_authorization,
        )
        scoped_application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_dispatch', '0002_scopedapplication_scopedapplicationorganization'),
    ]

    operations = [
        migrations.RunPython(migrate_application_data),
    ]
