# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_dispatch', '0003_application_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopedapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
