# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 14:58


import django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DEPENDENCIES = [
    ('oauth_dispatch', '0005_applicationaccess_type'),
]
RUN_BEFORE = []
if django.VERSION >= (2, 0):
    # Using django-oauth-toolkit 1.3.2+, which squashed and deleted the original 6 migrations
    DEPENDENCIES.append(('oauth2_provider', '0001_initial'))
else:
    # Using django-oauth-toolkit 1.1.3 or earlier, before the migrations squashing
    RUN_BEFORE.append(('oauth2_provider', '0005_auto_20170514_1141'))


class Migration(migrations.Migration):

    dependencies = DEPENDENCIES
    run_before = RUN_BEFORE

    operations = [
        migrations.AlterField(
            model_name='applicationaccess',
            name='application',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationorganization',
            name='application',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='restrictedapplication',
            name='application',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
