# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 15:12


import django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

if django.VERSION >= (2, 0):
    dot_migration = '0001_initial'
else:
    dot_migration = '0006_auto_20171214_2232'


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_dispatch', '0006_drop_application_id_constraints'),
        ('oauth2_provider', dot_migration),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaccess',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationorganization',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='restrictedapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
