ORGANIZATION_NAME_KEY = 'organization_name'
ENGLISH_PROFICIENCY_KEY = 'english_proficiency'
START_MONTH_YEAR_KEY = 'start_month_year'
IS_INTERESTS_DATA_SUBMITTED_KEY = 'is_interests_data_submitted'
FIRST_NAME_KEY = 'first_name'
LAST_NAME_KEY = 'last_name'
YEAR_OF_BIRTH_KEY = 'year_of_birth'
LEVEL_OF_EDUCATION_KEY = 'level_of_education'
GIVE2ASIA_DEFAULT_DATA = {
    YEAR_OF_BIRTH_KEY: 2000,
    LEVEL_OF_EDUCATION_KEY: 'IWRNS',
    ENGLISH_PROFICIENCY_KEY: 'IWRNS',
    START_MONTH_YEAR_KEY: '11/2019',
    IS_INTERESTS_DATA_SUBMITTED_KEY: True,
}
