// Generated by CoffeeScript 1.6.3
(function() {
  xdescribe('VideoControlAlpha', function() {
    beforeEach(function() {
      window.onTouchBasedDevice = jasmine.createSpy('onTouchBasedDevice').andReturn(false);
      loadFixtures('videoalpha.html');
      return $('.video-controls').html('');
    });
    describe('constructor', function() {
      it('render the video controls', function() {
        this.control = new window.VideoControlAlpha({
          el: $('.video-controls')
        });
        expect($('.video-controls')).toContain;
        ['.slider', 'ul.vcr', 'a.play', '.vidtime', '.add-fullscreen'].join(',');
        return expect($('.video-controls').find('.vidtime')).toHaveText('0:00 / 0:00');
      });
      it('bind the playback button', function() {
        this.control = new window.VideoControlAlpha({
          el: $('.video-controls')
        });
        return expect($('.video_control')).toHandleWith('click', this.control.togglePlayback);
      });
      describe('when on a touch based device', function() {
        beforeEach(function() {
          window.onTouchBasedDevice.andReturn(true);
          return this.control = new window.VideoControlAlpha({
            el: $('.video-controls')
          });
        });
        return it('does not add the play class to video control', function() {
          expect($('.video_control')).not.toHaveClass('play');
          return expect($('.video_control')).not.toHaveHtml('Play');
        });
      });
      return describe('when on a non-touch based device', function() {
        beforeEach(function() {
          return this.control = new window.VideoControlAlpha({
            el: $('.video-controls')
          });
        });
        return it('add the play class to video control', function() {
          expect($('.video_control')).toHaveClass('play');
          return expect($('.video_control')).toHaveHtml('Play');
        });
      });
    });
    describe('play', function() {
      beforeEach(function() {
        this.control = new window.VideoControlAlpha({
          el: $('.video-controls')
        });
        return this.control.play();
      });
      return it('switch playback button to play state', function() {
        expect($('.video_control')).not.toHaveClass('play');
        expect($('.video_control')).toHaveClass('pause');
        return expect($('.video_control')).toHaveHtml('Pause');
      });
    });
    describe('pause', function() {
      beforeEach(function() {
        this.control = new window.VideoControlAlpha({
          el: $('.video-controls')
        });
        return this.control.pause();
      });
      return it('switch playback button to pause state', function() {
        expect($('.video_control')).not.toHaveClass('pause');
        expect($('.video_control')).toHaveClass('play');
        return expect($('.video_control')).toHaveHtml('Play');
      });
    });
    return describe('togglePlayback', function() {
      beforeEach(function() {
        return this.control = new window.VideoControlAlpha({
          el: $('.video-controls')
        });
      });
      return describe('when the control does not have play or pause class', function() {
        beforeEach(function() {
          return $('.video_control').removeClass('play').removeClass('pause');
        });
        describe('when the video is playing', function() {
          beforeEach(function() {
            $('.video_control').addClass('play');
            spyOnEvent(this.control, 'pause');
            return this.control.togglePlayback(jQuery.Event('click'));
          });
          return it('does not trigger the pause event', function() {
            return expect('pause').not.toHaveBeenTriggeredOn(this.control);
          });
        });
        describe('when the video is paused', function() {
          beforeEach(function() {
            $('.video_control').addClass('pause');
            spyOnEvent(this.control, 'play');
            return this.control.togglePlayback(jQuery.Event('click'));
          });
          return it('does not trigger the play event', function() {
            return expect('play').not.toHaveBeenTriggeredOn(this.control);
          });
        });
        describe('when the video is playing', function() {
          beforeEach(function() {
            spyOnEvent(this.control, 'pause');
            $('.video_control').addClass('pause');
            return this.control.togglePlayback(jQuery.Event('click'));
          });
          return it('trigger the pause event', function() {
            return expect('pause').toHaveBeenTriggeredOn(this.control);
          });
        });
        return describe('when the video is paused', function() {
          beforeEach(function() {
            spyOnEvent(this.control, 'play');
            $('.video_control').addClass('play');
            return this.control.togglePlayback(jQuery.Event('click'));
          });
          return it('trigger the play event', function() {
            return expect('play').toHaveBeenTriggeredOn(this.control);
          });
        });
      });
    });
  });

}).call(this);
