# Generated by Django 3.2.20 on 2023-07-19 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_groups', '0004_alter_courseusergroup_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grouped', models.BooleanField(default=False)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, help_text='Which course are these settings associated with?', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('course_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_groups.courseusergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_user_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='course_groups.courseusergroup')),
                ('professors', models.ManyToManyField(blank=True, db_index=True, related_name='course_groups_professors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
