name: Trigger to add Issue or PR to a Core Contributor project board
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add-to-cc-board:
    if: github.event.label.name == 'Core Contributor assignee'
    uses: openedx/.github/.github/workflows/add-to-cc-board.yml@master
    with:
      board_name: cc-edx-platform
    secrets:
      projects_access_token: ${{ secrets.PROJECTS_TOKEN }}
