name: Docker Image CI

on:
  push:
    branches:
      - 'eol-release/**'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
    branches:
      - 'eol-release/**'
    paths-ignore:
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v3-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v3-

      - name: Define release version
        # TODO: parameterize release name
        run: echo "RELEASE-NAME=koa" >> $GITHUB_ENV

      - name: Set current date as env variable
        run: echo "TS=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Open edX Base
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target base \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --tag ghcr.io/eol-uchile/edx-platform:${GITHUB_SHA} \
            --tag ghcr.io/eol-uchile/edx-platform:${{ env.RELEASE-NAME }}-${{ env.TS }} \
            --tag ghcr.io/eol-uchile/edx-platform:${{ env.RELEASE-NAME }} \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
            --output "type=docker,push=false"

      - name: Build Open edX Testing version
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target testing \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --cache-from "type=local,src=/tmp/.buildx-cache-new" \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --output "type=docker,push=false"

      - name: Test eol changes
        run: |
          cd .github/test
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/heads/eol-release/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push production image to the registry
        if: startsWith(github.ref, 'refs/heads/eol-release/')
        run: |
          docker push ghcr.io/eol-uchile/edx-platform:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-platform:${{ env.RELEASE-NAME }}-${{ env.TS }}
          docker push ghcr.io/eol-uchile/edx-platform:${{ env.RELEASE-NAME }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
