name: Docker Image CI

on:
  push:
    branches:
      - eol/ironwood.master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull latest cache
        run: docker pull eoluchile/edx-platform:latest

      - name: Build OpenedX
        run: docker build . --file .github/build/Dockerfile --tag eoluchile/edx-platform:${GITHUB_SHA} --tag eoluchile/edx-platform:latest

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/edx-platform:${GITHUB_SHA}
          docker push eoluchile/edx-platform:latest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

