name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Open edX Base
        run: docker build . --file .github/build/Dockerfile --target base --tag eoluchile/edx-platform:${GITHUB_SHA} --tag eoluchile/edx-platform:juniper

      - name: Build Open edX Testing version
        run: docker build . --file .github/build/Dockerfile --target testing --tag eoluchile/edx-platform:testing-juniper

      - name: Test eol changes
        run: |
          cd .github/test
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh

      - name: Push
        if: github.ref == 'refs/heads/eol/ironwood.master'
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/edx-platform:${GITHUB_SHA}
          docker push eoluchile/edx-platform:latest
          docker push eoluchile/edx-platform:testing-juniper
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to juniper
        if: github.ref == 'refs/heads/eol/juniper.rc3'
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/edx-platform:${GITHUB_SHA}
          docker push eoluchile/edx-platform:juniper
          docker push eoluchile/edx-platform:testing-juniper
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
