name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v1-

      - name: Build Open edX Base
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target base \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --tag eoluchile/edx-platform:${GITHUB_SHA} \
            --tag eoluchile/edx-platform:koa \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
            --output "type=docker,push=false"

      - name: Build Open edX Testing version
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target testing \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --tag eoluchile/edx-platform:testing-koa \
            --cache-from "type=local,src=/tmp/.buildx-cache-new" \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --output "type=docker,push=false"

      - name: Test eol changes
        run: |
          cd .github/test
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh lms/djangoapps/instructor_task/tests/test_tasks_helper.py && docker-compose down -v
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh lms/djangoapps/instructor_analytics/tests/test_basic.py  && docker-compose down -v
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh lms/djangoapps/certificates/tests/test_webview_views.py && docker-compose down -v
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh lms/djangoapps/bulk_email/tests/ && docker-compose down -v
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh lms/djangoapps/instructor/tests/ && docker-compose down -v
          docker-compose run cms /openedx/edx-platform/.github/test/tests_cms.sh cms/djangoapps/contentstore/views/tests/test_videos.py && docker-compose down -v

      - name: Push to koa
        if: github.ref == 'refs/heads/eol/koa.master'
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/edx-platform:${GITHUB_SHA}
          docker push eoluchile/edx-platform:koa
          docker push eoluchile/edx-platform:testing-koa
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
