name: Docker Image CI

on:
  push:
    branches:
      - 'eol-release/**'
      - 'openuchile-release/**'
      - 'vlabx-release/**'
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
    branches:
      - 'eol-release/**'
      - 'openuchile-release/**'
      - 'vlabx-release/**'
    paths-ignore:
      - '.github/workflows/**'
jobs:
  variables:
    uses: ./.github/workflows/variables.yml

  build:
    needs: [ variables ]
    runs-on: ubuntu-latest
    env:
      TS: ${{ needs.variables.outputs.timestamp }}
      RELEASE-NAME: ${{ needs.variables.outputs.release-name }}
      CODE: ${{ needs.variables.outputs.code }}
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v3-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v3-

      - name: Build Open edX Base
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target base \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --tag ghcr.io/eol-uchile/edx-platform:${GITHUB_SHA} \
            --tag ghcr.io/eol-uchile/edx-platform:${{ env.CODE }}-${{ env.RELEASE-NAME }}-${{ env.TS }} \
            --tag ghcr.io/eol-uchile/edx-platform:${{ env.CODE }}-${{ env.RELEASE-NAME }} \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
            --output "type=docker,push=false"

      - name: Build Open edX Testing version
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target testing \
            --build-arg EDX_PLATFORM_VERSION=${{ env.CODE }}-${{ env.RELEASE-NAME }}-${{ env.TS }} \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
            --output "type=docker,push=false"

      - name: Test edX platform
        run: |
          cd .github/test
          docker-compose run lms /openedx/edx-platform/.github/test/tests.sh

      - name: Push production image to the registry
        if: startsWith(github.ref, 'refs/heads/eol-release/') || startsWith(github.ref, 'refs/heads/openuchile-release/') || startsWith(github.ref, 'refs/heads/vlabx-release/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ghcr.io/eol-uchile/edx-platform:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-platform:${{ env.CODE }}-${{ env.RELEASE-NAME }}-${{ env.TS }}
          docker push ghcr.io/eol-uchile/edx-platform:${{ env.CODE }}-${{ env.RELEASE-NAME }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  webhook:
    needs: [ variables, build ]
    uses: ./.github/workflows/webhook.yml
    with:
      code: ${{ needs.variables.outputs.code }}
      release-name: ${{ needs.variables.outputs.release-name }}
    secrets: inherit
