#check package-lock file version

name: Lockfile Version check

on:
  push:
    branches:
      - release-ulmo
  pull_request:

jobs:
  version-check:
    uses: openedx/.github/.github/workflows/lockfileversion-check-v3.yml@master
