on:
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:fake

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile
          echo 'LABEL org.opencontainers.image.description "This image was built from commit ${{ github.sha }}"' >> Dockerfile

      - name: Build image
        run: docker build . -t ${IMAGE,,} # lowercase IMAGE

      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u $ --password-stdin

      - name: Publish image
        run: docker push ${IMAGE,,} # lowercase IMAGE
