name: Webhook Update staging

on:
  workflow_call:
    inputs:
      code:
        required: true
        type: string
      release-name:
        required: true
        type: string
    secrets:
      WEBHOOK_SECRET:
        required: true
  repository_dispatch:
    types: [debug-webhook]

jobs:
  triggering-staging:
    runs-on: ubuntu-latest
    if: inputs.code || github.event.client_payload.debug
    steps:
      - name: Trigger edx-staging repository
        run: |
          RELEASE_NAME=${{ inputs.release-name }};
          RELEASE_NAME=${RELEASE_NAME:-${{ github.event.client_payload.release-name }}};
          RELEASE_NAME=${RELEASE_NAME:-koa};
          if [[ "${{ inputs.code }}" = "eol" || "${{ github.event.client_payload.debug }}" = "eol" ]]
          then
            curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-staging/dispatches --data "{\"event_type\": \"update-image\", \"client_payload\": {\"version\": \"${RELEASE_NAME}\", \"project\": \"eol\", \"code\": \"eol\"}}"
          elif [[ "${{ inputs.code }}" = "ou" || "${{ github.event.client_payload.debug }}" = "ou" ]]
          then
            curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-staging/dispatches --data "{\"event_type\": \"update-image\", \"client_payload\": {\"version\": \"${RELEASE_NAME}\", \"project\": \"openuchile\", \"code\": \"ou\"}}"
          fi
