name: Webhook Update staging and production

on:
  workflow_call:
    inputs:
      code:
        required: true
        type: string
      release-name:
        required: true
        type: string
      is-prod:
        required: true
        type: string
  repository_dispatch:
    types: [debug-webhook]

jobs:
  triggering-repos:
    runs-on: ubuntu-latest
    if: ${{ inputs.code || github.event.client_payload.debug }}
    steps:
      - name: Create GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.EOLITO_BOT_APP_ID }}
          private-key: ${{ secrets.EOLITO_BOT_PRIVATE_KEY }}
          owner: eol-uchile
          repositories: edx-staging,eol-edx,edx-openuchile
      - name: Define release name
        id: release
        run: |
          RELEASE_NAME=${{ inputs.release-name }};
          RELEASE_NAME=${RELEASE_NAME:-${{ github.event.client_payload.release-name }}};
          RELEASE_NAME=${RELEASE_NAME:-koa};
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_OUTPUT
      - name: Trigger edx-staging repository branch eol
        if: ${{ ( inputs.is-prod == 'false' && inputs.code == 'eol' ) || ( github.event.client_payload.staging && github.event.client_payload.debug == 'eol' ) }}
        run: |
          curl --fail-with-body -X POST -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-staging/dispatches --data "{\"event_type\": \"update-image\", \"client_payload\": {\"version\": \"${{ steps.release.outputs.RELEASE_NAME }}\", \"project\": \"eol\", \"code\": \"eol\"}}"
      - name: Trigger edx-staging repository branch openuchile
        if: ${{ ( inputs.is-prod == 'false' && inputs.code == 'ou' ) || ( github.event.client_payload.staging && github.event.client_payload.debug == 'ou' ) }}
        run: |
          curl --fail-with-body -X POST -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-staging/dispatches --data "{\"event_type\": \"update-image\", \"client_payload\": {\"version\": \"${{ steps.release.outputs.RELEASE_NAME }}\", \"project\": \"openuchile\", \"code\": \"ou\"}}"
      - name: Trigger edx-eol repository
        if: ${{ ( inputs.is-prod == 'true' && inputs.code == 'eol' ) || ( github.event.client_payload.production && github.event.client_payload.debug == 'eol' ) }}
        run: |
          curl --fail-with-body -X POST -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/eol-edx/dispatches --data "{\"event_type\": \"update-image\", \"client_payload\": {\"version\": \"${{ steps.release.outputs.RELEASE_NAME }}\", \"project\": \"eol\", \"code\": \"eol\"}}"
      - name: Trigger edx-openuchile repository
        if: ${{ ( inputs.is-prod == 'true' && inputs.code == 'ou' ) || ( github.event.client_payload.production && github.event.client_payload.debug == 'ou' ) }}
        run: |
          curl --fail-with-body -X POST -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-openuchile/dispatches --data "{\"event_type\": \"update-image\", \"client_payload\": {\"version\": \"${{ steps.release.outputs.RELEASE_NAME }}\", \"project\": \"openuchile\", \"code\": \"ou\"}}"
