name: Webhook Update staging

on:
  workflow_run:
    workflows: ["Testing Image CI"]
    types:
      - completed
    branches:
      - 'eol/**'

jobs:
  triggering-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger edx-staging repository
        run: |
          curl -XPOST -u "eolito:${{secrets.WEBHOOK_SECRET}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-staging/dispatches --data '{"event_type": "update-image", "client_payload": {"version": "koa"}}'
