# Generated by Django 3.2.20 on 2023-07-26 18:49

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIPIISignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('user_id', models.IntegerField()),
                ('lti_tools_hash', models.IntegerField()),
            ],
        ),
    ]
