# Generated by Django 3.2.20 on 2023-08-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_ltipiisignature'),
        ('agreements', '0002_ltipiitool'),
    ]

    operations = [
    ]
