# Generated by Django 5.2.10 on 2026-01-26 10:22

import django.db.models.deletion
from django.db import migrations, models



def migrate_agreement_type(apps, schema_editor):
    UserAgreementRecord = apps.get_model('agreements', 'UserAgreementRecord')
    UserAgreement = apps.get_model('agreements', 'UserAgreement')
    for user_agreement_record in UserAgreementRecord.objects.all():
        user_agreement_record.agreement = UserAgreement.objects.get_or_create(type=user_agreement_record.agreement_type, defaults=dict(text=''))


def migrate_agreement_type_rev(apps, schema_editor):
    UserAgreementRecord = apps.get_model('agreements', 'UserAgreementRecord')
    for user_agreement_record in UserAgreementRecord.objects.all():
        user_agreement_record.agreement_type = user_agreement_record.agreement.type


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_historicaluseragreement_useragreement_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_agreement_type, migrate_agreement_type_rev),
        migrations.RemoveField(
            model_name='useragreementrecord',
            name='agreement_type',
        ),
        migrations.AlterField(
            model_name='useragreementrecord',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='agreements.useragreement'),
        ),
    ]
